### ISSUE TITLE
Struggling to get it to work behind jupyter-server-proxy

### ISSUE THREAD

**Issue by TPreece101** [mage-ai/mage-ai#1040]
Hello, I'm trying to get this up and running behind a jupyter-server-proxy and I'm getting some strange errors.

For context I have a JupyterHub server running in AWS that I use for development. Usually I can proxy ports for things like streamlit and code-server using jupyter-server-proxy by launching the process and visiting `{base_url}/proxy/{port}/` but it doesn't seem to be working with mage-ai

Steps I have followed:
1. pip installed `mage-ai`
2. run `mage start demo_project` and it creates the scaffolding and such then starts running the server like so:
![Screenshot 2022-09-12 at 18 08 19](https://user-images.githubusercontent.com/12260327/189714834-e4d75ad4-afa6-44dc-a664-748811709ddf.png)
3. Tried to visit the `{base_url}/proxy/6789/`url and I get a blank white page and some 404 errors in the JS Console along the lines of `GET https://{jupyter_hub_url}/hub/_next/static/css/9563de380da227ba.css net::ERR_ABORTED 404`

You can see on that screenshot that requests are getting to the web server but it looks like it's having trouble retrieving the assets for the page looks like it should be trying to retrieve them from `{base_url}/proxy/6789/_next/static/css/9563de380da227ba.css` (I can get the CSS file if I make a GET request to this address)

Any ideas why the routing isn't working? and why it seems to work fine with other projects e.g. streamlit ?

Let me know if you need any more details 😊

**Comment by wangxiaoyou1993** [comment]
Thanks for raising the issue! This is a routing issue of our static frontend files. We'll fix it ASAP.

**Comment by tommydangerous** [comment]
Thanks @TPreece101 for reporting!

**Comment by TPreece101** [comment]
No problem, thanks for the speedy response and I look forward to taking the library for a spin!

**Comment by dy46** [comment]
Hi @TPreece101, thanks for reporting the issue! Can you share how you get streamlit working with jupyter-server-proxy? Is there anything special you need to do to get it running?

**Comment by TPreece101** [comment]
Hey @dy46 no problem. Nope, nothing special for Streamlit or code-server. Just start the process running with `streamlit run app.py` and then visit `{base_url}/proxy/{port}/` <- Note the slash at the end but don't ask me why it's needed 😂 - it seems to be required for all port proxying using jupyter-server-proxy but it's not well documented.

**Comment by wangxiaoyou1993** [comment]
Hi @TPreece101 , sorry for the delay! We looked into this issue and it's not an easy fix on our end. I wonder how urgent the issue is to you. As an alternative, you can  try [running the tool locally](https://github.com/mage-ai/mage-ai#%EF%B8%8F-quick-start) or use our [terraform script](https://github.com/mage-ai/mage-ai/tree/master/docs/deploy/terraform) to deploy the tool on cloud.

**Comment by TPreece101** [comment]
No worries @wangxiaoyou1993, thanks for looking into it. It's not super urgent, it just means that I won't be able to try it out in my actual data pipelines. I have tried it out locally with demo data (I can't use prod data on my local machine) and unfortunately I don't have the right permissions to deploy the tool on our AWS account 😬.

I look forward to trying it out when you get around to it 😁

**Comment by tommydangerous** [comment]
You can use Mage locally and connect to AWS resources. Do you have an AWS Access Key ID and an AWS Secret Access Key?

If you add that into your io_config.yaml, Mage locally can read from S3, Redshift, etc.

You can even run PySpark from Mage locally to your remote EMR cluster.

**Comment by TPreece101** [comment]
Thanks for the suggestion @tommydangerous, unfortunately it's more of a security issue having prod data running through my local machine rather than a technical problem.

My workspace is exposed to me through a platform and so the AWS infrastructure is abstracted away from me unfortunately.

**Comment by TPreece101** [comment]
Hi Folks, glad to see how far this project has come since I last saw it, you guys are killing it!

Have you had any thoughts about this? I've recently encountered the same problem with Dash apps in my environment. The way that they accommodate this kind of thing is that they have an environment variable `DASH_REQUESTS_PATHNAME_PREFIX` which allows you to insert a custom prefix, so in my example I set it to be `f"/user/{os.getenv('USER')}/proxy/8050/"` to work well behind jupyter-server-proxy.

I'm wondering whether it might be worth considering something like this for mage? It might have some good benefits when it comes to deploying in different environments 😊

**Comment by thomaschung408** [comment]
Hello @TPreece101! Thank you for kind words! We'll look into this and get back to you soon!

**Comment by TPreece101** [comment]
Cool, let me know if you need any extra info @thomaschung408

**Comment by rezo1134** [comment]
Bump for this! However if whatever implementation could consider reverse proxies like Traefik or nginx in gerenal that would be awesome.

**Comment by dy46** [comment]
Hey @TPreece101 and others on this thread, we finally added something to resolve this issue. You can set the `MAGE_REQUESTS_BASE_PATH` environment variable (similar to the Dash environment variable in the earlier comment) to be `proxy/6789` if your url is `<base url>/proxy/6789`, and you should be able to access Mage that way.
