### ISSUE TITLE
Can't query logs by start timestamp and end timestamp

### ISSUE THREAD

**Issue by wangxiaoyou1993** [mage-ai/mage-ai#1117]
Fetching logs takes a long time. Example link: http://demo.mage.ai/pipelines/example_pipeline/logs

Support fetching logs by start and end timestamp will help a lot.

Additionally, some empty logs are shown at the top. We should filter them out.

<img width="1429" alt="image" src="https://user-images.githubusercontent.com/80284865/193360474-c8c792aa-0fee-4025-9586-ea26ff74549e.png">

**Comment by soumojit** [comment]
@wangxiaoyou1993 i would like to take this up!

**Comment by wangxiaoyou1993** [comment]
> @wangxiaoyou1993 i would like to take this up!

Sure, I'll assign this to you. Thank you!

**Comment by wangxiaoyou1993** [comment]
Backend PR: https://github.com/mage-ai/mage-ai/pull/1203

**Comment by johnson-mage** [comment]
Frontend PR: https://github.com/mage-ai/mage-ai/pull/1218

**Comment by johnson-mage** [comment]
Should be able to fetch logs within a time range now:
<img width="954" alt="image" src="https://user-images.githubusercontent.com/78053898/197073324-3adbb67c-923d-4856-8d40-e7f98e5feda4.png">
