### ISSUE TITLE
Can't filter pipeline runs by status

### ISSUE THREAD

**Issue by wangxiaoyou1993** [mage-ai/mage-ai#1118]
When debugging the failed pipeline runs, it'll be helpful to add the filter to filter pipeline runs or block runs by status (failed, pending, etc.).

<img width="1508" alt="image" src="https://user-images.githubusercontent.com/80284865/193360994-0bd4129d-ed85-4c8c-917f-1f68df599587.png">

**Comment by soumojit** [comment]
@wangxiaoyou1993 I would like to work on this. 

URL: http://localhost:6789/api/pipeline_runs?_limit=30&_offset=0
The query params are [_limit, _offset]

I can extend this to include _status. 
Are there any other filter params that you would like to include?

**Comment by tommydangerous** [comment]
🙌 🙌 🙌

**Comment by wangxiaoyou1993** [comment]
Thank you @soumojit! Adding `status` filter should be good enough for now.

**Comment by soumojit** [comment]
Thanks @wangxiaoyou1993 

Currently [_limit, _offset] are being passed but they are not being issued. I will fix that too!
<img width="1435" alt="Screenshot 2022-10-11 at 3 39 42 AM" src="https://user-images.githubusercontent.com/38524508/194959889-8398a610-9268-4a7d-a7b6-f97c436cc799.png">

**Comment by wangxiaoyou1993** [comment]
Hi @soumojit 
I think [_limit, _offset] are being used for filtering now. You can check the code here: https://github.com/mage-ai/mage-ai/blob/master/mage_ai/server/api/orchestration.py#L134

**Comment by soumojit** [comment]
@wangxiaoyou1993, you are right. Thank you!

**Comment by wangxiaoyou1993** [comment]
Backend PR: https://github.com/mage-ai/mage-ai/pull/1159

**Comment by johnson-mage** [comment]
Frontend PRs: https://github.com/mage-ai/mage-ai/pull/1265 and https://github.com/mage-ai/mage-ai/pull/1264
