### ISSUE TITLE
Can't see full message in the logs

### ISSUE THREAD

**Issue by wangxiaoyou1993** [mage-ai/mage-ai#1283]
**Describe the bug**
Long message gets cut off in logs.
<img width="822" alt="image" src="https://user-images.githubusercontent.com/80284865/199138711-9ecd9f40-ce45-4661-9e4b-7586d4ab7bec.png">

**Comment by johnson-mage** [comment]
@wangxiaoyou1993 So we can see the whole log message via a tooltip if we hover over it (already worked in the log detail window and works in the logs list view after merging this [PR](https://github.com/mage-ai/mage-ai/pull/1292)). If there is a lot of utility in viewing the entire message in the UI (e.g. for copying it to clipboard), that's a feature we can add. The tooltip should solve the issue of cutoff logs though.

**Comment by johnson-mage** [comment]
PR that allows user to show full log in UI: https://github.com/mage-ai/mage-ai/pull/1304
