### ISSUE TITLE
Edit pipeline name missing on Firefox

### ISSUE THREAD

**Issue by acirtep** [mage-ai/mage-ai#1388]
**Describe the bug**
On Firefox the edit name of the pipeline does not exist.

**To Reproduce**
1. Go to pipelines
2. Click on Edit pipeline

**Expected behavior**
There should be the possibility to rename the pipeline. 

**Screenshots**
<img width="831" alt="Screenshot 2022-11-15 at 06 25 39" src="https://user-images.githubusercontent.com/33284782/201833501-353caec5-66c9-429f-ae5a-1992e60bf09a.png">

**Desktop (please complete the following information):**
 - OS: OS Monterey
 - Browser firefox
 - Version 106.0.1
 - mage-ai = 0.6.3

**Additional context**

**Comment by tommydangerous** [comment]
This might be due to a malformed pipeline YAML file.

Can you go into default_repo/pipelines/blue_river/metadata.yaml and share the contents?

Change default_repo to the name of your Mage project.

**Comment by acirtep** [comment]
It is an empty pipeline:
```
name: blue river
type: python
uuid: blue_river
```

**Comment by tommydangerous** [comment]
Try changing it to this:

name: blue river
type: python
uuid: blue_river
blocks: []
widgets: []

**Comment by acirtep** [comment]
The issue is truly with Firfox, on Safari the option exists
<img width="808" alt="Screenshot 2022-11-15 at 06 42 16" src="https://user-images.githubusercontent.com/33284782/201835792-e654e029-d4f5-4da9-af8d-83a5f0bf9c27.png">

**Comment by tommydangerous** [comment]
Thanks for reporting. We'll debug this ASAP. Sorry for the inconvenience.

**Comment by tommydangerous** [comment]
Can you also try using the latest version 0.7.5?

**Comment by acirtep** [comment]
Tested with 0.7.5 and it has the same behavior.

**Comment by tommydangerous** [comment]
Will debug on our end, sorry for the inconvenience.

**Comment by johnson-mage** [comment]
Hi @acirtep, sorry for the delay, but this issue should be addressed in the latest version (v0.8.5). PR: https://github.com/mage-ai/mage-ai/pull/2058
