### ISSUE TITLE
One hot encoding as a transform

### ISSUE THREAD

**Issue by ajatau** [mage-ai/mage-ai#1396]
**Is your feature request related to a problem? Please describe.**
One Hot Encoding is used to convert numerical categorical variables into binary vectors. This is generally performed during the data preprocessing step.
Mage-Ai includes some common used transformations but one hot encoding is not a part of the tool right now. 

**Describe the solution you'd like**
User is able to select “One Hot Encoding” from the “Transformer” option on the tool. Once the use selects it, the transformation step is added in the pipeline and return the data including  the one hot encoded (get dummies) is performed.

**Additional context**
I intend to implement using the scikit learn library

**Comment by tommydangerous** [comment]
Sorry for the delay, will take a look 👀

**Comment by tommydangerous** [comment]
Here is another PR that added a new transformer: https://github.com/mage-ai/mage-ai/pull/1277

This might be helpful.

**Comment by wangxiaoyou1993** [comment]
@ajatau I'd like to follow up on this ticket. Are you still planning to implement this feature?

**Comment by ajatau** [comment]
@wangxiaoyou1993 yes I have implemented already just waiting for the merge https://github.com/mage-ai/mage-ai/pull/1449

**Comment by wangxiaoyou1993** [comment]
> @wangxiaoyou1993 yes I have implemented already just waiting for the merge #1449

Oh, thank you!  I'll review your PR today!

**Comment by thomaschung408** [comment]
Hello @ajatau! I'm following up to see if you were able to address the comments from the PR review https://github.com/mage-ai/mage-ai/pull/1449

Please let us know if you have any questions. Thank you!

**Comment by wangxiaoyou1993** [comment]
Close this ticket since there's no follow up on the PR. Feel free to reopen it if you still need this feature.
