### ISSUE TITLE
Add dbt snapshot as option

### ISSUE THREAD

**Issue by acirtep** [mage-ai/mage-ai#1399]
**Is your feature request related to a problem? Please describe.**
N/A

**Describe the solution you'd like**
I would like to be able to execute dbt snapshots as well: https://docs.getdbt.com/docs/build/snapshots.

**Describe alternatives you've considered**
N/A

**Additional context**

Thank you!

**Comment by tommydangerous** [comment]
Sorry for the delay, will take a look 👀

**Comment by tommydangerous** [comment]
Some updates on this feature request: we’re scoping the work and drafting a technical design. Thank you so much for your patience.

**Comment by thomaschung408** [comment]
Hi @acirtep! We've also added dbt snapshots as an option to the roadmap and currently planned to be release by the end of the quarter as well. You can see our current roadmap here: https://airtable.com/shrJctaGt4tvU27uF/tbl5bIlFkk2KhCpL4

Thank you for your patience and we'll keep you posted!

**Comment by wangxiaoyou1993** [comment]
@acirtep dbt snapshot is supported now. here is the doc: https://docs.mage.ai/dbt/snapshots
