### ISSUE TITLE
As a user, I want to kick off a new pipeline run from the pipeline list view

### ISSUE THREAD

**Issue by tommydangerous** [mage-ai/mage-ai#1503]
**Is your feature request related to a problem? Please describe.**

**Describe the solution you'd like**

**Describe alternatives you've considered**

**Additional context**

**Comment by wangxiaoyou1993** [comment]
This feature is achieved with the "Run pipeline now" button.
<img width="180" alt="image" src="https://user-images.githubusercontent.com/80284865/210662683-d76999ab-8eb1-4339-96e9-9c8bd9c482fa.png">
