### ISSUE TITLE
As a user, I want to execute a function if a block run fails or succeeds

### ISSUE THREAD

**Issue by tommydangerous** [mage-ai/mage-ai#1504]
**Is your feature request related to a problem? Please describe.**

**Describe the solution you'd like**

**Describe alternatives you've considered**

**Additional context**

**Comment by wangxiaoyou1993** [comment]
This is supported by callback block block: https://docs.mage.ai/development/blocks/callbacks/overview#how-to-add-callbacks-to-your-pipeline
