### ISSUE TITLE
As a user, I want to get alerts for specific run statuses; e.g. only get alerted when runs fail

### ISSUE THREAD

**Issue by tommydangerous** [mage-ai/mage-ai#1505]
**Is your feature request related to a problem? Please describe.**

**Describe the solution you'd like**

**Describe alternatives you've considered**

**Additional context**

**Comment by wangxiaoyou1993** [comment]
This is supported in `notification_config`
Example:
```
notification_config:
  alert_on:
    - trigger_failure
    - trigger_passed_sla
``` 
Doc: https://docs.mage.ai/production/observability/alerting-slack#update-mage-project-settings
