### ISSUE TITLE
As a user, I want to see the current run time and the final execution time for each pipeline run from the pipeline runs view

### ISSUE THREAD

**Issue by tommydangerous** [mage-ai/mage-ai#1506]
**Is your feature request related to a problem? Please describe.**

**Describe the solution you'd like**

**Describe alternatives you've considered**

**Additional context**

**Comment by wangxiaoyou1993** [comment]
The final execution time is supported in pipeline runs view now: 
<img width="809" alt="image" src="https://github.com/mage-ai/mage-ai/assets/80284865/d4e157db-a47a-4aaa-bcee-00cf5d2a4cb1">
