### ISSUE TITLE
As a user, I want data loader and data exporter templates for Azure SQL

### ISSUE THREAD

**Issue by tommydangerous** [mage-ai/mage-ai#1508]
**Is your feature request related to a problem? Please describe.**

**Describe the solution you'd like**

**Describe alternatives you've considered**

**Additional context**

**Comment by MinuraPunchihewa** [comment]
Hey @tommydangerous,
I would like to give this a go, if that's OK. This will be my first time contributing, so if you have any docs or examples I could refer, I'd really appreciate that.

**Comment by tommydangerous** [comment]
Hey @MinuraPunchihewa!!!

That would be super duper amazing!

@johnson-mage can share some example files and pointers on how to add these templates.

The data engineering community thanks you so much for helping!

**Comment by MinuraPunchihewa** [comment]
Hey @johnson-mage,
Will you be able to share the examples mentioned above, please?

**Comment by johnson-mage** [comment]
> Hey @johnson-mage, Will you be able to share the examples mentioned above, please?

Hi @MinuraPunchihewa, thanks for the reminder, just saw this thread. So sorry I missed it earlier in the month. This is where we keep the files for the actual templates that you can refer to:
Data loaders: https://github.com/mage-ai/mage-ai/tree/master/mage_ai/data_preparation/templates/data_loaders
Data exporters: https://github.com/mage-ai/mage-ai/tree/master/mage_ai/data_preparation/templates/data_exporters

The naming of the template file depends on the name of the data_source in the Block POST request payload's config. You can refer to this [PR](https://github.com/mage-ai/mage-ai/pull/2219/files#diff-588562728f62f61400e08f3f50e91b16e218bc675c85cf376c28bec98aa71b8a) where David added sensor templates.  You may need to update the data source types in this [file](https://github.com/mage-ai/mage-ai/blob/master/mage_ai/frontend/interfaces/DataSourceType.ts) to include Azure SQL.

When a block is added, we call the `create` method in the this [file](https://github.com/mage-ai/mage-ai/blob/master/mage_ai/data_preparation/models/block/__init__.py), and this is where we load the templates: https://github.com/mage-ai/mage-ai/blob/master/mage_ai/data_preparation/models/block/__init__.py#L474-L480

If you have any questions, it'll be easier to reach me through our [Slack](https://www.mage.ai/chat) channel. You can just DM me. Thanks!

**Comment by MinuraPunchihewa** [comment]
@johnson-mage Thank you very much. I will have a look and start my work as soon as I can.

**Comment by wangxiaoyou1993** [comment]
This feature is supported now. Azure SQL is Microsoft SQL Server: https://docs.mage.ai/integrations/databases/MicrosoftSQLServer
