### ISSUE TITLE
As a user, I want to see all unused data loaders, transformers, scratchpads, data exporters, charts, and sensors and be able to easily delete them.

### ISSUE THREAD

**Issue by tommydangerous** [mage-ai/mage-ai#1511]
**Is your feature request related to a problem? Please describe.**

**Describe the solution you'd like**

**Describe alternatives you've considered**

**Additional context**

**Comment by johnson-mage** [comment]
We updated the file browser to indicate unused block files in this [PR](https://github.com/mage-ai/mage-ai/pull/4449). Here are the [docs](https://docs.mage.ai/developer-ux/file-browser#block-files-used-unused-by-pipelines). Files can easily be deleted from the file browser by right-clicking the file and selecting `Delete file`.
