### ISSUE TITLE
As a user, I want to see the timestamps in logs in a specific timezone vs the default UTC timezone

### ISSUE THREAD

**Issue by tommydangerous** [mage-ai/mage-ai#1512]
**Is your feature request related to a problem? Please describe.**

**Describe the solution you'd like**

**Describe alternatives you've considered**

**Additional context**

**Comment by wangxiaoyou1993** [comment]
This feature is released. https://docs.mage.ai/development/project/local-timezone#steps-to-enable-local-timezone-setting
