### ISSUE TITLE
As a user, I want to be able to run complex pipelines where each task runs in its own Docker container

### ISSUE THREAD

**Issue by asydorchuk** [mage-ai/mage-ai#1553]
**Is your feature request related to a problem? Please describe.**
Yes, the problem is that in complex production environments, different tasks within a pipeline often require different programming languages and/or Python environments. This can make it difficult to manage and execute these tasks in an efficient and scalable way.

**Describe the solution you'd like**
I would like the ability to define pipelines where tasks can be executed in separate Docker containers, potentially using multiple Docker images. This would allow for better isolation and management of the different environments and languages required for each task.

**Describe alternatives you've considered**
One alternative that I have considered is using Argo to run tasks as Docker containers. However, using YAML to define pipelines can become unwieldy for larger projects and organizations. In the past, I have worked on production projects where we used Airflow with the KubernetesPodOperator, which provided a more scalable solution.

**Additional context**
If Mage is intended as a replacement for Airflow, it is important that it support the most common setup used by mature organizations in production environments. This includes the ability to run each task in its own isolated environment using Docker containers.

**Comment by wangxiaoyou1993** [comment]
Hi @asydorchuk ,  thanks for creating this request.
Currently, we do support running the tasks in separate containers in AWS via ECS tasks. You can also customize the compute resource of the ECS task: https://github.com/mage-ai/mage-ai/blob/master/docs/production/compute_resource.md#ecs-executor
We'll support running tasks in containers in other platforms soon.

Which cloud provider are you using now?

**Comment by asydorchuk** [comment]
Hi @wangxiaoyou1993, I am using Google Cloud mainly.

Thanks for the reference to AWS, I will check how it works with it.

**Comment by GhisF** [comment]
An easy way to run docker containers on the local infrastructure is possible ?

**Comment by wangxiaoyou1993** [comment]
@GhisF Currently, all the tasks run in the same container locally. We'll support running tasks in separate containers locally this week.

**Comment by Mautriz** [comment]
Hi! I would add that a generic "kubernetes executor" would be great instead of platform specific ones (as well as the docker executor mentioned above I guess)

**Comment by wangxiaoyou1993** [comment]
> Hi! I would add that a generic "kubernetes executor" would be great instead of platform specific ones (as well as the docker executor mentioned above I guess)

Thanks for bringing it up. Adding the generic "kubernetes executor" is on our short term roadmap as well. This will be supported in one or two weeks.

**Comment by wangxiaoyou1993** [comment]
To give an update here, running tasks in separate kubernetes pods via "kubernetes executor" is supported in Mage now.
* https://docs.mage.ai/getting-started/setup#using-kubernetes
* https://docs.mage.ai/production/configuring-production-settings/compute-resource#2-customize-the-compute-resource-of-the-mage-executor

cc: @GhisF @Mautriz

**Comment by eddylit** [comment]
@wangxiaoyou1993 do you plan on supporting Azure Container Instances for running tasks in containers?

**Comment by wangxiaoyou1993** [comment]
> @wangxiaoyou1993 do you plan on supporting Azure Container Instances for running tasks in containers?

Hi @eddylit , supporting Azure Container instances for running tasks is definitely on our roadmap. Could you let us know when you need this by? It'll help us better prioritize the feature.

**Comment by wangxiaoyou1993** [comment]
@eddylit Running the tasks in separate Azure Container instances is supported now. https://docs.mage.ai/production/configuring-production-settings/compute-resource#azure-container-instance-executor

**Comment by utopic-men** [comment]
> An easy way to run docker containers on the local infrastructure is possible ?
 
Hello, perhaps I missed something but Docker containers doesn’t seem to be a possibility. Am I right ?

Thanks for your response

**Comment by wangxiaoyou1993** [comment]
> > An easy way to run docker containers on the local infrastructure is possible ?
> 
> Hello, perhaps I missed something but Docker containers doesn’t seem to be a possibility. Am I right ?
> 
> Thanks for your response

You can use local k8s cluster if your want to run jobs in separate docker containers locally

**Comment by matbalc-derisk** [comment]
> @GhisF Currently, all the tasks run in the same container locally. We'll support running tasks in separate containers locally this week.

Are there any documentation how to achieve this? In pipelines metadata, there are no such option as execution_type

**Comment by wangxiaoyou1993** [comment]
@matbalc-derisk Here is the doc: https://docs.mage.ai/production/configuring-production-settings/compute-resource#2-set-executor-type-and-customize-the-compute-resource-of-the-mage-executor
