### ISSUE TITLE
Can you provide support for user authentication so that we can set up different groups of users?

### ISSUE THREAD

**Issue by c0090555** [mage-ai/mage-ai#1627]
**Is your feature request related to a problem? Please describe.**
We are planning to set up a local instance of Mage and are wondering if it is possible to support user authentication. We would like different users to be able to have their own unique account settings."

**Describe the solution you'd like**
User authentication.

**Describe alternatives you've considered**
Grouping on a shared account.

**Additional context**
N/A

**Comment by tommydangerous** [comment]
Thank you @c0090555 for submitting this. User authentication is on our very near term roadmap. Many companies have already requested this so we’re moving things around to better prioritize it.

How urgent is it for your company?

**Comment by c0090555** [comment]
At present, this feature is preventing further usage of the product. It would be greatly appreciated if this feature could be added in the near future, if possible.

**Comment by tommydangerous** [comment]
@c0090555 we'll prioritize this immediately to be available in next week's release.

I'll reach out to you directly when it's available.

Can you please send me an email at tommy@mage.ai so I know who to email as soon as this feature is live?

**Comment by nc-sika** [comment]
Hi @tommydangerous ,
When is this expected to be ready for release? We'll adopt Mage internally as soon as this  is released :-)

**Comment by tommydangerous** [comment]
@nc-sika its being tested as we speak. It'll be in this week's big release!

I'll ping you when it's live this week 🚀

**Comment by tommydangerous** [comment]
@c0090555 @nc-sika 

User login, management, authentication, roles, permissions: https://docs.mage.ai/production/authentication/overview

Is live!

**Comment by c0090555** [comment]
@tommydangerous Great! Thanks for the updates!

**Comment by tommydangerous** [comment]
@c0090555 please let me know if you have any questions, issues, or need any feature adjustments.

You can ping me here or directly on Slack: https://www.mage.ai/chat
