### ISSUE TITLE
Outdated default IO query limit in documentation

### ISSUE THREAD

**Issue by jlondonobo** [mage-ai/mage-ai#1707]
**Describe the bug**
The documentation states that the default query limit for loading data from the cloud is 100,000 rows. #779 bumped this value to 10,000,000 rows.

**To Reproduce**
1. Go to the [data loading](https://docs.mage.ai/design/data-loading) documentation.
2. CMD + F into "100,000".

**Screenshots**
![image](https://user-images.githubusercontent.com/43001823/211213054-681871e5-13d7-4889-a6d0-8c8869dc3a54.png)

**Additional context**
I opened a PR to update this value (#1706)

**Comment by tommydangerous** [comment]
Thank you for sharing

**Comment by wangxiaoyou1993** [comment]
Thank you @jlondonobo for fixing the doc in this PR! https://github.com/mage-ai/mage-ai/pull/1706
