### ISSUE TITLE
HTML Select element has bad background on dark theme

### ISSUE THREAD

**Issue by lucafaggianelli** [mage-ai/mage-ai#1739]
**Describe the bug**
The Select input element in the New/Edit trigger page has a background not in line with the website theme: in my case I have a dark theme and the select menu has a white background with white text

**To Reproduce**
1. Create a pipeline
2. Create a trigger
3. Go to the trigger settings
4. Open the Frequency menu and observe the background

**Expected behavior**
The background should be in line with the current website theme

**Screenshots**

![image](https://user-images.githubusercontent.com/4471043/212341208-a0c4e7c4-3b36-4a8f-a29b-39990fe2c388.png)

**Desktop (please complete the following information):**
 - OS: Microsoft Windows 10 Enterprise
 - Browser: Chrome
 - Version: 108.0.5359.125

**Additional context**
My OS preference is to use a dark theme, so I see mage with a dark theme, I don't know if there's a light theme as well

**Comment by tommydangerous** [comment]
Thank you so much for sharing, will fix this.

**Comment by thomaschung408** [comment]
Hi @lucafaggianelli! We've added this to the roadmap and should be released in the upcoming week. You can see our current roadmap here: https://airtable.com/shrJctaGt4tvU27uF/tbl5bIlFkk2KhCpL4

Thank you for your patience and we'll keep you posted!

**Comment by johnson-mage** [comment]
Fixed by https://github.com/mage-ai/mage-ai/pull/1965
