### ISSUE TITLE
non-ascii chars are mistreated

### ISSUE THREAD

**Issue by lucafaggianelli** [mage-ai/mage-ai#1740]
**Describe the bug**
My code contains non-ascii chars (in particular the Euro symbol `€`) but Mage transforms it into an unknown symbol

PS: for the moment I found a workaround saving the python string as a unicode string:

```py
u"\N{euro sign}"
```

**To Reproduce**
1. Create a pipeline in Mage UI
2. Somewhere in your pipeline code type a non-ascii char like the EUR symbol `€`
3. Wait for the file to be saved automatically
4. go to your IDE and open the python file
5. the non-ascii char should be corrupted

You can also do the opposite:
1. Create a pipeline in Mage UI
2. Edit the pipeline file in you IDE (not in Mage UI)
3. Somewhere in your pipeline code type a non-ascii char like the EUR symbol `€`
4. Save the file
5. Refresh Mage pipeline page
6. the non-ascii char should be corrupted

**Expected behavior**
UTF-8 chars should be supported

**Screenshots**
I type the EUR symbol in my IDE:
![image](https://user-images.githubusercontent.com/4471043/212366994-5a040849-4013-4d1b-9b4f-c893b3a0b15d.png)

And when I open the pipeline in Mage, in the browser, this is the result:
![image](https://user-images.githubusercontent.com/4471043/212367199-b5bdc796-b86f-434b-ae13-e6406a22a5f2.png)

Also the opposite doesn't work, if I type the EUR symbol in Mage IDE in the browser, when I open the python file in my IDE, the symbol is corrupted

**Desktop (please complete the following information):**
 - OS: Win 10
 - Browser: Chrome
 - Version: 108

**Additional context**
*None*

**Comment by wangxiaoyou1993** [comment]
thanks for reporting the bug! we'll fix it ASAP.

**Comment by thomaschung408** [comment]
Hi @lucafaggianelli! We should have this fixed by next week! We'll keep you posted!

**Comment by wangxiaoyou1993** [comment]
This issue has been fixed.
