### ISSUE TITLE
As a user I would like to edit global variables in the pipeline page

### ISSUE THREAD

**Issue by lucafaggianelli** [mage-ai/mage-ai#1741]
**Is your feature request related to a problem? Please describe.**
Once you create a global variable in the pipeline page, it cannot be changed (nor the name neither the value)

**Describe the solution you'd like**
Make the variable name and value editable

**Describe alternatives you've considered**
you have to delete the var and recreate it, or as a shortcut you can re-create a variable with the same name
if you just want to change the value

**Additional context**
![image](https://user-images.githubusercontent.com/4471043/212371745-7a4763e4-7fa6-4abe-8e3b-93ee1db14800.png)

**Comment by tommydangerous** [comment]
Thank you so much for sharing @lucafaggianelli.

Great idea, will add it.

**Comment by dy46** [comment]
hey @lucafaggianelli, this feature was added in version 0.7.90. thanks for the feature request!
