### ISSUE TITLE
Pipeline doesn't run on Windows due to free memory check

### ISSUE THREAD

**Issue by lucafaggianelli** [mage-ai/mage-ai#1756]
**Describe the bug**
The free memory check via `free` cmd line doesn't work on Windows as a consequence the pipeline heartbeat fails and the pipelines don't run.

The responsible code is here:
https://github.com/mage-ai/mage-ai/blame/master/mage_ai/orchestration/utils/resources.py#L22

As a workaround I set some dummy default values instead of None and that does the trick:
```py
free_memory = 100
total_memory = 100
used_memory = 0
```

Error message:
```
'free' is not recognized as an internal or external command,
operable program or batch file.
list index out of range
```

Then the actual crash happens because there is a division between None and None:

https://github.com/mage-ai/mage-ai/blame/master/mage_ai/orchestration/pipeline_scheduler.py#L368

**To Reproduce**
1. Run a version of mage >= 0.7.66 on windows
2. run a pipeline
3. Look at the console message

**Expected behavior**
The pipeline should run

**Screenshots**
None

**Desktop (please complete the following information):**
 - OS: Win 10
 - Browser: Chrome
 - Version: 108

**Additional context**
-

**Comment by tommydangerous** [comment]
So sorry about this issue. We’ll fix it ASAP.

**Comment by tommydangerous** [comment]
If you pull the latest Docker image, this should be resolved.
