### ISSUE TITLE
Matrix run trigger

### ISSUE THREAD

**Issue by lucafaggianelli** [mage-ai/mage-ai#1758]
**Is your feature request related to a problem? Please describe.**
As a user I would like to run 1 pipeline with different input variables, resulting in N runs of the same pipeline at the same time. The input would be provided as a list of values for each variable and optionally in a *matrix* fashion.

**Describe the solution you'd like**
When I create a trigger I would like to override the runtime variables (this is already supported) providing a list of values.
Saying I have a runtime variable called `days_before`, I would like to create a trigger that overrides the runtime variable `days_before` passing a list of values, i.e.: `1,2,3` this should result in running the pipeline 3 times, once with a different value of `days_before`.

I would also like to use a *Matrix run* feature so if I have the following variables:
* `days_before=[1, 2, 3, 4]`
* `view_type=['view_1', 'view_2']`

I would like to run the pipeline 8 times with all the combinations of values, i.e.:
* `days_before=1; view_type='view_1'`
* `days_before=2; view_type='view_1'`
* `days_before=3; view_type='view_1'`
* `days_before=4; view_type='view_1'`
* `days_before=1; view_type='view_2'`
* `days_before=2; view_type='view_2'`
* `days_before=3; view_type='view_2'`
* `days_before=4; view_type='view_2'`

**Describe alternatives you've considered**
A workaround is to create multiple triggers overriding the runtime variables, but it's very verbose and not easy to maintain when the variations are many.

In my case I have 2 variables:
* `days_before=[1, 2, 3, 4]`
* `view_type=['view_1', 'view_2']`

so I needed to create 8 triggers resulting from all the combinations of the 2 variables.

**Additional context**
None

**Comment by tommydangerous** [comment]
Check out dynamic blocks: https://docs.mage.ai/design/blocks/dynamic-blocks

Tutorial: https://docs.mage.ai/guides/blocks/dynamic-blocks

This might for what you need.

**Comment by lucafaggianelli** [comment]
Ah nice indeed it should do the work! I'll check the docs

**Comment by tommydangerous** [comment]
Awesome! If the dynamic blocks don’t solve your needs, please re-open this issue.
