### ISSUE TITLE
Pass runtime variables to test functions

### ISSUE THREAD

**Issue by lucafaggianelli** [mage-ai/mage-ai#1766]
**Is your feature request related to a problem? Please describe.**
As a user I would like to access runtime variables in test functions

**Describe the solution you'd like**
The test functions should accept a `kwargs` argument like other block functions:

```py
@test
def test_data_readiness(df: pd.DataFrame, *args, **kwargs) -> None:
  pass
```

**Describe alternatives you've considered**

**Additional context**

**Comment by dy46** [comment]
heyr @lucafaggianelli, a fix for this issue is included in the latest mage version. let me know if you have any further issues
