### ISSUE TITLE
Feedback: some missing features / bugs?

### ISSUE THREAD

**Issue by paolorechia** [mage-ai/mage-ai#1799]
Hi, everyone.

First, thanks for this project, it looks very promising. Unfortunately, I still found that some features missing (and maybe bugs?). I'm just wondering if these things have been reported before - I could also go and refine this and create better issues separately if it makes sense.

I'm using local docker setup on Ubuntu, and Firefox as the browser.

1. Copy/paste doesn't work in the terminal.
2. Cannot create packages/modules/files in the `utils` directory through the UI. This is still possible using `touch` and `mkdir` through the terminal.
3. When I click on a file on the left side, I have access to the source code, which I can edit. However, if I make modifications, the only button that seems relevant is _Add to current pipeline._ **If this button is clicked and the task is already used by the pipeline, then an error occurs and the **changes are lost**.

**Comment by tommydangerous** [comment]
So sorry for the inconvenience and troubles.

1. Copy and paste isn't supported in the Mage terminal yet, we'll be adding that shortly.
2. You can't create or upload files through the UI yet, but that's launching in February.
3.

**Comment by paolorechia** [comment]
Hi, @tommydangerous , thanks for the reply! No need to apologize, I understand this is not v1 yet :)

Regarding point 3
> In order to save the file, press the Command + S keys together as if you were saving changes in a text editor. We'll add a button to make it more obvious.

I'm using Linux, I did try saving with `Ctrl + S` but I still run into this issue. It seems the changes are only persisted when I'm going through the edit pipeline UI, at least for the tasks that already exist in a pipeline.

**Comment by tommydangerous** [comment]
We’ll fix number 3 to make it easier to save files. So sorry about the inconvenience.

**Comment by tommydangerous** [comment]
@paolorechia number 2 is now live!

3: We added a button to save the file!

**Comment by tommydangerous** [comment]
1: Will be launched in this week’s version release

**Comment by paolorechia** [comment]
Hi, thanks a lot again for the effort here.

I’ll give the new version a try when I get some free time.

**Comment by tommydangerous** [comment]
Excited for you to try it out!

**Comment by tommydangerous** [comment]
@paolorechia once it works for you and satisfies all your requirements, please let us know so we can close the issue.
