### ISSUE TITLE
Importing python module, document or feature missing

### ISSUE THREAD

**Issue by amoghkokari** [mage-ai/mage-ai#1813]
**Is your feature request related to a problem? Please describe.**
yes, I am not able to import stopwords library into my text processing pipeline

**Describe the solution you'd like**
A guideline for user to import python libraries and use them while running the pipeline

**Describe alternatives you've considered**
tried to install using pip, dint work

**Additional context**

**Comment by tommydangerous** [comment]
Hello @amoghkokari!

Are you running Mage in Docker or did you install Mage using `pip`?

Also, if you want more real-time help, you can get instant chat on Slack: https://www.mage.ai/chat

**Comment by amoghkokari** [comment]
Hi @tommydangerous 

I did pip install, Yes, I will check https://www.mage.ai/chat. Also the code is taking too long to execute for lambda functions
