### ISSUE TITLE
Access Global Variables Using R

### ISSUE THREAD

**Issue by ChengzhiZhao** [mage-ai/mage-ai#1842]
I can see documentation on python and SQL to access the global variable like `execution_date`. However,  I couldn't find a way to get the context for R, and further access to the global variables is not documented here https://docs.mage.ai/guides/r-blocks. Anything I missed here? Appreciate your help!

**Comment by tommydangerous** [comment]
Hello @ChengzhiZhao,

Have you tried using something like this:

```R
library("pacman")
p_load(dplyr)

transform <- function(df_1, ...) {
    # Specify your transformation logic here
    # Return value: transformed dataframe.
    df_1 <- filter(df_1, Pclass < 3)
    df_1
}
```

The values after the `df_1` argument should contain the variables like `execution_date`.

Also, for instant response and faster help, you can join the Mage community Slack (https://www.mage.ai/chat) and get instant replies.

I’d also love to hear more feature requests from you as well.

Thank you so much for your amazing blog!

**Comment by tommydangerous** [comment]
Hello @ChengzhiZhao, we just recently added support for using global variables and runtime variables in R blocks.

Please pull the latest docker image and use this in your code:

```R
global_vars['execution_date']
```

**Comment by tommydangerous** [comment]
@ChengzhiZhao did this work for you? If it works, please let us know. Then, we’ll close this issue.

**Comment by ChengzhiZhao** [comment]
Thanks @tommydangerous I can verify with the latest build, right on time this PR merged 20h ago https://github.com/mage-ai/mage-ai/pull/1845. I close the one now.

**Comment by ChengzhiZhao** [comment]
One small suggestion is to update the variable tab with more instruction for SQL and R (or point to the documentation link)
<img width="599" alt="image" src="https://user-images.githubusercontent.com/3297715/215020108-2d589b31-0911-4515-8377-d26ff693e92a.png">

**Comment by tommydangerous** [comment]
We'll update the UI and documentation to reflect those changes. Thank you so much for suggesting!

**Comment by johnson-mage** [comment]
> One small suggestion is to update the variable tab with more instruction for SQL and R (or point to the documentation link) <img alt="image" width="599" src="https://user-images.githubusercontent.com/3297715/215020108-2d589b31-0911-4515-8377-d26ff693e92a.png">

Hi @ChengzhiZhao, just FYI the Variables tab has been updated with more details for SQL and R blocks per your suggestion. https://github.com/mage-ai/mage-ai/pull/2153
