### ISSUE TITLE
postgresql table_exists check fails for existing empty table

### ISSUE THREAD

**Issue by AkshayBade** [mage-ai/mage-ai#1905]
**Describe the bug**
`table_exists` definition relies on number of rows within table & if rows are zero (empty table) it assumes table does not exists and tries to create same table again resulting into `DuplicateTable` exception.
**Version:** mage-ai==0.7.86

**To Reproduce**
1. Create empty table in postgresql
2. Write Data Exporter step with ExportWritePolicy as append or replace.
3. Try to export some data to this
4. Excepts into `psycopg2.errors.DuplicateTable: relation "empty_table_name" already exists`

**Expected behavior**
Exporting to empty postgresql table with ExportWritePolicy as append or replace is valid use case and `table_exists` method should return true.

**Comment by tommydangerous** [comment]
👀

**Comment by tommydangerous** [comment]
What version of Mage are you on? And are you using it from Docker or pip?

**Comment by tommydangerous** [comment]
1. Empty table in PostgreSQL
<img width="632" alt="image" src="https://user-images.githubusercontent.com/1066980/216024574-cbf3f23a-1dc7-4c7e-9144-559123478869.png">

2. Data exporter:
```python
from mage_ai.data_preparation.repo_manager import get_repo_path
from mage_ai.io.config import ConfigFileLoader
from mage_ai.io.postgres import Postgres
from pandas import DataFrame
from os import path

if 'data_exporter' not in globals():
    from mage_ai.data_preparation.decorators import data_exporter


@data_exporter
def export_data_to_postgres(df: DataFrame, **kwargs) -> None:
    """
    Template for exporting data to a PostgreSQL database.
    Specify your configuration settings in 'io_config.yaml'.

    Docs: https://docs.mage.ai/design/data-loading
    """
    schema_name = 'mage3'  # Specify the name of the schema to export data to
    table_name = 'test_table_name'  # Specify the name of the table to export data to
    config_path = path.join(get_repo_path(), 'io_config.yaml')
    config_profile = 'local'
    
    import pandas as pd

    df = pd.DataFrame([{'id': 1}])

    with Postgres.with_config(ConfigFileLoader(config_path, config_profile)) as loader:
        loader.export(
            df,
            schema_name,
            table_name,
            index=False,  # Specifies whether to include index in exported table
            if_exists='append',  # Specify resolution policy if table name already exists
        )
```

3. Run export
<img width="1035" alt="image" src="https://user-images.githubusercontent.com/1066980/216024716-64bed90b-e605-4e1b-bcb4-d7255000b5ca.png">

4. No error. Here is my table:
<img width="718" alt="image" src="https://user-images.githubusercontent.com/1066980/216024776-9060ba29-e112-42ff-9a4f-385433abd4af.png">

**Comment by tommydangerous** [comment]
Can we hop on a quick video chat so I can see your screen and help you debug this in realtime?

If possible, can you join our Slack and DM me: https://www.mage.ai/chat

**Comment by tommydangerous** [comment]
Hey @AkshayBade!

Did you ever get this solved? I’d love to help you with this!

**Comment by thomaschung408** [comment]
Hi @AkshayBade I wanted to check in to see if this was resolved. Please let us know if you need anything else. Thank you!

**Comment by AGarrow** [comment]
I ran into this issue in version `0.8.22` and it seems to be fixed in `0.8.27`

**Comment by thomaschung408** [comment]
Thanks for your input @AGarrow! Glad it's fixed with the recent release. I'll go ahead and close this issue. Please don't hesitate to reach out if you experience any other issues. Thank you!

**Comment by M0M0K** [comment]
Hi! I'm having this issue in version 0.9.70, and I don't know how to fix it. I installed mage with the Docker Compose Template. I want to update the version to 0.9.71 but I'm affraid to lose my project (I'v already written 40 block and I'm in a Oracle Linux VM). Any help ?

**Comment by M0M0K** [comment]
I'm having the same issue in version 0.9.71.
