### ISSUE TITLE
Couchbase as source

### ISSUE THREAD

**Issue by haithem-souala** [mage-ai/mage-ai#1906]
**Is your feature request related to a problem? Please describe.**
Ability to sync. data from Couchbase (https://www.couchbase.com)

**Describe the solution you'd like**
Sync. data from Couchbase to BigQuery

**Comment by tommydangerous** [comment]
Hey @haithem-souala! We support BigQuery as a destination already. We’ll add support for Couchbase in next week’s release: https://airtable.com/shrJctaGt4tvU27uF/tbl5bIlFkk2KhCpL4

<img width="1163" alt="image" src="https://user-images.githubusercontent.com/1066980/216149737-07e84041-2aef-4eb4-b96a-035fe68e5058.png">

Please join our community Slack (https://www.mage.ai/chat) so I can update you in real time on the progress.

**Comment by dy46** [comment]
hey @haithem-souala, we added couchbase as a source in the most recent version of Mage. here's the couchbase documentation: https://github.com/mage-ai/mage-ai/blob/master/mage_integrations/mage_integrations/sources/couchbase/README.md. please let us know if you run into any issues

**Comment by haithem-souala** [comment]
Hey @dy46 
Ill check it this week, and ill let you know the result.
Thank you!!!
