### ISSUE TITLE
keyerror on using dynamic blocks.

### ISSUE THREAD

**Issue by dichouhan** [mage-ai/mage-ai#1943]
I'm using mageai:latest build on docker.

here is the structure of my pipeline.

![Screenshot from 2023-02-06 19-30-24](https://user-images.githubusercontent.com/121872816/216991049-9bf3bd84-b692-48ea-8968-82042ff0bac9.png)

output of root_data_import is in this format.
[[{user_details: [1,2,3,4,5]}, {user_details: [6,7,8,9]}],[{block_uuid: 1_5 }, {block_uuid: 6_9]]

it works well on testing the pipeline, but when I execute the entire pipeline, fetch_data block throws weird error.

[stacktrace log](https://github.com/mage-ai/mage-ai/files/10663827/stacktrace.log).

I've gone through dynamic blocks, documentation, but can't find much on this matter.

**Comment by thomaschung408** [comment]
Hi @dichouhan, so sorry that you have experienced this error. Thank you for reporting it this. We'll take a look and reach back out to you soon.

**Comment by tommydangerous** [comment]
Hello @dichouhan, so sorry for the inconvenience and the error.

Thanks so much for sharing the stack trace. We'll try to reproduce on our end and report back with a fix.

Can you please share your transformer block code?

Also, for real-time help, you can always join our Slack (https://www.mage.ai/chat).

**Comment by tommydangerous** [comment]
@dichouhan the fix is live, please pull the latest Docker image: https://docs.mage.ai/getting-started/setup#download-new-version-of-mage
