### ISSUE TITLE
Problems with MySQL source

### ISSUE THREAD

**Issue by agroideas** [mage-ai/mage-ai#2164]
Hi, I'm trying to setup an integration pipeline connecting to MySQL 8 database, **Test connection** goes fine, **View and select streams** gives this error:

`{"caller": "MySQL", "level": "EXCEPTION", "message": "MySQL process failed with error a bytes-like object is required, not 'str'.", 
`

I've tried two different MySQL 8 instances I have.

It works fine connecting to MySQL 5.7

Additional info: In both MySQL 8.0 servers the ports are not standard (i.e. 33006). With MySQL 5.7 I have port 3306.

**To Reproduce**

*Setup a connection to MySQL 8 server filling:*
database: 
host: 
port: (view note above)
username: 
password: 

*I  kept these fields as default:*
connection_method: direct
ssh_host: null
ssh_port: 22
ssh_username: null
ssh_password: null
ssh_pkey: null

**Comment by tommydangerous** [comment]
We'll look into this, sorry for the issue.

**Comment by wangxiaoyou1993** [comment]
Hi @agroideas , the issue has been fixed in latest Mage version (version 0.8.23). Let us know if you still have this issue.

**Comment by agroideas** [comment]
It worked like a charm, thank you very much for the quick fix!
