### ISSUE TITLE
Could not start mage-ai after installation with Windows OS

### ISSUE THREAD

**Issue by sphinks** [mage-ai/mage-ai#2245]
**Describe the bug**
After installation of mage-ai  at Windows Server 2016 I could not start it. I use both pip and conda install and get the error
```
Anaconda3\Scripts\mage-script.py", line 5, in <module>
    from mage_ai.cli.main import main
ImportError: cannot import name 'main' from 'mage_ai.cli.main'
```

**To Reproduce**
1. Start powershell with conda environment
2. Run `pip install mage-ai`
3. Run ` mage start demo`

The same result if I run `conda install -c conda-forge mage-ai`

**Expected behavior**
Mage-ai starts according to install tutorial

**Desktop (please complete the following information):**
 - OS: Windows Server 2016
 - Anaconda: 1.11.0
 - Conda: 23.1.0
 - Python 3.9.13

**Comment by wangxiaoyou1993** [comment]
Thanks for reporting the issue! We'll look into it.

**Comment by tommydangerous** [comment]
Thank you for reporting @sphinks, we’ll fix this ASAP and report back.

**Comment by wangxiaoyou1993** [comment]
This issue is fixed in latest version.
