### ISSUE TITLE
Add pre-commit to the project to prevent failures in lint test

### ISSUE THREAD

**Issue by bruno-uy** [mage-ai/mage-ai#2256]
**Is your feature request related to a problem? Please describe.**
As a mage contributor, I would like a more straightforward way to check my commits against the "standard". Simple things like `flake8`, but other things like "we use single quotes for stings". When I created my first PR the `Build and test / Lint (pull_request)` test failed because I had spaces in an empty line. It was an easy fix, but I had to take time to correct it when having something checking for that before pushing would be better.

**Describe the solution you'd like**
I would recommend adding [pre-commit](https://pre-commit.com/) and setting the rules we're currently trying to follow.

**Describe alternatives you've considered**
You can configure that on your own IDE, but it's not "mandatory". You see the failures when the commit is already pushed.

**Comment by tommydangerous** [comment]
Great idea!

**Comment by tommydangerous** [comment]
We'll work on this.

**Comment by bruno-uy** [comment]
I can help if needed 😄

**Comment by tommydangerous** [comment]
That would be amazing if you could help 🙏🙏🙏

**Comment by bruno-uy** [comment]
If you give me the guidelines or where to look, I can start working on that if you don't have another thing for me.

**Comment by wangxiaoyou1993** [comment]
There's an open PR from [chethanuk](https://github.com/chethanuk) to add the pre-commit: https://github.com/mage-ai/mage-ai/pull/2355
Will review that PR today.

**Comment by bruno-uy** [comment]
Nice 🙌🏼
