### ISSUE TITLE
DuckDB Integration

### ISSUE THREAD

**Issue by kylelundstedt** [mage-ai/mage-ai#2273]
Really enjoying Mage; thanks team!

Your docs mention "Scaling is made simple" as a core principle.  If that's so, I'd highly recommend that you look at [DuckDB](https://github.com/duckdb/duckdb).  Unlike Spark, Dask, Ray, etc., DuckDB is an in-process analytical database system that is super fast and really easy to use, and has attracted a ton of interest (no personal affiliation; just a big fan).

I know your project is just getting started, but I think a DuckDb integration would help kick things into high gear.  It could be both a source and a destination, and DuckDB has really strong APIs including Python, R, and a SQL CLI.  Best of luck with the project!

**Comment by tommydangerous** [comment]
Great idea! Thank you so much for sharing. We'll add this to our roadmap.

Fun fact: the founders of MotherDuck are investors in Mage.

**Comment by datamike** [comment]
And those quacks at DuckDb have put in features like querying JSON, CSV, Parquet files, e.g. - Without having to load the the files into database tables (similar to querying Staged Data files in Snowflake)!!!

**Comment by tommydangerous** [comment]
Hey @datamike, thanks so much for the feedback and share. Would a Mage + DuckDB integration be useful to you as well?

**Comment by rupurt** [comment]
Hey @tommydangerous. I'd love a DuckDB integration also. I'm happy to work on it if you can point me in the right direction.

I've written an [ODBC extension for DuckDB](https://github.com/rupurt/odbc-scanner-duckdb-extension) and I'd love to orchestrate pipelines with mage for migrating legacy systems. As a side note it could also be used to expand the range of supported databases for mage itself.

**Comment by wangxiaoyou1993** [comment]
Update: DuckDB SQL block is supported in Mage now: https://docs.mage.ai/integrations/databases/DuckDB

**Comment by wangxiaoyou1993** [comment]
Wwe’ve finished integrations for these
* DuckDB IO class and SQL block
* Data loader/exporter templates for DuckDB
* dbt-duckdb
* Add DuckDB as a streaming pipeline destination
