### ISSUE TITLE
As a user, I want to be able to load any file format to S3 Bucket like images, Pdf's ,etc 

### ISSUE THREAD

**Issue by alexbonella** [mage-ai/mage-ai#2338]
**Is your feature request related to a problem? Please describe.**

Sure!, I have a Python function that read url_images of the internet in order to save them in .jpg format before loading to an S3 bucket automatically using Airflow, but I would love to export images or any other format with Mage. 

**Describe the solution you'd like**

I want to have the chance to load any file to S3

**Describe alternatives you've considered**

I think an easy way to do this is to use boto3 to upload any file format to S3 Bucket and not only depend on .csv, hdf5, and parquet.

**Additional context**

**Comment by wangxiaoyou1993** [comment]
Hey, are you able to use this code to upload the file to S3 bucket?
```
import boto3

client = boto3.client("s3")
client.upload_file("local_file_path", "s3_bucket", "s3_file_path")
```

**Comment by alexbonella** [comment]
Yes I did it, thanks for your hints @wangxiaoyou1993 only I needed to add secrets to client object 

client = boto3.client(
    's3',
    aws_access_key_id=get_secret_value('aws_key'),
    aws_secret_access_key=get_secret_value('secret_key') 
)
