### ISSUE TITLE
Change Mage default port on Docker

### ISSUE THREAD

**Issue by gui-elastic** [mage-ai/mage-ai#2362]
**Describe the bug**
When the default exposed port (6789) on Mage's container is changed to another port (e.g., 9876), the UI is not able to render correctly. I had another service running on port 6789, so I exposed a different port for the Mage container, but it did not work as expected.

**To Reproduce**
1. On your terminal (Mac or Linux), execute the following command:
```
docker run -it -p 9876:6789 -v $(pwd):/home/src mageai/mageai \
  /app/run_app.sh mage start demo_project
```
2. The container will start, but when accessing the Web UI on the `localhost:9876` endpoint, the following screen is displayed:
<img width="1788" alt="Screenshot 2023-04-08 at 22 50 29" src="https://user-images.githubusercontent.com/95642525/230750135-47dbda17-040c-4d7c-b8a4-05867014f54d.png">

**Expected behavior**
It would see the home page of the Mage UI rendered correctly, as in the example below:
<img width="1792" alt="Screenshot 2023-04-08 at 22 52 29" src="https://user-images.githubusercontent.com/95642525/230750175-70aa9e02-3264-42fb-90e6-e5c4704cf20a.png">

**Desktop (please complete the following information):**
 - OS: MacOS
 - Browser: Safari
 - Version: Version 16.4 (18615.1.26.11.22)

**Additional context**
The workaround was to instead of using `localhost:9876` on the URL, use the IP/Hostname of my laptop.

**Comment by tommydangerous** [comment]
Try this:

```
docker run -it -p 9876:6789 -v $(pwd):/home/src mageai/mageai \
  /app/run_app.sh mage start demo_project --port 9876
```

**Comment by gui-elastic** [comment]
Unfortunately executing the command you sent me and also this one:
```
docker run -it -p 9876:9876 -v $(pwd):/home/src mageai/mageai \
  /app/run_app.sh mage start demo_project --port 9876
```

did not work. I am still not able to access the Mage service using the `http://localhost:9876` URL. 

I just would like to explain that I am able to access the Mage URL using my IP/Hostname (e.g., `http://192.168.0.1:9876`), but not with `localhost` as it is described on the Mage documentation. So this Issue was opened to understand if this is the expected behavior. If it is, I think you should add this to the documentation, so other people who need to run Mage in a different port will not experience the same issue. But it also can be something I am doing wrong from my side, so I would like to confirm with you if that is the case.

I really appreciate your assistance. Thank you.

**Comment by johnson-mage** [comment]
@gui-elastic Thanks for bringing this to our attention! Just wanted to confirm that the Mage UI was rendering fine for you, just not on `localhost:9876` specifically, correct? 

We updated the docs to clarify that if the port is changed, user will need to go to `http://127.0.0.1:[port]` instead of using `localhost`. You had mentioned being able to access the Mage UI at `http://192.168.0.1:9876`, but are you also able to access it at http://127.0.0.1:9876?

**Comment by johnson-mage** [comment]
@gui-elastic Going to close this issue since a different port is able to be used, just not using `localhost` in the url. We've updated the docs [here](https://docs.mage.ai/introduction/overview#install-using-docker). Feel free to reopen this issue if something was not addressed. Thanks!
