### ISSUE TITLE
pip and conda installations not running on Windows OS

### ISSUE THREAD

**Issue by ZhenoSan** [mage-ai/mage-ai#2370]
**Describe the bug**
mage start does not work after installing from pip or conda. Tried installing on clean 

**Screenshots**
pip:
![image](https://user-images.githubusercontent.com/48855019/230906798-13936073-5a1b-4037-aa70-1dbd2d576ef0.png)

Conda:
![image](https://user-images.githubusercontent.com/48855019/230906768-693e7c24-65b5-4bd0-9cb4-ac7b23395184.png)

- OS Windows 11
- conda 23.3.1
- Python 3.10.8
- mage-ai 0.8.41

**Comment by thomaschung408** [comment]
Hi @ZhenoSan! So sorry you're experience these issues. We'll look into it and have someone from the team reach out shortly. Thank you for patience.

**Comment by dy46** [comment]
hi @ZhenoSan for the first issue, do you have git installed? can you include the command you're trying to run, and the entire output from that command?

**Comment by ZhenoSan** [comment]
Hey @dy46 , no i don't have git installed.

The first command that i ran was `conda install -c conda-forge mage-ai`

The second command i ran was `mage start demo_project`

That's when i got that git error.

**Comment by ZhenoSan** [comment]
@dy46  This is the conda error:
[Anaconda Prompt (miniconda3).txt](https://github.com/mage-ai/mage-ai/files/11193059/Anaconda.Prompt.miniconda3.txt)

**Comment by ZhenoSan** [comment]
The pip issue was resolved by typing `set GIT_PYTHON_REFRESH=quiet` into the cmd and then running `mage start`

**Comment by dy46** [comment]
@ZhenoSan great! does that mean it work for you through pip now?

**Comment by ZhenoSan** [comment]
@dy46 yes but i have to type set GIT_PYTHON_REFRESH=quiet every time before starting mage.

**Comment by dy46** [comment]
we'll still look into the issue, but glad it works for you now
