### ISSUE TITLE
Allow for more complex Streaming pipelines

### ISSUE THREAD

**Issue by rezo1134** [mage-ai/mage-ai#2371]
Hey!,

I'm evaluating mage-ai as an airflow replacement, and was messing around with the streaming pipelines, and was thinking that it would be really nice to:
1. Support mutliple transforms in a single pipeline. At the moment if you have more than 1 transform it spits out an error saying to limit it to 1 transform block. This would help add sanity to potentially complex workflows and remove the need for a potentially huge wall of code.

2. Support chaining together exporters and data loader blocks. At the moment if you were to have a single pipeline and try to create another dataloader that depends on the data from a previous exporter, it errors saying data loaders can't have downstream dependencies. While I COULD always just make another pipeline, it would add breakages in certain workflows where Kafka is being used as an intermediary microservice. Ideally this kind of workflow could be supported in a single pipeline:

```
    Dataloader1(kafkatopic1) -> transformer1 -> Dataexporter1(kafkatopic2) -> Dataloader2(kafkatopic2) -> transformer2 -> Dataexporter3(kafkatopic3)
```

3. Restructuring of components in the UI. The code cells in the pipeline editor are static and stay in the order you create them. If more complex pipelines are allowed, being able to reorder the cells to match the dag view on the right would be a great QoL improvement, and really play to that "notebook" style setup by implementing a logical ordering to match the pipeline

**Comment by tommydangerous** [comment]
We’re adding this to our roadmap! When do you need it by @rezo1134?

**Comment by rezo1134** [comment]
No hard deadlines or anything, I just think it would greatly improve QoL especially for the streaming pipelines.

**Comment by tommydangerous** [comment]
@rezo1134 we’ll work on this very soon. It’s on the roadmap for May: https://airtable.com/shrJctaGt4tvU27uF/tbl5bIlFkk2KhCpL4/viwuG2UltYNwgKTVC/reciflF61heMIgEJd

**Comment by wangxiaoyou1993** [comment]
Hi @rezo1134 , the complex streaming pipeline structure is supported in Mage now: https://docs.mage.ai/guides/streaming/overview

**Comment by wangxiaoyou1993** [comment]
@rezo1134 Reordering the cells is also supported in the notebook by drag and drop.
I'm going to close this ticket now. Let us know if you have problems using the streaming pipelne.
