### ISSUE TITLE
Typo on docs

### ISSUE THREAD

**Issue by ZhenoSan** [mage-ai/mage-ai#2398]
Path: /development/text-editor

Under Development, same heading for two titles

![image](https://user-images.githubusercontent.com/48855019/231738974-e6193636-6f0c-4cae-9d3b-b4d98b38311c.png)

**Comment by wangxiaoyou1993** [comment]
Thanks for pointing out the doc issue. Will fix it.

**Comment by wangxiaoyou1993** [comment]
Just fixed the doc: 
<img width="285" alt="image" src="https://user-images.githubusercontent.com/80284865/231837224-88d08c5a-a8e8-4a48-aebd-7a12a2c7fff9.png">
