### ISSUE TITLE
User Authentication Issue

### ISSUE THREAD

**Issue by ZhenoSan** [mage-ai/mage-ai#2399]
I tried enabling user authentication on a project with REQUIRE_USER_AUTHENTICATION = 1

When I try to sign in with the default owner, i get this error:
![Untitled](https://user-images.githubusercontent.com/48855019/231757576-ed5e069d-8fdb-40e6-99e5-9ec4a30f68ad.png)

Tried to disable user authentication with REQUIRE_USER_AUTHENTICATION = 0 but it's no use. Can't access my project anymore.

EDIT:

I was able to get authentication working by installing the ldap3 python package. How do i disable it now?

**Comment by wangxiaoyou1993** [comment]
Which Mage version are you using?

**Comment by ZhenoSan** [comment]
I'm running 0.8.44 in Python 3.10.9 on Windows 11 OS. Installed with pip.

By the way, I tried toggling REQUIRE_USER_AUTHENTICATION and now i've lost my pipelines and i get these errors when the program starts. Don't even get the sign-in mage even though flag is set to 1.

[Anaconda Prompt (miniconda3) - mage  start test.txt](https://github.com/mage-ai/mage-ai/files/11225153/Anaconda.Prompt.miniconda3.-.mage.start.test.txt)

**Comment by wangxiaoyou1993** [comment]
Could you click "Sign out" at the top right corner? And then sign in again.
<img width="156" alt="image" src="https://user-images.githubusercontent.com/80284865/231846064-b25dc769-8391-4a36-a8e6-fc34c4bb890e.png">

**Comment by ZhenoSan** [comment]
Thanks, that worked :)
Now I just need to know how to switch user authentication off.

**Comment by wangxiaoyou1993** [comment]
> Thanks, that worked :) Now I just need to know how to switch user authentication off.

Could you try deleting the `REQUIRE_USER_AUTHENTICATION` environment variable?

**Comment by ZhenoSan** [comment]
That worked too! Thanks a bunch.

I thought I already tried doing that before. 

I just assumed setting REQUIRE_USER_AUTHENTICATION  to 0 would disable it.

**Comment by thomaschung408** [comment]
Glad it worked @ZhenoSan!!! I'll go ahead and close this issue. Please don't hesitate to reach out if you experience any other issues. Thank you!
