### ISSUE TITLE
[Docs] Broken streaming pipeline example

### ISSUE THREAD

**Issue by jlondonobo** [mage-ai/mage-ai#2418]
**Describe the bug**
When I try to run the example under the section **Using Kafka locally in a Docker container** it throws out the following error:
```
docker: invalid reference format.
See 'docker run --help'.
```

**To Reproduce**
1. Go to https://docs.mage.ai/guides/streaming-pipeline
2. Run the example under **Using Kafka locally in a Docker container** on your machine.

**What I believe to be the problem**
This is the example:
```bash
docker run -it -p 6789:6789 -v $(pwd):/home/src \
  --env AWS_ACCESS_KEY_ID=your_access_key_id \
  --env AWS_SECRET_ACCESS_KEY=your_secret_access_key \
  --env AWS_REGION=your_region \
  --network kafka-docker_default \
  /app/run_app.sh mageai/mageai mage start default_repo
```

I believe that on the last line, `/app/run_app.sh` should go after the image `mageai/mageai`. This is how I got it working:
```bash
docker run -it -p 6789:6789 -v $(pwd):/home/src \
  --env AWS_ACCESS_KEY_ID=your_access_key_id \
  --env AWS_SECRET_ACCESS_KEY=your_secret_access_key \
  --env AWS_REGION=your_region \
  --network kafka-docker_default \
  mageai/mageai /app/run_app.sh mage start start default_repo
```

**Expected behavior**
The example should start MageAI on a Docker container.

**Desktop (please complete the following information):**
 - OS: MacOS
 - Browser: Chrome

**Comment by jlondonobo** [comment]
This typo was introduced in https://github.com/mage-ai/mage-ai/commit/f16618dde68b0de07a470bbd4918bb969e2b9b07 as part of a multi-script update.

From looking at the commit, the documentation for **Airflow Integration** might also have this problem:
- https://github.com/mage-ai/mage-ai/blob/8445494e5b85413c74331f921a63be2d41b66ed3/docs/guides/integrate-mage-airflow.mdx?plain=1#L59
- https://github.com/mage-ai/mage-ai/blob/8445494e5b85413c74331f921a63be2d41b66ed3/docs/guides/integrate-mage-airflow.mdx?plain=1#L118

**Comment by tommydangerous** [comment]
Thank you so much for catching this, we'll update the docs to fix.

**Comment by tommydangerous** [comment]
Fixed!
