### ISSUE TITLE
google ads integrations support google cloud storage as destination

### ISSUE THREAD

**Issue by jerryan999** [mage-ai/mage-ai#2489]
<img width="778" alt="image" src="https://user-images.githubusercontent.com/17285408/233818084-e1dfed50-7031-42e5-8089-e5b7a942d29d.png">
It seems the google ads integrations does't support google cloud storage as destination.

**Comment by wangxiaoyou1993** [comment]
Hey @jerryan999 , we'll add "google cloud storage destination" to our roadmap. When do you need this feature by?

**Comment by jerryan999** [comment]
maybe in the next 2 weeks

**Comment by wangxiaoyou1993** [comment]
Got it. We'll add "google cloud storage destination" next week.

**Comment by andreventura02** [comment]
I will contribute to this issue

**Comment by andreventura02** [comment]
Hey! Enhancement finished. Waiting  Pull Request approve. @wangxiaoyou1993

**Comment by wangxiaoyou1993** [comment]
Thank you @andreventura02 !

Hi @jerryan999 , the Google Cloud Storage destination has been added. You can upgrade to version 0.8.68 or above to use it.
