### ISSUE TITLE
google ads integration support statement to populate start_date field

### ISSUE THREAD

**Issue by jerryan999** [mage-ai/mage-ai#2490]
<img width="407" alt="image" src="https://user-images.githubusercontent.com/17285408/233818380-4d09b537-6fe1-4631-a3cf-d35a62ec2112.png">

I would be great to support this feature: statement like {{today_date-days(7)}} to populate the start_date field. We always don't want to query starting from the fixed start_date because it will be inconvenient for daily tasks.

**Comment by wangxiaoyou1993** [comment]
Hey @jerryan999 , this is actually supported. you can try using `"{{ n_days_ago(7) }}"` to populate the start_date.

**Comment by jerryan999** [comment]
@wangxiaoyou1993  thanks!
