### ISSUE TITLE
Mage ai is not recognised as internal or external command

### ISSUE THREAD

**Issue by HarshkumarDegamadiya** [mage-ai/mage-ai#2492]
I install mage-ai with pip and after that i tried to run it in cmd as well as conda cmd but it is showing this error

**Comment by tommydangerous** [comment]
What command are you trying to run?

mage start ?

**Comment by Snorlax51** [comment]
Same issue , i am also getting issue in Mage start

**Comment by wangxiaoyou1993** [comment]
Hi @HarshkumarDegamadiya and @Snorlax51 , what errors did you get?

**Comment by Snorlax51** [comment]
@wangxiaoyou1993  i got error that mage is not recognised

**Comment by wangxiaoyou1993** [comment]
@Snorlax51 did you use pip or conda to install Mage?

**Comment by Snorlax51** [comment]
@wangxiaoyou1993  i used pip , and then using mage start demo to run the program

**Comment by prikshit-2000** [comment]
@HarshkumarDegamadiya which python version and OS you are using??

**Comment by devilsaint99** [comment]
@HarshkumarDegamadiya 
> I install mage-ai with pip and after that i tried to run it in cmd as well as conda cmd but it is showing this error

Can you please share the screenshot of what command you are using, a screenshot gives better view of the issue to the audience

**Comment by Weddou1** [comment]
Hey ! 

To fix this, you need to adjust your environment variables (assuming you're on Windows), or alternatively you can do this :

`pip show mage-ai 
`

This will take you to your Python directory and take you to the Scripts folder, where there's normally a mage.exe file that will let you run Mage commands by using the file path as follows: 

`../Python39/Scripts/mage.exe start demo-Project`

**Comment by Weddou1** [comment]
Also you probably didn't made a virtual environment for installing mage (which is not very recommended :x)

**Comment by wangxiaoyou1993** [comment]
Close this issue since no recent reports.
