### ISSUE TITLE
Logging to AWS Cloudwatch

### ISSUE THREAD

**Issue by dumim** [mage-ai/mage-ai#2528]
**Is your feature request related to a problem? Please describe.**
There is no in-built way to stream the logs to AWS CloudWatch.

**Describe the solution you'd like**
Since Cloudwatch is the main logging system and the log analyzer used by all AWS Services, having it as a direct logging destination would be ideal

**Describe alternatives you've considered**
The other way I can think of implementing this would be to use the Cloudwatch Logs agent to point to read from the logging folder within the EC2. Or use the AWS CLI, CloudWatch Logs SDK, or the CloudWatch Logs API to push directly from within the code or simplify with an app such as Watchtower

**Additional context**
Deployment is managed through Terraform with AWS provider

**Comment by thomaschung408** [comment]
Hi @dumim! Great feature request! How urgent is this for you and when would you need this by?

**Comment by wangxiaoyou1993** [comment]
Hey @dumim , all the logs from the ECS containers should be sent to CloudWatch by default.
The log group is this: https://github.com/mage-ai/mage-ai-terraform-templates/blob/master/aws/main.tf#L31
Could you check whether you can find your logs there?

**Comment by wangxiaoyou1993** [comment]
Hey @dumim , are you able to find the cloudwatch logs from the log group I mentioned above?

**Comment by wangxiaoyou1993** [comment]
@dumim I'm going to close ticket. Feel free to reopen the ticket if you still have issues with the logs.

**Comment by dumim** [comment]
@wangxiaoyou1993 Thank you! I glossed over this part, that will work for us at the moment. We are still in the process of setting up Mage, will report back once deployed.
