### ISSUE TITLE
HTML UI issue when extending code window

### ISSUE THREAD

**Issue by prikshit-2000** [mage-ai/mage-ai#2601]
**Describe the bug**
If I increase the file view size by moving it to the right side  to have a better view for coding and I click on tree,charts,terminal etc I am not able to see them as they have moved to the right of the screen and also if I try to reduce the size by moving the coding screen I am not able to do so as the panel containing tree,chart,terminal options pops up and covers that region.

**To Reproduce**
1. Extend the code window to right
2. Tree will be hidden now
3. click on either option tree,terminal or chart
4. It gets hidden behind and you are not able to reduce the code window size as popup containing the options terminal,tree is extending there

**Expected behavior**
When we click on either option we should be able to view that

**Screenshots**
![image](https://user-images.githubusercontent.com/46683777/236603082-d3bf88df-9497-4d45-bf1c-912eec118381.png)

**Desktop (please complete the following information):**
 - OS: Windows 11
 - Browser: Mozilla Firefox
 - Version: 112.0.2

**Comment by johnson-mage** [comment]
@prikshit-2000 Thanks for bringing this to our attention, we'll fix this as soon as we get the chance.

**Comment by johnson-mage** [comment]
@prikshit-2000 We will add a fix for this soon (this week), but in the meantime if youre Sidekick is hidden, you can open up your browser's local storage and look for the `pipeline_editor_after_width` key. Increase that amount (e.g. to 400) and then refresh your page. The Sidekick should be wide enough so that you can resize it again.

**Comment by prikshit-2000** [comment]
@johnson-mage  thanks for the solution

**Comment by johnson-mage** [comment]
@prikshit-2000 We just built a new version last night (v0.8.76) that should prevent this issue from happening again. There are minimum widths on the side panels now. If you want to hide them, you can click the `>` or `<` arrows that will hide the left or right panel. Marking this issue as completed.
