### ISSUE TITLE
mage local desktop installation - mage terminating unexpectedly.

### ISSUE THREAD

**Issue by ravindra-kumar25** [mage-ai/mage-ai#2648]
**Describe the bug**
I installed the mage.ai on my MacBook pro, and when creating a simple pipeline, after every few minutes, the instance is terminating.

**To Reproduce**
Please see the log below
INFO:mage_ai.server.active_kernel:Switch active kernel: python3
INFO:mage_ai.server.active_kernel:Kernel python3 is already alive.
INFO:mage_ai.api.logging:[2023-05-16T22:31:51.010256][api.views] Action: detail pipelines mage_demo_from_local  
INFO:mage_ai.api.logging:[2023-05-16T22:31:51.010418][api.views] Latency: 0.0253 seconds
INFO:tornado.access:200 GET /api/pipelines/mage_demo_from_local?includes_outputs=false&api_key=zkWlN0PkIKSN0C11CfUHUj84OT5XOJ6tDZ6bDRO2 (::1) 28.00ms
INFO:mage_ai.server.scheduler_manager:Scheduler status: running.
INFO:mage_ai.api.logging:[2023-05-16T22:32:06.256411][api.views] Action: list variables mage_demo_from_local pipelines mage_demo_from_local
INFO:mage_ai.api.logging:[2023-05-16T22:32:06.261399][api.views] Latency: 6.2981 seconds
INFO:tornado.access:200 GET /api/pipelines/mage_demo_from_local/variables?api_key=zkWlN0PkIKSN0C11CfUHUj84OT5XOJ6tDZ6bDRO2 (::1) 12718.11ms
INFO:mage_ai.server.scheduler_manager:Scheduler status: running.
INFO:mage_ai.api.logging:[2023-05-16T22:32:12.764378][api.views] Action: list kernels None  
INFO:mage_ai.api.logging:[2023-05-16T22:32:12.764503][api.views] Latency: 0.0403 seconds
INFO:tornado.access:200 GET /api/kernels?api_key=zkWlN0PkIKSN0C11CfUHUj84OT5XOJ6tDZ6bDRO2 (::1) 41.85ms
WARNING:traitlets:Could not destroy zmq context for <jupyter_client.blocking.client.BlockingKernelClient object at 0x7fad8c100510>
INFO:mage_ai.api.logging:[2023-05-16T22:32:17.808836][api.views] Action: list kernels None  
INFO:mage_ai.api.logging:[2023-05-16T22:32:17.808913][api.views] Latency: 0.0232 seconds
INFO:tornado.access:200 GET /api/kernels?api_key=zkWlN0PkIKSN0C11CfUHUj84OT5XOJ6tDZ6bDRO2 (::1) 24.09ms
WARNING:traitlets:Could not destroy zmq context for <jupyter_client.blocking.client.BlockingKernelClient object at 0x7fad885b7c50>
INFO:mage_ai.server.active_kernel:Switch active kernel: python3
INFO:mage_ai.server.active_kernel:Kernel python3 is already alive.
INFO:mage_ai.server.active_kernel:Switch active kernel: python3
INFO:mage_ai.server.active_kernel:Kernel python3 is already alive.
INFO:mage_ai.api.logging:[2023-05-16T22:32:22.451373][api.views] Action: update pipelines mage_demo_from_local  
INFO:mage_ai.api.logging:[2023-05-16T22:32:22.451453][api.views] Latency: 0.3440 seconds
INFO:tornado.access:200 PUT /api/pipelines/mage_demo_from_local?update_content=true&api_key=zkWlN0PkIKSN0C11CfUHUj84OT5XOJ6tDZ6bDRO2 (::1) 346.82ms
INFO:mage_ai.server.active_kernel:Switch active kernel: python3
INFO:mage_ai.server.active_kernel:Kernel python3 is already alive.
INFO:mage_ai.api.logging:[2023-05-16T22:32:22.485917][api.views] Action: detail pipelines mage_demo_from_local  
INFO:mage_ai.api.logging:[2023-05-16T22:32:22.486034][api.views] Latency: 0.0205 seconds
INFO:tornado.access:200 GET /api/pipelines/mage_demo_from_local?includes_outputs=false&api_key=zkWlN0PkIKSN0C11CfUHUj84OT5XOJ6tDZ6bDRO2 (::1) 21.64ms
INFO:mage_ai.server.scheduler_manager:Scheduler status: running.
INFO:mage_ai.api.logging:[2023-05-16T22:32:42.868911][api.views] Action: list statuses None  
INFO:mage_ai.api.logging:[2023-05-16T22:32:42.869308][api.views] Latency: 0.0473 seconds
INFO:tornado.access:304 GET /api/statuses?api_key=zkWlN0PkIKSN0C11CfUHUj84OT5XOJ6tDZ6bDRO2 (::1) 55.01ms
INFO:mage_ai.api.logging:[2023-05-16T22:32:42.888160][api.views] Action: list files None  
INFO:mage_ai.api.logging:[2023-05-16T22:32:42.888317][api.views] Latency: 0.0047 seconds
INFO:tornado.access:304 GET /api/files?api_key=zkWlN0PkIKSN0C11CfUHUj84OT5XOJ6tDZ6bDRO2 (::1) 8.63ms
INFO:mage_ai.server.active_kernel:Switch active kernel: python3
INFO:mage_ai.server.active_kernel:Kernel python3 is already alive.
INFO:mage_ai.api.logging:[2023-05-16T22:32:42.927803][api.views] Action: detail pipelines mage_demo_from_local  
INFO:mage_ai.api.logging:[2023-05-16T22:32:42.928231][api.views] Latency: 0.0450 seconds
INFO:tornado.access:304 GET /api/pipelines/mage_demo_from_local?includes_outputs=false&api_key=zkWlN0PkIKSN0C11CfUHUj84OT5XOJ6tDZ6bDRO2 (::1) 48.91ms
WARNING:traitlets:Could not destroy zmq context for <jupyter_client.blocking.client.BlockingKernelClient object at 0x7fad8c12a190>
INFO:mage_ai.api.logging:[2023-05-16T22:32:42.939717][api.views] Action: list kernels None  
INFO:mage_ai.api.logging:[2023-05-16T22:32:42.939806][api.views] Latency: 0.0586 seconds
INFO:tornado.access:200 GET /api/kernels?api_key=zkWlN0PkIKSN0C11CfUHUj84OT5XOJ6tDZ6bDRO2 (::1) 60.69ms
WARNING:traitlets:Could not destroy zmq context for <jupyter_client.blocking.client.BlockingKernelClient object at 0x7fad88450c10>
INFO:mage_ai.api.logging:[2023-05-16T22:32:50.819583][api.views] Action: list kernels None  
INFO:mage_ai.api.logging:[2023-05-16T22:32:50.819679][api.views] Latency: 0.0271 seconds
INFO:tornado.access:200 GET /api/kernels?api_key=zkWlN0PkIKSN0C11CfUHUj84OT5XOJ6tDZ6bDRO2 (::1) 27.92ms
INFO:mage_ai.server.scheduler_manager:Scheduler status: running.
INFO:mage_ai.server.active_kernel:Switch active kernel: python3
INFO:mage_ai.server.active_kernel:Kernel python3 is already alive.
INFO:mage_ai.server.active_kernel:Switch active kernel: python3
INFO:mage_ai.server.active_kernel:Kernel python3 is already alive.
INFO:mage_ai.api.logging:[2023-05-16T22:32:56.503147][api.views] Action: update pipelines mage_demo_from_local  
INFO:mage_ai.api.logging:[2023-05-16T22:32:56.503252][api.views] Latency: 0.1069 seconds
INFO:tornado.access:200 PUT /api/pipelines/mage_demo_from_local?update_content=true&api_key=zkWlN0PkIKSN0C11CfUHUj84OT5XOJ6tDZ6bDRO2 (::1) 111.61ms
INFO:mage_ai.server.active_kernel:Switch active kernel: python3
INFO:mage_ai.api.logging:[2023-05-16T22:32:56.585755][api.views] Action: list kernels None  
INFO:mage_ai.api.logging:[2023-05-16T22:32:56.585874][api.views] Latency: 0.0040 seconds
INFO:tornado.access:200 GET /api/kernels?api_key=zkWlN0PkIKSN0C11CfUHUj84OT5XOJ6tDZ6bDRO2 (::1) 11.01ms
INFO:mage_ai.server.active_kernel:Kernel python3 is already alive.
INFO:mage_ai.api.logging:[2023-05-16T22:32:56.592284][api.views] Action: detail pipelines mage_demo_from_local  
INFO:mage_ai.api.logging:[2023-05-16T22:32:56.592468][api.views] Latency: 0.0248 seconds
INFO:tornado.access:200 GET /api/pipelines/mage_demo_from_local?includes_outputs=false&api_key=zkWlN0PkIKSN0C11CfUHUj84OT5XOJ6tDZ6bDRO2 (::1) 26.43ms
INFO:mage_ai.api.logging:[2023-05-16T22:33:01.845536][api.views] Action: list kernels None  
INFO:mage_ai.api.logging:[2023-05-16T22:33:01.845728][api.views] Latency: 0.0033 seconds
INFO:tornado.access:304 GET /api/kernels?api_key=zkWlN0PkIKSN0C11CfUHUj84OT5XOJ6tDZ6bDRO2 (::1) 4.69ms
INFO:mage_ai.server.active_kernel:Switch active kernel: python3
INFO:mage_ai.server.active_kernel:Kernel python3 is already alive.
INFO:mage_ai.api.logging:[2023-05-16T22:33:05.829992][api.views] Action: detail pipelines mage_demo_from_local  
INFO:mage_ai.api.logging:[2023-05-16T22:33:05.830090][api.views] Latency: 0.0161 seconds
INFO:tornado.access:304 GET /api/pipelines/mage_demo_from_local?includes_outputs=false&api_key=zkWlN0PkIKSN0C11CfUHUj84OT5XOJ6tDZ6bDRO2 (::1) 17.03ms
INFO:mage_ai.api.logging:[2023-05-16T22:33:06.861640][api.views] Action: list kernels None  
INFO:mage_ai.api.logging:[2023-05-16T22:33:06.861749][api.views] Latency: 0.0031 seconds
INFO:tornado.access:304 GET /api/kernels?api_key=zkWlN0PkIKSN0C11CfUHUj84OT5XOJ6tDZ6bDRO2 (::1) 3.96ms
INFO:mage_ai.api.logging:[2023-05-16T22:33:10.167207][api.views] Action: list statuses None  
INFO:mage_ai.api.logging:[2023-05-16T22:33:10.167339][api.views] Latency: 0.0151 seconds
INFO:tornado.access:304 GET /api/statuses?api_key=zkWlN0PkIKSN0C11CfUHUj84OT5XOJ6tDZ6bDRO2 (::1) 16.45ms
INFO:mage_ai.api.logging:[2023-05-16T22:33:10.176741][api.views] Action: list kernels None  
INFO:mage_ai.api.logging:[2023-05-16T22:33:10.176851][api.views] Latency: 0.0050 seconds
INFO:tornado.access:304 GET /api/kernels?api_key=zkWlN0PkIKSN0C11CfUHUj84OT5XOJ6tDZ6bDRO2 (::1) 7.46ms
INFO:mage_ai.api.logging:[2023-05-16T22:33:10.180475][api.views] Action: list files None  
INFO:mage_ai.api.logging:[2023-05-16T22:33:10.180576][api.views] Latency: 0.0030 seconds
INFO:tornado.access:304 GET /api/files?api_key=zkWlN0PkIKSN0C11CfUHUj84OT5XOJ6tDZ6bDRO2 (::1) 6.69ms
INFO:mage_ai.server.active_kernel:Switch active kernel: python3
INFO:mage_ai.server.active_kernel:Kernel python3 is already alive.
INFO:mage_ai.api.logging:[2023-05-16T22:33:10.201190][api.views] Action: detail pipelines mage_demo_from_local  
INFO:mage_ai.api.logging:[2023-05-16T22:33:10.201317][api.views] Latency: 0.0275 seconds
INFO:tornado.access:304 GET /api/pipelines/mage_demo_from_local?includes_outputs=false&api_key=zkWlN0PkIKSN0C11CfUHUj84OT5XOJ6tDZ6bDRO2 (::1) 30.94ms
INFO:mage_ai.server.scheduler_manager:Scheduler status: running.
INFO:mage_ai.server.active_kernel:Switch active kernel: python3
INFO:mage_ai.server.active_kernel:Kernel python3 is already alive.
INFO:mage_ai.server.active_kernel:Switch active kernel: python3
INFO:mage_ai.server.active_kernel:Kernel python3 is already alive.
INFO:mage_ai.api.logging:[2023-05-16T22:33:15.868054][api.views] Action: update pipelines mage_demo_from_local  
INFO:mage_ai.api.logging:[2023-05-16T22:33:15.868152][api.views] Latency: 0.1120 seconds
INFO:tornado.access:200 PUT /api/pipelines/mage_demo_from_local?update_content=true&api_key=zkWlN0PkIKSN0C11CfUHUj84OT5XOJ6tDZ6bDRO2 (::1) 114.55ms
INFO:mage_ai.server.active_kernel:Switch active kernel: python3
INFO:mage_ai.server.active_kernel:Kernel python3 is already alive.
INFO:mage_ai.api.logging:[2023-05-16T22:33:17.033623][api.views] Action: detail pipelines mage_demo_from_local  
INFO:mage_ai.api.logging:[2023-05-16T22:33:17.033848][api.views] Latency: 0.0237 seconds
INFO:tornado.access:200 GET /api/pipelines/mage_demo_from_local?includes_outputs=false&api_key=zkWlN0PkIKSN0C11CfUHUj84OT5XOJ6tDZ6bDRO2 (::1) 24.94ms
INFO:tornado.access:304 GET /pipelines/mage_demo_from_local/edit?sideview=tree (::1) 0.76ms
INFO:terminado.websocket:Websocket closed
INFO:mage_ai.api.logging:[2023-05-16T22:33:18.736675][api.views] Action: list statuses None  
INFO:mage_ai.api.logging:[2023-05-16T22:33:18.737008][api.views] Latency: 0.0277 seconds
INFO:tornado.access:304 GET /api/statuses?api_key=zkWlN0PkIKSN0C11CfUHUj84OT5XOJ6tDZ6bDRO2 (::1) 37.66ms
INFO:mage_ai.api.logging:[2023-05-16T22:33:19.035426][api.views] Action: list projects None  
INFO:mage_ai.api.logging:[2023-05-16T22:33:19.035610][api.views] Latency: 0.1526 seconds
INFO:tornado.access:304 GET /api/projects?api_key=zkWlN0PkIKSN0C11CfUHUj84OT5XOJ6tDZ6bDRO2 (::1) 153.95ms
INFO:mage_ai.api.logging:[2023-05-16T22:33:19.545519][api.views] Action: list kernels None  
INFO:mage_ai.api.logging:[2023-05-16T22:33:19.545792][api.views] Latency: 0.0137 seconds
INFO:tornado.access:304 GET /api/kernels?api_key=zkWlN0PkIKSN0C11CfUHUj84OT5XOJ6tDZ6bDRO2 (::1) 15.31ms
INFO:mage_ai.api.logging:[2023-05-16T22:33:19.555761][api.views] Action: list files None  
INFO:mage_ai.api.logging:[2023-05-16T22:33:19.555962][api.views] Latency: 0.0045 seconds
INFO:tornado.access:304 GET /api/files?api_key=zkWlN0PkIKSN0C11CfUHUj84OT5XOJ6tDZ6bDRO2 (::1) 8.44ms
INFO:mage_ai.api.logging:[2023-05-16T22:33:19.568087][api.views] Action: list secrets None  
INFO:mage_ai.api.logging:[2023-05-16T22:33:19.569231][api.views] Latency: 0.0031 seconds
INFO:tornado.access:304 GET /api/secrets?api_key=zkWlN0PkIKSN0C11CfUHUj84OT5XOJ6tDZ6bDRO2 (::1) 9.39ms
INFO:tornado.access:101 GET /websocket/ (::1) 1.17ms
INFO:mage_ai.server.active_kernel:Switch active kernel: python3
INFO:mage_ai.server.active_kernel:Kernel python3 is already alive.
INFO:mage_ai.api.logging:[2023-05-16T22:33:24.814437][api.views] Action: list variables mage_demo_from_local pipelines mage_demo_from_local
INFO:mage_ai.api.logging:[2023-05-16T22:33:24.814563][api.views] Latency: 5.2501 seconds
INFO:tornado.access:200 GET /api/pipelines/mage_demo_from_local/variables?api_key=zkWlN0PkIKSN0C11CfUHUj84OT5XOJ6tDZ6bDRO2 (::1) 11500.77ms
INFO:mage_ai.api.logging:[2023-05-16T22:33:31.067020][api.views] Action: list data_providers None  
INFO:mage_ai.api.logging:[2023-05-16T22:33:31.067208][api.views] Latency: 11.5041 seconds
INFO:tornado.access:304 GET /api/data_providers?api_key=zkWlN0PkIKSN0C11CfUHUj84OT5XOJ6tDZ6bDRO2 (::1) 11509.68ms
INFO:tornado.access:101 GET /websocket/terminal?api_key=zkWlN0PkIKSN0C11CfUHUj84OT5XOJ6tDZ6bDRO2&token=null (::1) 62.14ms
INFO:terminado.websocket:TermSocket.open: tty
INFO:terminado.websocket:TermSocket.open: Opened tty
INFO:mage_ai.api.logging:[2023-05-16T22:33:31.143994][api.views] Action: detail git_branches test  
INFO:mage_ai.api.logging:[2023-05-16T22:33:31.144265][api.views] Latency: 0.0028 seconds
INFO:tornado.access:304 GET /api/git_branches/test?api_key=zkWlN0PkIKSN0C11CfUHUj84OT5XOJ6tDZ6bDRO2 (::1) 9.31ms
INFO:mage_ai.api.logging:[2023-05-16T22:33:31.148125][api.views] Action: detail clusters emr  
INFO:mage_ai.api.logging:[2023-05-16T22:33:31.148334][api.views] Latency: 0.0022 seconds
INFO:tornado.access:304 GET /api/clusters/emr?api_key=zkWlN0PkIKSN0C11CfUHUj84OT5XOJ6tDZ6bDRO2 (::1) 12.08ms
INFO:mage_ai.api.logging:[2023-05-16T22:33:31.156926][api.views] Action: list block_templates None  
INFO:mage_ai.api.logging:[2023-05-16T22:33:31.157832][api.views] Latency: 0.0058 seconds
INFO:tornado.access:304 GET /api/block_templates?api_key=zkWlN0PkIKSN0C11CfUHUj84OT5XOJ6tDZ6bDRO2 (::1) 19.12ms
Exception ignored in: <function KernelClient.__del__ at 0x7fad83428440>
Traceback (most recent call last):
  File "/Users/ravindra/mage_demo/lib/python3.7/site-packages/jupyter_client/client.py", line 121, in __del__
    if self._created_context and self.context and not self.context.closed:
  File "/Users/ravindra/mage_demo/lib/python3.7/site-packages/traitlets/traitlets.py", line 703, in __get__
    return self.get(obj, cls)
  File "/Users/ravindra/mage_demo/lib/python3.7/site-packages/traitlets/traitlets.py", line 659, in get
    default = obj.trait_defaults(self.name)
  File "/Users/ravindra/mage_demo/lib/python3.7/site-packages/traitlets/traitlets.py", line 1872, in trait_defaults
    return self._get_trait_default_generator(names[0])(self)
  File "/Users/ravindra/mage_demo/lib/python3.7/site-packages/jupyter_client/client.py", line 100, in _context_default
    return zmq.asyncio.Context()
  File "/Users/ravindra/mage_demo/lib/python3.7/site-packages/zmq/sugar/context.py", line 125, in __init__
    super().__init__(io_threads=io_threads, shadow=shadow_address)
  File "zmq/backend/cython/context.pyx", line 49, in zmq.backend.cython.context.Context.__init__
zmq.error.ZMQError: Too many open files
INFO:mage_ai.api.logging:[2023-05-16T22:33:31.290642][api.views] Action: list kernels None  
INFO:mage_ai.api.logging:[2023-05-16T22:33:31.291102][api.views] Latency: 0.1160 seconds
INFO:tornado.access:304 GET /api/kernels?api_key=zkWlN0PkIKSN0C11CfUHUj84OT5XOJ6tDZ6bDRO2 (::1) 119.43ms
INFO:mage_ai.server.scheduler_manager:Scheduler status: running.
INFO:mage_ai.server.active_kernel:Switch active kernel: python3
INFO:mage_ai.api.logging:[2023-05-16T22:33:46.931105][api.views] Action: list variables mage_demo_from_local pipelines mage_demo_from_local
INFO:mage_ai.api.logging:[2023-05-16T22:33:46.931224][api.views] Latency: 15.7526 seconds
INFO:tornado.access:304 GET /api/pipelines/mage_demo_from_local/variables?api_key=zkWlN0PkIKSN0C11CfUHUj84OT5XOJ6tDZ6bDRO2 (::1) 22580.50ms
ERROR:tornado.application:Uncaught exception GET /websocket/ (::1)
HTTPServerRequest(protocol='http', host='localhost:6789', method='GET', uri='/websocket/', version='HTTP/1.1', remote_ip='::1')
Traceback (most recent call last):
  File "/Users/ravindra/mage_demo/lib/python3.7/site-packages/tornado/websocket.py", line 647, in _run_callback
    result = callback(*args, **kwargs)
  File "/Users/ravindra/mage_demo/lib/python3.7/site-packages/mage_ai/server/websocket_server.py", line 214, in on_message
    pipeline = Pipeline.get(pipeline_uuid, get_repo_path())
  File "/Users/ravindra/mage_demo/lib/python3.7/site-packages/mage_ai/data_preparation/models/pipeline.py", line 214, in get
    pipeline = self(uuid, repo_path=repo_path)
  File "/Users/ravindra/mage_demo/lib/python3.7/site-packages/mage_ai/data_preparation/models/pipeline.py", line 65, in __init__
    self.load_config_from_yaml()
  File "/Users/ravindra/mage_demo/lib/python3.7/site-packages/mage_ai/data_preparation/models/pipeline.py", line 406, in load_config_from_yaml
    self.load_config(self.get_config_from_yaml(), catalog=catalog)
  File "/Users/ravindra/mage_demo/lib/python3.7/site-packages/mage_ai/data_preparation/models/pipeline.py", line 390, in get_config_from_yaml
    raise Exception(f'Pipeline {self.uuid} does not exist.')
Exception: Pipeline undefined does not exist.
INFO:mage_ai.server.active_kernel:Kernel python3 is already alive.
INFO:mage_ai.server.scheduler_manager:Scheduler status: running.
Too many open files (src/kqueue.cpp:62)
Abort trap: 6
(mage_demo) (base) Ravindras-MBP:mage_demo ravindra$ [IPKernelApp] WARNING | Parent appears to have exited, shutting down.

**Expected behavior**
The local instance of mage should not should down again and again.

**Screenshots**

**Desktop (please complete the following information):**

 - Browser chrome

Model Name:	MacBook Pro
  Model Identifier:	MacBookPro12,1
  Processor Name:	Dual-Core Intel Core i5
  Processor Speed:	2.7 GHz
  Number of Processors:	1
  Total Number of Cores:	2
  L2 Cache (per Core):	256 KB
  L3 Cache:	3 MB
  Hyper-Threading Technology:	Enabled
  Memory:	8 GB
  Boot ROM Version:	428.60.3.0.0
  SMC Version (system):	2.28f7

**Smartphone (please complete the following information):**

**Additional context**

**Comment by wangxiaoyou1993** [comment]
Hey @ravindra-kumar25 , could you follow this doc to increase the limit of "open files" on your laptop? https://docs.mage.ai/production/configuring-production-settings/overview#ulimit

**Comment by ravindra-kumar25** [comment]
Thanks for sharing the solution. it worked.

**Comment by ravindra-kumar25** [comment]
Closing the issue.
