### ISSUE TITLE
Issue while setting up project

### ISSUE THREAD

**Issue by kshitiz305** [mage-ai/mage-ai#2666]
**Describe the bug**
Error while setting up project.
**To Reproduce**
1. Go to  ./scripts/init.sh dev inside the project clone folder.

**Expected behavior**

**Screenshots**
![image](https://github.com/mage-ai/mage-ai/assets/38988779/24e044a3-527c-4bee-9295-9836cfdc8e17)

**Desktop (please complete the following information):**
 - OS: Windows
 - Browser chrome

**Additional context**

 > [19/28] RUN wget https://raw.githubusercontent.com/jupyter-incubator/sparkmagic/master/sparkmagic/example_config.json:
#0 0.323 --2023-05-21 11:13:23--  https://raw.githubusercontent.com/jupyter-incubator/sparkmagic/master/sparkmagic/example_config.json
#0 0.329 Resolving raw.githubusercontent.com (raw.githubusercontent.com)... 49.44.79.236, ::ffff:49.44.79.236
#0 0.342 Connecting to raw.githubusercontent.com (raw.githubusercontent.com)|49.44.79.236|:443... connected.
#0 13.87 GnuTLS: The TLS connection was non-properly terminated.
#0 13.87 Unable to establish SSL connection.
------
failed to solve: executor failed running [/bin/sh -c wget https://raw.githubusercontent.com/jupyter-incubator/sparkmagic/master/sparkmagic/example_config.json]: exit code: 4

**Comment by kshitiz305** [comment]
yes

**Comment by wangxiaoyou1993** [comment]
Hey @kshitiz305 , could you clarify it a little bit? Do you want to contribute to Mage or just use Mage to build pipelines?

**Comment by wangxiaoyou1993** [comment]
Close this ticket since building docker image not necessary for setting up project.
