### ISSUE TITLE
KafkaSource: publish timestamp and key

### ISSUE THREAD

**Issue by mazieb** [mage-ai/mage-ai#2707]
**Is your feature request related to a problem? Please describe.**
We are storing information in kafka messages using the key, value and timestamp fields. The current implementation of KafkaSource only publishes the value.

**Describe the solution you'd like**
We would like to get all the kafka message information, including key, value and timestamp.

**Describe alternatives you've considered**
Streaming pipelines are very restricted. We can't find an easy way to implement custom data loaders in python. 

**Additional context**
In [kafka.py:125](https://github.com/mage-ai/mage-ai/blob/b5039e3301d34a28355eb7af2410c31219f7b886/mage_ai/streaming/sources/kafka.py#LL125C13-L125C61) there may be a possibility to extend the message properties published.

**Comment by thomaschung408** [comment]
Hi @mazieb! Thank you for bringing this to our attention. We'll review this request and get back to you on possible solution and timeline shortly.

**Comment by wangxiaoyou1993** [comment]
We'll update the KafkaSource to publish the whole message.
