### ISSUE TITLE
Your JWT_SECRET is not a secret

### ISSUE THREAD

**Issue by Firesphere** [mage-ai/mage-ai#2722]
https://github.com/mage-ai/mage-ai/blob/master/mage_ai/authentication/oauth2.py#L8

**Comment by johnson-mage** [comment]
In v0.8.96+, you can modify the `JWT_SECRET` via an environment variable. You can refer to our docs for details on [configuring](https://docs.mage.ai/getting-started/setup#environment-variables) the [env vars](https://docs.mage.ai/development/environment-variables).
