### ISSUE TITLE
Fix inserting LONGTEXT into Snowflake destination (data integration pipeline)

### ISSUE THREAD

**Issue by wangxiaoyou1993** [mage-ai/mage-ai#2727]
> I have observed that during MySQL to Snowflake data load, within snowflake inserts, all of the string columns get cast as VARCHAR(255). I have a LONGTEXT field coming in from MySQL which is failing to load into SF tables as a result of this restriction. Is this restriction done for a reason?

[Slack Message](https://mageai.slack.com/archives/C03HTTWFEKE/p1685482493425459?thread_ts=1685482493.425459&cid=C03HTTWFEKE)

**Comment by jamccauley** [comment]
This bug also affects fields of type TEXT, not just LONGTEXT.
