### ISSUE TITLE
Issue on docs

### ISSUE THREAD

**Issue by necatiarslan** [mage-ai/mage-ai#2756]
Path: /contributing/backend/api/pipelines

Even though the api response is error, the call is not successful, auth issue for example, the status is 200.
The status should be 400, 401 etc.

compare to airflow API 
https://airflow.apache.org/docs/apache-airflow/stable/stable-rest-api-ref.html#operation/patch_dags

**Comment by thomaschung408** [comment]
Thanks for bringing this to our attention @necatiarslan! We'll take a look and have it fixed ASAP.

**Comment by mattppal** [comment]
Hi @necatiarslan! Could you provide a bit more info?

You're saying our documentation is incorrect? Or you're getting a 200 status, even when a call fails?

**Comment by mattppal** [comment]
Hi @necatiarslan— I think I might understand your issue.

All of our calls return a 200, for example:

```
{
'error': {'code': 404,
  'message': 'Email/username and/or password invalid.',
  'type': 'record_not_found'},
 'status': 200
}
```

I believe this is a limitation of returning a `json` payload for each response. You can get _actual_ code by checking the `code` key within the `error` element.

**Comment by mattppal** [comment]
I'll update our documentation to reflect this
