### ISSUE TITLE
Video in documentation is not shown properly

### ISSUE THREAD

**Issue by FlorianK13** [mage-ai/mage-ai#2767]
**Describe the bug**
The first Demo video in https://docs.mage.ai/guides/data-integration-pipeline is shown in a zoomed in version.

**To Reproduce**
1. Go to https://docs.mage.ai/guides/data-integration-pipeline
2. Scroll to the first video
3. See error

**Expected behavior**
A normal view of the video.

**Screenshots**
![grafik](https://github.com/mage-ai/mage-ai/assets/74312290/b419e10b-d808-47f1-8ce3-a53836281ecd)

**Desktop (please complete the following information):**
 - OS: Windows
 - Browser: Firefox
 - Version 113.0.2

**Comment by johnson-mage** [comment]
@FlorianK13 Thanks for bringing this to our attention. This seems to be a Firefox-specific issue. We'll look into it.

**Comment by johnson-mage** [comment]
This should be resolved now.
