### ISSUE TITLE
Docs: broken link to "Set up DBT models & orchestrate DBT runs" tutorial

### ISSUE THREAD

**Issue by cch0** [mage-ai/mage-ai#2792]
**Describe the bug**
From the Tutorials page, the link to "Set up DBT models & orchestrate DBT runs" is broken.

**To Reproduce**
1. Go to [Tutorials](https://docs.mage.ai/introduction/overview#tutorials)
2. Click on `Set up DBT models & orchestrate DBT runs`.
3. The link (https://docs.mage.ai/integrations/dbt-models) does not exist and falls back to [Overview](https://docs.mage.ai/introduction/overview) page

**Expected behavior**
Tutorial page has the correct link (https://docs.mage.ai/tutorials/setup-dbt) instead.

**Screenshots**

![mage_dbt_doc](https://github.com/mage-ai/mage-ai/assets/1668614/af2494e5-b264-4e02-aff3-aef7be19ed8f)

**Desktop (please complete the following information):**
 - OS: [MacOS]
 - Browser [Chrome]
 - Version [Version 113.0.5672.126 (Official Build) (arm64)]

**Smartphone (please complete the following information):**
n/a

**Additional context**

**Comment by tommydangerous** [comment]
Will fix ASAP

**Comment by tommydangerous** [comment]
Fixed!

**Comment by cch0** [comment]
> Fixed!

Thanks for the quick turn around. Was the link in `README.md` also fixed as well?  I was going to submit a PR but you beat me to it, thanks again.
