### ISSUE TITLE
Couchbase Certificate Authentication

### ISSUE THREAD

**Issue by jamie-quickplay** [mage-ai/mage-ai#2796]
The Couchbase connector looks awesome. However my company's servers require VPN access, and I need to provide authentication certificates to access the data.

Could you look into adding an option to provide a certificate to the Couchbase connector [here](https://github.com/mage-ai/mage-ai/blob/82e1fd91f8928720835e4de88cedb6e2e9529cb6/mage_integrations/mage_integrations/connections/couchbase/__init__.py#L8), which would then accept a path when I set up a connection in the UI? It looks like the Python Couchbase package provides a certificate authentication call [here](https://github.com/couchbase/couchbase-python-client/blob/4ffe4574b07dad0fca0d9396998f7fffea962b7d/couchbase/auth.py#L77) so it should be relatively straight forward to handle the connection option using built in functions. 

My alternative is doing this myself, but I only discovered Mage this week.

**Comment by thomaschung408** [comment]
Hi @jamie-quickplay! Thank you for bringing this to our attention. We'll take a look and get back to you shortly.

**Comment by wangxiaoyou1993** [comment]
@jamie-quickplay thanks for requesting the feature!
It'll be a bit hard for us to set up a similar environment with you and use certificate to authenticate. I wonder whether you're interested in contributing to Mage. You can modify the source code of the [Couchbase connector](https://github.com/mage-ai/mage-ai/blob/82e1fd91f8928720835e4de88cedb6e2e9529cb6/mage_integrations/mage_integrations/connections/couchbase/__init__.py#L8) to support authentication with certificate. I can provide more code pointers if you want to make this change.

**Comment by wangxiaoyou1993** [comment]
Close this ticket as it's no longer needed. Feel free to reopen it if anyone needs this feature in the future.
