### ISSUE TITLE
open telemetry integration

### ISSUE THREAD

**Issue by dichouhan** [mage-ai/mage-ai#2811]
The program lacks support for open telemetry, It will be great feature, and would provide most out of mage.

Using open telemetry, we can allow users to provide OTL config, and through that we can publish, live metrics.

https://opentelemetry.io/docs/

I'd like to work on this, please provide follow-up asap.

**Comment by tkeller-moxe** [comment]
An option here would be to make an external exporter application that scrapes mages metrics endpoints and serves them in open telemetry format. 
https://github.com/nats-io/prometheus-nats-exporter
For an example. This would decouple the effort from mage is self ;)

**Comment by dichouhan** [comment]
so basically, I want to track stuff like , execution time of pipeline, blocks. time of completion, failure, etc.

**Comment by wangxiaoyou1993** [comment]
Hi @dichouhan , are you still working on the open telemetry integration?

**Comment by dichouhan** [comment]
> Hi @dichouhan , are you still working on the open telemetry integration?
was away for a while, still working on it I'm aiming to get it done by end of this month!

**Comment by mfreeman451** [comment]
Any updates on this? I am interested in this as well and willing to contribute.

**Comment by wangxiaoyou1993** [comment]
Hi @mfreeman451 , if you're interested in this, feel free to take it on.

**Comment by wangxiaoyou1993** [comment]
Hi @mfreeman451 , are you still interested in working on it? If so, we can discuss the implementation.

**Comment by wangxiaoyou1993** [comment]
The feature has been added in the PR https://github.com/mage-ai/mage-ai/pull/4476
It's released in version 0.9.64
