### ISSUE TITLE
what is mage-fs?

### ISSUE THREAD

**Issue by tirelibirefe** [mage-ai/mage-ai#2820]
Hello

I would like to install mage by using Helm Chart but there are cpl of expressions not clear like mage-fs ve pvc-name...

What do you mean "mage-fs"? Do you mean StorageClass? What if I would like to use default storageclass? 

What is pvc-name? Can it be any name or does the Chart not create/name the persistent volume claim?

Thanks & Regards

**Comment by wangxiaoyou1993** [comment]
Hello @tirelibirefe , you'll need to provision the persistent volume claim yourself. You can follow this doc: https://docs.mage.ai/production/deploying-to-cloud/using-helm#customize-deployment

**Comment by wangxiaoyou1993** [comment]
Hi @tirelibirefe , I'm going to close this ticket. Let me know if you more questions on the persistent volume claim.
