### ISSUE TITLE
Right clicking on block shows multiple "Run selected block" as options.

### ISSUE THREAD

**Issue by wangxiaoyou1993** [mage-ai/mage-ai#2822]
Original thread
> When I right click on my block, I got loads of "Run selected block" as option. Why is that? How to remove them?

[Slack Message](https://mageai.slack.com/archives/C03HTTWFEKE/p1687184846549999?thread_ts=1687184846.549999&cid=C03HTTWFEKE)

**Comment by johnson-mage** [comment]
This should be resolved in v0.8.97+
