### ISSUE TITLE
Fix exporting data to Clickhouse

### ISSUE THREAD

**Issue by wangxiaoyou1993** [mage-ai/mage-ai#2864]
Original thread:
> is there any guide to set up clickhouse?  I use same sql to export data. failed in clickhouse but succesfull for postgres

[Slack Message](https://mageai.slack.com/archives/C03HTTWFEKE/p1687617652664539?thread_ts=1687617652.664539&cid=C03HTTWFEKE)

**Comment by csharplus** [comment]
@wangxiaoyou1993 sure, working on it.

**Comment by csharplus** [comment]
This issue has been fixed in https://github.com/mage-ai/mage-ai/pull/2871 and https://github.com/mage-ai/mage-ai/pull/2877

**Comment by csharplus** [comment]
Fix merged into the main branch.
