### ISSUE TITLE
Issue on docs

### ISSUE THREAD

**Issue by joezein** [mage-ai/mage-ai#2869]
Path: /contributing/backend/api/pipelines

Missing documentation (WIP) for programmatic pipeline creation (POST) and updates (PUT)

**Comment by wangxiaoyou1993** [comment]
Hi @joezein , we're working on this doc now.

**Comment by mattppal** [comment]
Hi Joe! Thanks for bringing this to light. 

This work is in progress [here](https://github.com/mage-ai/mage-ai/issues/2883).

**Comment by mattppal** [comment]
V1 docs for pipelines just went live!
