### ISSUE TITLE
[Errorno 13]Permission denied:'/.gitconfig.lock'

### ISSUE THREAD

**Issue by tpatel1912** [mage-ai/mage-ai#2878]
We have tried to deploy it on OpenShift and we are facing below error

[Errorno 13]Permission denied:'/.gitconfig.lock'

You can refere below deployment file
[mageai-deployment.txt](https://github.com/mage-ai/mage-ai/files/11893503/mageai-deployment.txt)

Any helpful pointers would be appreciated.

Thanks

**Comment by wangxiaoyou1993** [comment]
cc: @dy46

**Comment by wangxiaoyou1993** [comment]
This issue has been fixed in latest version.
