### ISSUE TITLE
Switch project inside monorepo

### ISSUE THREAD

**Issue by Jacse** [mage-ai/mage-ai#2882]
**Is your feature request related to a problem? Please describe.**
I've set up git sync in my cloud deployment so it always pulls from master. But every time it boots, it boots into `default_repo` project, it then fetches my other projects though git (and I can see them in the file system), but I can't change the active project to these ones. So I'm kinda stuck.

**Describe the solution you'd like**
Where it says "default repo" to the top left I'd like a dropdown where I can switch between projects in my repo.

**Describe alternatives you've considered**
A way to for git sync to be run before the project is selected. I'm not sure which of multiple projects it would select though.

**Additional context**
I'm currently deploying on k8s with git sync enabled on server start and before pipeline runs.

It looks like it pulls the data, I just can't use it because I'm stuck in the `default_repo` project (which I guess is auto-created when there's no data).

From the documentation it seems like the recommended setup is to have a monorepo with multiple projects. If this is they way to go it seems a little weird you can't navigate these different projects inside the app.

**Comment by wangxiaoyou1993** [comment]
We're launching the workspace management very soon: https://docs.mage.ai/developing-in-the-cloud/workspaces/overview
This will allow you to manage multiple projects.

**Comment by wangxiaoyou1993** [comment]
Hey @Jacse , just to give an update, we've launched the workspace management, which allows you to manage multiple projects. https://docs.mage.ai/developing-in-the-cloud/workspaces/overview

**Comment by wangxiaoyou1993** [comment]
Close this issue since it's supported by workspace management
