### ISSUE TITLE
Remote control Mage via REST

### ISSUE THREAD

**Issue by fithisux** [mage-ai/mage-ai#2883]
**Is your feature request related to a problem? Please describe.**
Just a feature request, can help integration testing

**Describe the solution you'd like**
Something like Airflow REST API

**Describe alternatives you've considered**
GEB + Browser but a bit awkward?

**Additional context**
A similar API? https://github.com/apache/airflow-client-python

**Comment by fithisux** [comment]
Thank you. I will keep my eye on it.

**Comment by tommydangerous** [comment]
Everything you can do in the Mage UI is API driven.

While we write out the docs, of you inspect element and view the network tab, you'll be able to see the type of request being made.
