### ISSUE TITLE
Module dependency error in tutorial 

### ISSUE THREAD

**Issue by balexandermunoz** [mage-ai/mage-ai#2888]
If mage is installed with the `pip install mage-ai` command, then dependencies are needed to run a project with `mage init [project_name]` or the tutorial project.
Instead, the documentation should suggest `pip install mage-ai[all]`.

**To Reproduce**
1. run `pip install mage-ai`
2. run `mage init [project_name]` and `mage start [project_name]`
3. Follow the [ETL pipeline tutorial](https://docs.mage.ai/tutorials/load-api-data) until you reach the export data block

![image](https://github.com/mage-ai/mage-ai/assets/18507365/18386a0c-87e7-47e0-b934-74121561cf15)

**Expected behavior**
The tutorial should be achievable with the documentation read so far, however there are missing dependency errors.

**Comment by balexandermunoz** [comment]
It happens to me with Python 3.7.4 but I have tested with 3.10 and 3.11 in virtualenvs and it also happens

**Comment by wangxiaoyou1993** [comment]
Got it. We'll debug and fix it.

**Comment by dy46** [comment]
the ETL pipeline tutorial has been updated with new steps and new quickstart instructions, so closing this issue now
