### ISSUE TITLE
Illegal instruction (core dumped)

### ISSUE THREAD

**Issue by ghomsi** [mage-ai/mage-ai#2900]
**Describe the bug**
WARNING:traitlets:Message signing is disabled.  This is insecure and not recommended!
WARNING:traitlets:Message signing is disabled.  This is insecure and not recommended!
Illegal instruction (core dumped)

**To Reproduce**
1. Conda create and activate new env
2. pip install mage-ai
3. mage-ai start

**Expected behavior**
launch mage UI.

**Desktop (please complete the following information):**
 - OS: Ubuntu 18.04

**Comment by wangxiaoyou1993** [comment]
Hi @ghomsi , do you use virtual machine?

**Comment by ghomsi** [comment]
Hi @wangxiaoyou1993 
Yes, anaconda.

**Comment by ghomsi** [comment]
I have installed the oldest version (pip install mage-ai==0.8.60) and "mage start" works without errors.

**Comment by wangxiaoyou1993** [comment]
Got it. @ghomsi , do you run your ubuntu in a VM or is Ubuntu the OS on your laptop?

**Comment by mwportfolio** [comment]
Having the same issue with error message "Illegal instruction (core dumped)"

Using Ubuntu 23.04 as a VM

Error occurs when trying to start mage, both after docker install and pip install

**Comment by wangxiaoyou1993** [comment]
Here is one update from one user who resolved the issue:
![image](https://github.com/mage-ai/mage-ai/assets/80284865/aa1ba408-ee9f-42cb-a8a9-f8663bbddce1)

**Comment by wangxiaoyou1993** [comment]
Root cause: https://github.com/mage-ai/mage-ai/issues/3775
Solution: https://github.com/mage-ai/mage-ai/issues/3775#issuecomment-1896613315
