### ISSUE TITLE
Is there anyway to change the word color in traceback?

### ISSUE THREAD

**Issue by chrisyang-callaway** [mage-ai/mage-ai#2905]
**Is your feature request related to a problem? Please describe.**
some lines in the traceback log are hardly read. See the attached screenshot. The context in blue is not able to read with the dark mode background.

**Describe the solution you'd like**
able to change the color.

**Describe alternatives you've considered**

**Additional context**
![1688578971964](https://github.com/mage-ai/mage-ai/assets/120050655/57f77af0-c154-41be-b54e-459f6a973e7f)

**Comment by chrisyang-callaway** [comment]
BTW, I am using the browser.

**Comment by wangxiaoyou1993** [comment]
Hi @chrisyang-callaway , this issue is fixed in this PR: https://github.com/mage-ai/mage-ai/pull/2913
And the change is available in latest version. I'm going to close this ticket. Let me know if you still have problem reading the stacktrace.
