### ISSUE TITLE
Fix executing dynamic blocks on k8s executor

### ISSUE THREAD

**Issue by wangxiaoyou1993** [mage-ai/mage-ai#2908]
Original thread:
> I have a pipeline with dynamic blocks, but when I run it the pipeline goes to “completed” after having just finished the first block. The dynamic blocks are just in initial state and are never called. Any ideas?
> I’ve checked the output of the data loader and it correctly returns a list of files

[Slack Message](https://mageai.slack.com/archives/C03HTTWFEKE/p1688413744904179?thread_ts=1688413744.904179&cid=C03HTTWFEKE)

Additional contexts
* This issue doesn't happen on local_python executor.
* This issue happens on GCP cloud run executor as well: https://mageai.slack.com/archives/C03HTTWFEKE/p1688692715939499

**Comment by Jacse** [comment]
To us, this is a very critical bug because it means we simply can't use it. Is there any way to increase prio on it or help out @wangxiaoyou1993 ?

**Comment by wangxiaoyou1993** [comment]
Hi @Jacse , we'll prioritize it this week
