### ISSUE TITLE
Editing a trigger's SLA in the Pipeline UI resets CRON expression to `custom`

### ISSUE THREAD

**Issue by mattppal** [mage-ai/mage-ai#2967]
Editing a trigger's SLA in the Pipeline UI resets CRON expression to `custom`

![image](https://github.com/mage-ai/mage-ai/assets/59450879/5b1a7ce9-95ee-41a9-9baa-348b03224d86)

https://mageai.slack.com/archives/C03HTTWFEKE/p1689157754834259

**Comment by mattppal** [comment]
cc @wangxiaoyou1993

**Comment by wangxiaoyou1993** [comment]
This issue is fixed in version 0.9.1
