### ISSUE TITLE
PostgreSQL integration pipelines SOURCES fail to quote schema name, so fail on schemas with invalid characters

### ISSUE THREAD

**Issue by langabi** [mage-ai/mage-ai#2973]
For a schema name with a character such as a hyphen, mage.ai isn't quoting that schema name and so the queries are failing, for PostgreSQL (and maybe other DBs) as SOURCES.

This is a reopening of bug #2903 , as the commit on that bug fixed the issue for these databases as DESTINATIONS, but not as SOURCES.

I believe the issue is on line 38 of `mage-ai/mage_integrations/mage_integrations/sources/postgresql
/__init__.py`, where the table prefix should have backticks/quotes around the schema name. I'm not proposing a pull request as I might be wrong, and not sure what other databases this issue might affect.

**Comment by wangxiaoyou1993** [comment]
ah, got it. we'll fix this issue in Postgres source.
