### ISSUE TITLE
OpenSSL 1.1.1 is missing

### ISSUE THREAD

**Issue by haithem-souala** [mage-ai/mage-ai#3044]
**Describe the bug**
The lib libssl1 or OpenSSL 1.1.1 is missing in the mageai image, which impact the couchbase python SDK.

**To Reproduce**

**Expected behavior**
OpenSSL 1.1.1 available in the built image.

**Screenshots**

**Desktop (please complete the following information):**

**Smartphone (please complete the following information):**

**Additional context**

A suggestion from the couchbase team.

<img width="884" alt="Capture d’écran 2023-07-21 à 10 11 19" src="https://github.com/mage-ai/mage-ai/assets/75131226/0b5f4fca-3677-46b6-b10f-d887b298f1f6">

**Comment by wangxiaoyou1993** [comment]
Thanks for reporting the issue. We're looking into it.

**Comment by dy46** [comment]
Hey @haithem-souala, I added a Dockerfile in the repo to install openssl version 1.1.1. You can try building Mage from this dockerfile, and it should use openssl 1.1.1g instead of openssl 3.

https://github.com/mage-ai/mage-ai/blob/master/integrations/openssl/1_1_1g/Dockerfile
