### ISSUE TITLE
Allow override for default wait of ECS Executor block

### ISSUE THREAD

**Issue by mattppal** [mage-ai/mage-ai#3121]
The default wait time for an ECS Executor block is defaulted at 10mins (15s x 40 retries), and theres no way to change this.

mage_ai\services\aws\ecs\ecs.py

https://boto3.amazonaws.com/v1/documentation/api/1.9.42/reference/services/ecs.html#ECS.Waiter.ServicesStable.wait

Is it possible to add a way to modify this for ECS tasks?

**Comment by wangxiaoyou1993** [comment]
The feature is included in v0.9.10
https://docs.mage.ai/production/configuring-production-settings/compute-resource#aws-ecs-executor
