### ISSUE TITLE
Add abstractmethod markers to Destination base class

### ISSUE THREAD

**Issue by jcorrado76** [mage-ai/mage-ai#3138]
When writing a new destination for the `mage_integrations` subpackage, you have to create a derived class based on `Destination` from the `base.py` module. 

Currently, the class is not marked as an abstract base class, and does not have `abstractmethod` methods. 

This means that for new developers to the project, the interface they must implement when trying to add a new destination is **implicit**, instead of **explicit**. 

It's well known that abstract base classes are not that value-added in Python (what does inheriting from `abc.ABC` even do?), but decorating the minimal API with `abstractmethod` explicitly requires developers to implement those methods in derived classes. Another option would be to use `Protocols`, which I think fits better here, but it might not be as well known, so I assume we'd stick with using the `abstractmethod` mechanism. 

Most of the value in this change would be to unambiguously signal to new developers what the minimal API that needs to be implemented by implementations of the base `Destination` class has to be. 

We don't need to make `Destination` inherit from `ABC`, but we should at least mark its methods that would raise an error anyways as `abstractmethod`s, like this one:

```python
def export_batch_data(self, record_data: List[Dict], stream: str) -> None:
        raise Exception('Subclasses must implement the export_batch_data method.')
```

I would also suggest we move `classmethods` to the bottom of the class code, since those methods aren't really methods of the class, but that's just how Python represents adding methods "within the namespace" of the class (`classmethod`s don't take `self`, they take an instance of `cls`).

Finally, I would suggest that we centralize the use of `_` and `__` prefixes on "private" methods. Some methods have `_`, and others have `__`. 
The convention in Python is for private methods to have a single `_`. The double `__` is used to trigger name-mangling in Python, which prevents attributes and methods from base classes from conflicting with methods by the same name derived classes. 
Unless we actually need name-mangling here, I suggest we pick one convention or the other, for cohesiveness and readability.

The requested changes would be to:
* mark the methods that currently raise an exception if not implemented, and replace the raised exception with an `abstractmethod` decorator
* move all such methods to the top of the code for the class, so it's obvious to new developers which methods need to be overridden
* move `classmethod` decorated methods to the bottom of the class
* switch all `__` prefixes to `_`

@wangxiaoyou1993  - let me know your thoughts on my proposals before we release this.
Thanks!

**Comment by mattppal** [comment]
Really love these ideas @jcorrado76! I'll check with the team and follow up with you 😄

**Comment by wangxiaoyou1993** [comment]
Hi @jcorrado76 , sorry for the late reply. These are good suggestions.
* mark the methods that currently raise an exception if not implemented, and replace the raised exception with an abstractmethod decorator
  * I think that's a great idea. we should do that.
* move all such methods to the top of the code for the class, so it's obvious to new developers which methods need to be overridden
  * good idea
* move classmethod decorated methods to the bottom of the class
  * good idea
* switch all __ prefixes to _
  * We currently use `_` for protected method that can be overridden by subclass and `__` as the private method.

**Comment by wangxiaoyou1993** [comment]
I'm going to work on this ticket.
