### ISSUE TITLE
ClickHouse data exporter bugs

### ISSUE THREAD

**Issue by mattppal** [mage-ai/mage-ai#3140]
Bugs in ClickHouse exporter:
- Throws an error when the table contains Boolean fields
- When the Raw SQL option is not activated
    - It tries to create the table with CREATE AS SELECT which not supported by ClickHouse Cloud
    - It does not use the custom table name
- When the Raw SQL  option is activated
    - The custom table name creates a table even if the block contains a CREATE command

https://mageai.slack.com/archives/C03HTTWFEKE/p1690806409870269

**Comment by detygon** [comment]
The ClickHouse exporter has also bugs in a data integration pipeline:
- The config field is still empty after selecting the destination
- The connection fails without any details (even with parameters that work for standard pipelines)

**Comment by csharplus** [comment]
> Version: 0.9.9 Env: Docker
> 
> The ClickHouse exporter has also bugs in a data integration pipeline:
> 
> * The config field is still empty after selecting the destination
> * The connection fails without any details (even with parameters that work for standard pipelines)

@detygon could you please create another bug on this ClickHouse issue in data integration pipelines, as the detailed implementation in data integration pipelines is different (i.e., not shared).

**Comment by detygon** [comment]
Ok, will do it !

**Comment by csharplus** [comment]
For the following issue mentioned:

```
When the Raw SQL option is not activated
* It tries to create the table with CREATE AS SELECT which not supported by ClickHouse Cloud
* It does not use the custom table name
```

I tested it with a locally running ClickHouse instance, and verified that it worked as expected (see screenshot below). I'll test it out with ClickHouse Cloud next.
![Screenshot 2023-08-05 at 12 28 47 AM](https://github.com/mage-ai/mage-ai/assets/42320565/4429e109-200e-4b68-a7bc-d5198f3322e8)

The newly created table was checked with ClickHouse client as well:
```
bins-mbp.repeater :) select * from test_table;

SELECT *
FROM test_table

Query id: 9b13564b-5d7e-4365-b18e-d997d2ecc229

┌─num_legs─┬─num_wings─┬─num_specimen_seen─┬─flag──┐
│        2 │         2 │                10 │ true  │
│        4 │         0 │                 2 │ true  │
│        8 │         0 │                 1 │ false │
│        0 │         0 │                 8 │ false │
└──────────┴───────────┴───────────────────┴───────┘

4 rows in set. Elapsed: 0.003 sec. 
```

**Comment by csharplus** [comment]
For the following issue reported:

```
When the Raw SQL option is activated
* The custom table name creates a table even if the block contains a CREATE command
```

I tried the following raw SQL commands in the ClickHouse Data exporter:
```
CREATE TABLE insert_select_testtable
(
    `a` Int8,
    `b` String,
    `c` Int8
)
ENGINE = MergeTree()
ORDER BY a;

INSERT INTO insert_select_testtable (*) VALUES (1, 'a', 1) ;
```

The new table `insert_select_testtable` was created and got populated with the given `insert` statement as well:
![Screenshot 2023-08-05 at 12 41 01 AM](https://github.com/mage-ai/mage-ai/assets/42320565/c1299992-9624-42c1-9bea-880a059afb98)

The new table was verified with the ClickHouse client as well:
```
bins-mbp.repeater :) select * from insert_select_testtable ;

SELECT *
FROM insert_select_testtable

Query id: 2e39e37f-a868-48cc-9e7a-52958cb25d80

┌─a─┬─b─┬─c─┐
│ 1 │ a │ 1 │
└───┴───┴───┘

1 row in set. Elapsed: 0.015 sec. 
```

**Comment by detygon** [comment]
For the following issue reported:

```
When the Raw SQL option is activated
* The custom table name creates a table even if the block contains a CREATE command
```

1. Set a custom table name
2. Add a create statement to the block with an engine different than Memory (eg. MergeTree)
3. Execute `SHOW CREATE TABLES [TABLENAME]` from the clickhouse client
4. See that the engine used is Memory which is different from the one mentionned in the block

**Comment by detygon** [comment]
For the following issue mentioned:
```
When the Raw SQL option is not activated
* It tries to create the table with CREATE AS SELECT which not supported by ClickHouse Cloud
* It does not use the custom table name
```
See error below:

![image](https://github.com/mage-ai/mage-ai/assets/25983025/142108f6-78c3-4476-9a42-e7a649434fa9)

**Comment by csharplus** [comment]
> 3\. SHOW CREATE TABLE [TABLENAME]

I tested creating a table on the ClickHouse Cloud with the following command:
```
CREATE TABLE insert_select_testtable
(
    `a` Int8,
    `b` String,
    `c` Int8
)
ENGINE = MergeTree()
ORDER BY a;

INSERT INTO insert_select_testtable (*) VALUES (1, 'a', 1) ;
```

The table was created in the `ReplicatedMergeTree` type, i.e., not the `Memory` type:
```
clickhouse-cloud :) SHOW CREATE TABLE insert_select_testtable;

SHOW CREATE TABLE insert_select_testtable

Query id: db1714fc-84a9-4bb3-a532-39e1c7526bfb

TimeoutSetter: Can't reset timeouts: Poco::Exception. Code: 1000, e.code() = 22, Invalid argument, Stack trace (when copying this message, always include the lines below):

 (version 23.6.1.1152 (official build))
Password for user (default): 
Connecting to database helloworld at fadpvrevk3.us-west-2.aws.clickhouse.cloud:9440 as user default.
Connected to ClickHouse server version 23.8.1 revision 54464.

ClickHouse client version is older than ClickHouse server. It may lack support for new features.

┌─statement──────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────┐
│ CREATE TABLE helloworld.insert_select_testtable
(
    `a` Int8,
    `b` String,
    `c` Int8
)
ENGINE = ReplicatedMergeTree('/clickhouse/tables/{uuid}/{shard}', '{replica}')
ORDER BY a
SETTINGS index_granularity = 8192 │
└────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────┘

1 row in set. Elapsed: 0.001 sec. 
```

@detygon could you please drop your test table, and re-run your block to re-generate it again to see if the table type is created as expected?

**Comment by csharplus** [comment]
> For the following issue mentioned:
> 
> ```
> When the Raw SQL option is not activated
> * It tries to create the table with CREATE AS SELECT which not supported by ClickHouse Cloud
> * It does not use the custom table name
> ```
> 
> See error below:
> 
> ![image](https://user-images.githubusercontent.com/25983025/258573332-142108f6-78c3-4476-9a42-e7a649434fa9.png)

This issue has been re-produced with the ClickHouse cloud. The fix is ready for review at: https://github.com/mage-ai/mage-ai/pull/3194.

**Comment by csharplus** [comment]
All the issues listed have been resolved. Please re-open if the same issues still exist.
