### ISSUE TITLE
Bookmark property values are not updated / cannot be edited manually

### ISSUE THREAD

**Issue by bdoester** [mage-ai/mage-ai#3153]
The actual goal is to fully reset some Mage pipelines - I couldn't find the functionality to this. So I deleted the Postgres destination schema and re-ran all pipelines. 
Mage however doesn't seem to pick up on this and still keeps storing the bookmark property values of the previous runs (saw this in the UI). I found out they are cached in `mage_data/[project_name]/pipelines/[pipeline_name]/postgresql/[source_name]/[destination_name]_state.json`.

Then, I at least tried to manually delete the bookmark property value using the UI but also this seems like a bug (see video): You can edit the field but the previous value will always show up again:
https://github.com/mage-ai/mage-ai/assets/116005683/5b69921a-5d1c-4ef3-bac5-034eb7a0aed2
<img width="1076" alt="image" src="https://github.com/mage-ai/mage-ai/assets/116005683/a419736c-4b89-4caa-a331-43c57e0dd938">

Running on Docker [mageai/mageai:0.9.10](https://hub.docker.com/layers/mageai/mageai/0.9.10/images/sha256-0088cd652a1a223cff2d046f84d8df0536758640701adee405425c18b4c6f756?context=explore)

**Comment by wangxiaoyou1993** [comment]
Thanks for reporting the bug. We'll fix it.
