### ISSUE TITLE
Investigate odd behavior with GCP Cloud Run deployment

### ISSUE THREAD

**Issue by mattppal** [mage-ai/mage-ai#3175]
On some GCP deploys, the postgres database is unable to be accessed by the server. One of our users was able to fix the issue by setting `MAGE_DATABASE_CONNECTION_URL` manually. We should investigate the issue and update our template if necessary.

https://mageai.slack.com/archives/C03HTTWFEKE/p1691077416821119?thread_ts=1688336702.264869&cid=C03HTTWFEKE

**Comment by wangxiaoyou1993** [comment]
Close this issue since no recent reports. Will reopen it if it's still an issue.
