### ISSUE TITLE
Data integration with INCREMENTAL causes duplicates in destination table

### ISSUE THREAD

**Issue by bdoester** [mage-ai/mage-ai#3198]
Hello again :)

I observed a Mage pipeline with an INCREMENTAL sync from/to a Postgres table creating really odd duplicate distributions. So digged into this: 

The source table provides an `updated_at` column (and an surrogate `id` column). I used  `updated_at` as the Bookmark value. I also set `id` to "Key prob" (but not to "Unique"). 
Now surprisingly, the source table's  `updated_at` column is not unique (maybe because of some bulk updates)! There are 10x `batch size` rows that share the same `updated_at` column. I assume then the load process of Mage runs those limit/offset queries ordered by `updated_at` - but now there is not deterministic order ensured anymore, so for every limit/offset query in the range of the duplicated `updated_at` value, it is not guaranteed that the batches are complete and non-overlapping.

This eventually results into duplicates (and missing rows) in the destination table :( 

I could image using a Postgres cursor might solve this issues since the ordering only happens once then. Or, Mage should forbid using Bookmark values to have duplicates.

Running on docker image 0.9.10

**Comment by splatcollision** [comment]
Just tested changing `unique_conflict_method` to be "IGNORE" and got the same result, one new destination row, with no change to the source.

**Comment by bdoester** [comment]
I guess "Unique" should just be compulsory 😃 Thanks @wangxiaoyou1993 !

**Comment by splatcollision** [comment]
Doing some more investigation, as with my simple test case, it still feels like a bug, and no configuration changes that I can make seem to help.

I've captured the logs of a pipeline run where the scheduler is using bookmarks to do an incremental sync, and the query that it starts with looks like: 

```
SELECT
COUNT(*) AS number_of_records
FROM \"public\".\"product_usage_metrics\"
WHERE \"id\" >= CAST('2' AS BIGINT)
```

Tracing back to the `mage_integrations/mage_integrations/sources/sql/base.py` file, in the `count_records` method, this query is being generated by the `__fetch_rows` method, with `count_records` set to True.

This results in the bookmark property ('id') being used from the last bookmark state, but my question now is: Why is the operator greater than and equal to? 

Code reference: https://github.com/mage-ai/mage-ai/blob/master/mage_integrations/mage_integrations/sources/sql/base.py#L353

In my (very simplified) example source database with only 2 rows, unique 'id' field with values 1, 2, for an INCREMENTAL sync, the behavior I'd expect for a 'count records' query would be to use a plain greater than operator. If that was the case, a source table with no new records would return a count of zero, not one.

Thanks for any suggestions @mattppal @wangxiaoyou1993

**Comment by sumanshusamarora** [comment]
Adding more examples - https://mageai.slack.com/archives/C03HTTWFEKE/p1691713423028329

**Comment by wangxiaoyou1993** [comment]
We've updated the operator to use greater than for unique columns. Thus, close this ticket.
Feel free to reopen it if you have more questions or issues.
