### ISSUE TITLE
MySQL syntax error "near 'BIGINT)'" while counting records for integration pipeline

### ISSUE THREAD

**Issue by langabi** [mage-ai/mage-ai#3228]
**Describe the bug**
Integration pipeline from MySQL to Bigquery, is failing to initialise due to a MySQL syntax error while counting records.

Unrelated issue - debug log shows MySQL password in plaintext

**To Reproduce**
- integration pipeline pulling multiple tables from MySQL to Bigquery
- rest of the tables are working ok, AND the first sync from this table started fine, but failed due to an unrelated issue (connectivity)
- now further syncs don't start successfully, due to syntax error as below
- nothing unusual in the MySQL source table schema; in particular, no unusually large integer fields (bigints), and the number of rows is 743,611 - not unreasonable

**Expected behavior**
Integration pipeline succeeds

**Desktop (please complete the following information):**
Mage.ai Version 0.9.12, running on k8s

**Debug log**
Key piece below, full log attached.

```
[log.txt](https://github.com/mage-ai/mage-ai/files/12302140/log.txt)
INFO [2023-08-09T10:38:50.767986] {"caller": "MySQL", "level": "INFO", "message": "Counting records for sales_flat_order_address started.", "tags": {"stream": "sales_flat_order_address"}, "timestamp": 1691577530, "uuid": "43179368e1ee4b859950f940624ce414", "type": "LOG"}

ERROR [2023-08-09T10:38:51.356202] {"caller": "MySQL", "level": "EXCEPTION", "message": "MySQL process failed with error 1064 (42000): You have an error in your SQL syntax; check the manual that corresponds to your MySQL server version for the right syntax to use near 'BIGINT)' at line 4.", "tags": {"error": "1064 (42000): You have an error in your SQL syntax; check the manual that corresponds to your MySQL server version for the right syntax to use near 'BIGINT)' at line 4", "errors": ["  File \"/usr/local/lib/python3.10/site-packages/mage_integrations/sources/mysql/__init__.py\", line 62, in <module>

    main(MySQL)

", "  File \"/usr/local/lib/python3.10/site-packages/singer/utils.py\", line 235, in wrapped

    return fnc(*args, **kwargs)

", "  File \"/usr/local/lib/python3.10/site-packages/mage_integrations/sources/base.py\", line 723, in main

    source.process()

", "  File \"/usr/local/lib/python3.10/site-packages/mage_integrations/sources/base.py\", line 280, in process

    errors=traceback.format_stack(),

"]
```

**Comment by wangxiaoyou1993** [comment]
@langabi Could you share what column types are there in your MySQL table?
Do you select any bookmark columns?

**Comment by PrincipalJohnShepherd** [comment]
I also experience it. 
No problems when synchronise FULL_TABLE but I get the error when using INCREMENTAL
It can be provoke by the "Bookmark" function on a int column. In my case an ID as 123456789

**Comment by PrincipalJohnShepherd** [comment]
`Exception: 2023-09-13T10:30:39 Error while executing query: 1064 (42000): You have an error in your SQL syntax; check the manual that corresponds to your MySQL server version for the right syntax to use near 'BIGINT)
ORDER BY `id`
LIMIT 10000 OFFSET 0' at line 9. Query string: SELECT
`id`
, `name`
, `company`
, `customerId`
, `searchData`
FROM contacts
WHERE `id` > CAST('887875712' AS BIGINT)
ORDER BY `id`
LIMIT 10000 OFFSET 0 {"caller": "MySQL", "level": "ERROR", "timestamp": 1694601039, "uuid": "e003a6bd4e314d0b8181eea51229c523", "type": "LOG"}`

**Comment by wangxiaoyou1993** [comment]
> `Exception: 2023-09-13T10:30:39 Error while executing query: 1064 (42000): You have an error in your SQL syntax; check the manual that corresponds to your MySQL server version for the right syntax to use near 'BIGINT) ORDER BY `id`LIMIT 10000 OFFSET 0' at line 9. Query string: SELECT`id`,`name`,`company`,`customerId`,`searchData`FROM contacts WHERE`id`> CAST('887875712' AS BIGINT) ORDER BY`id` LIMIT 10000 OFFSET 0 {"caller": "MySQL", "level": "ERROR", "timestamp": 1694601039, "uuid": "e003a6bd4e314d0b8181eea51229c523", "type": "LOG"}`
> 
> Mysql Version 5.7.42-log

Thank you for sharing the sql query. What's the data type of the ID in your mysql table?

**Comment by PrincipalJohnShepherd** [comment]
int(11)

**Comment by wangxiaoyou1993** [comment]
> int(11)

Got it. We'll fix this issue.
