### ISSUE TITLE
Too many open files even with large ulimits

### ISSUE THREAD

**Issue by dumim** [mage-ai/mage-ai#3244]
**Describe the bug**
We are trying to deploy Mage in production using an ECS cluster setup as recommended for AWS (using Terraform).
But after a few minutes of uptime the Dashboard becomes inaccessible. Initially the thoughts were some networking/connectivity issue, but after a look at the Cloudwatch logs we have isolated it to a ulimit issue. 

`OSError: [Errno 24] Too many open files` and `zmq.error.ZMQError: Too many open files`

We have increased the size of the task and the ulimits but still no luck. Our current settings are 512 CPU and 4GB Memory with the `nofile` ulimits defined as below in the Task Definition:
```
 "ulimits": [
        {
          "name": "nofile",
          "softLimit": 32768,
          "hardLimit": 65536
        }
      ]
```

There are no pipelines created, this is a fresh copy of Mage, with just the `example_pipeline` in it. Mage version is 0.9.8

**Screenshots**
![image](https://github.com/mage-ai/mage-ai/assets/30994223/2f096ee8-75fe-4084-b0fa-c380164a072e)

**Comment by wangxiaoyou1993** [comment]
Thanks for reporting it. We'll look into it.

**Comment by dumim** [comment]
Thanks @wangxiaoyou1993 we are currently blocked in production due to this. More contextual logs:
![image](https://github.com/mage-ai/mage-ai/assets/30994223/2cfb0e10-c5d8-4ead-9556-f23ea27c22b0)

**Comment by dumim** [comment]
Thanks @wangxiaoyou1993  we are currently blocked in production due to this. More contextual logs:
![Uploading image.png…]()

**Comment by dumim** [comment]
Thanks @wangxiaoyou1993 we are currently blocked in production due to this. More contextual logs:

![image](https://github.com/mage-ai/mage-ai/assets/30994223/8434fb87-5e9a-4cd3-b29e-ed925b8ba530)

**Comment by dumim** [comment]
More information: The memory utilisation of the task (2GB set in the case below) steadily rises (no pipelines except the example Titanic one), and then starts failing. The drops in memory is when the new task was initialised to replace the one that was erroring out
![image](https://github.com/mage-ai/mage-ai/assets/30994223/717d0bec-02f4-4c5b-bd6e-31c8500a4453)

**Comment by wangxiaoyou1993** [comment]
Does setting a higher ulimit help?

**Comment by dumim** [comment]
Hi @wangxiaoyou1993 as mentioned in the bug report, the ulimit is set to a hard limit of 65536, which is very large. According to the [mage docs](https://docs.mage.ai/production/configuring-production-settings/overview): `you can set the environment variable ULIMIT_NO_FILE to a larger number (e.g. 8192 or 16384)` and our current value is x4 larger

**Comment by wangxiaoyou1993** [comment]
I see. @dumim do you use the terraform scripts provided by Mage?

**Comment by dumim** [comment]
@wangxiaoyou1993 yes we do https://github.com/mage-ai/mage-ai-terraform-templates

**Comment by wangxiaoyou1993** [comment]
> @wangxiaoyou1993 yes we do https://github.com/mage-ai/mage-ai-terraform-templates

Ok, I'm looking into this issue.

**Comment by wangxiaoyou1993** [comment]
Hey @dumim , can you run `ulimit -n` in your Mage terminal to check the limit?

**Comment by wangxiaoyou1993** [comment]
And you can further increase the limit to 131072.

**Comment by wangxiaoyou1993** [comment]
You can also try upgrading to latest version. The [demo.mage.ai ](https://demo.mage.ai/overview) runs with latest version and limit 32768 without problems

**Comment by dumim** [comment]
Thanks @wangxiaoyou1993 . The terminal cannot be interacted with for some reason... we have `DISABLE_NOTEBOOK_EDIT_ACCESS` set to `0`. Am I doing this wrong, or should I raise a bug request for this?
Thanks we have now deployed v0.9.16 to production. Will report back after we observe the memory for at least 24 hours.

**Comment by dumim** [comment]
@wangxiaoyou1993 from an initial look it seems like the memory is rising again, with no usage from our end
![image](https://github.com/mage-ai/mage-ai/assets/30994223/aa847fdb-b034-4ec1-af30-bff6b24420de)

**Comment by dumim** [comment]
CPU is stable FYI

**Comment by wangxiaoyou1993** [comment]
Thanks for the updates! We're looking into the memory increase issue.

**Comment by dumim** [comment]
@wangxiaoyou1993 
Can confirm that the memory kept rising by itself, until it errored out and the target group restarted it
![image](https://github.com/mage-ai/mage-ai/assets/30994223/8b8acb50-5f1d-490a-afad-8b572b3cfe70)

**Comment by dumim** [comment]
CPU is .5 vCPU and Memory is set to 2GB at the moment FYI

**Comment by dumim** [comment]
@wangxiaoyou1993 Hi, just checking in on this. Aware that this is a complex issue. We are currently from being production-ready due to this. Attached is confirmation that the memory keeps rising until the health checks fail and the target group starts a new task
![image](https://github.com/mage-ai/mage-ai/assets/30994223/a44e19fc-cc70-4c17-ace5-1adccaf64407)

**Comment by wangxiaoyou1993** [comment]
Hi @dumim , it's a bit hard to investigate this issue but we're prioritizing it this week. We'll definitely get it resolved this week. Sorry about the delay.

**Comment by dumim** [comment]
@wangxiaoyou1993 no worries, thanks for the update

**Comment by dumim** [comment]
@wangxiaoyou1993 checking in to see if there is any update on this? We are blocked from going live in production

**Comment by wangxiaoyou1993** [comment]
> @wangxiaoyou1993 checking in to see if there is any update on this? We are blocked from going live in production

Hi @dumim , we suspect the memory leak is from some of the dependency packages. So we upgraded the dependencies and currently doing some testing. Hope to get some results tomorrow.

**Comment by dumim** [comment]
Thanks for the update @wangxiaoyou1993

**Comment by wangxiaoyou1993** [comment]
> Thanks for the update @wangxiaoyou1993

Just to give an update here. We're releasing a fix for this issue tomorrow.

**Comment by dumim** [comment]
Thanks @wangxiaoyou1993 we are looking forward to testing it

**Comment by wangxiaoyou1993** [comment]
@dumim The fix is included in `mageai/mageai:latest`. You can test it.

**Comment by dumim** [comment]
Thanks @wangxiaoyou1993 we will test this and report back

**Comment by dumim** [comment]
@wangxiaoyou1993 can confirm that after a day of letting it run, it is working properly. Thanks so much for the effort on your part to getting this tricky bug fixed!
