### ISSUE TITLE
Database secrets exposed in plaintext

### ISSUE THREAD

**Issue by dumim** [mage-ai/mage-ai#3266]
Hi, we are deploying Mage to production (AWS) using terraform [scripts](https://github.com/mage-ai/mage-ai-terraform-templates). The database connection string is exported as an [environment variable](https://docs.mage.ai/production/configuring-production-settings/overview#postgresql). This exposes the connection string, which includes the username & password, in the task definition and in the terraform state files in plaintext.

We have already implemented a more secure way than the recommended plain text `variable` in Terraform, by using AWS Secrets Manager to store a Terraform-generated random password. But since the environment variable needs to be exported through the TD, this random password is still exposed in the TD and the state.

Is there a feature instead for Mage to read and decode the credentials directly from a given AWS Secrets Manager Secret ARN?
Thanks

**Comment by dumim** [comment]
Hi! Any progress on this? Thanks

**Comment by dumim** [comment]
Looks like the PR need to only check for Secrets Manager if `DB_USER` is not set. Also need to use the AWS SDK to read this + update the documentation.

**Comment by wangxiaoyou1993** [comment]
@dumim FYI, this feature is available in 0.9.20. Doc: https://docs.mage.ai/production/databases/default#get-credentials-from-aws-secret-manager

**Comment by dumim** [comment]
Thanks @dy46  and @wangxiaoyou1993 I will confirm soon as this is tested in production

**Comment by dumim** [comment]
Can confirm this is working. For anyone else looking for the terraform implementation:
1. `random_password` to generate the password
2. Use this for the `aws_db_instance` `password` and for in the `aws_secretsmanager_secret` json
3. Expose the secret's arn to the env vars in the task defnition

Thanks @dy46 @wangxiaoyou1993
