### ISSUE TITLE
Data Integration Pipeline Export to Trino, column names should be double quoted

### ISSUE THREAD

**Issue by sumanshusamarora** [mage-ai/mage-ai#3267]
**Describe the bug**
I am running a postgres to trino delta lake data integration pipeline wherein source table has a column name "table". Create table statement generated by mage is being blocked by trino due to use of restricted keyword table. Error trace below - 

`CREATE TABLE IF NOT EXISTS dev_bronze.table_schema (id BIGINT, created_by_fk BIGINT, changed_by_fk BIGINT, database_id BIGINT, tab_state_id BIGINT, table VARCHAR(255), expanded BOOLEAN, schema VARCHAR(255), changed_on VARCHAR(52), created_on VARCHAR(52), _mage_created_at VARCHAR(52), _mage_updated_at VARCHAR(52))WITH (location = 'abfss://bronze@**************.dfs.core.windows.net/mage/nonprod/supserset/table_schema')`

**To Reproduce**
1. Create a source table with column name "table" into it
2. Create data integration pipeline with destination trino
3. Create pipeline and start sync

**Expected behavior**
Table should be created in destination i..e trino

**Comment by dy46** [comment]
This issue should be resolved
