### ISSUE TITLE
MSSQL Server connection error 

### ISSUE THREAD

**Issue by code-with-roz** [mage-ai/mage-ai#3269]
#### Description

Hi, I'm trying to connect to my mssql server but I'm unable to establish the connection even after modifying the io.congig.yaml file in my demo_project folder. I also tried running the cmd: export MAGE_DATABASE_CONNECTION_URL="mssql+pyodbc://?odbc_connect=DRIVER={ODBC Driver 18 for SQL Server};SERVER=host;DATABASE=dbname;UID=user;PWD=password;ENCRYPT=yes;TrustServerCertificate=yes;" in my terminal, but no success. 

Could you assist?

#### Screenshots
![image](https://github.com/mage-ai/mage-ai/assets/85030845/90ad972a-6635-437f-bb3e-d870796c0d67)

#### Files
- io.congig.yaml
- metadata.yaml

**Comment by wangxiaoyou1993** [comment]
I think your MSSQL Server is using "ODBC Driver 17 for SQL Server". That could be the reason.
Also, `MAGE_DATABASE_CONNECTION_URL` is not used to connect to your mssql server in your block.

**Comment by wangxiaoyou1993** [comment]
ODBC Driver 18 is installed in the docker image by default. https://github.com/mage-ai/mage-ai/blob/master/Dockerfile#L17
If you want to use ODBC Driver 17, you'll need to build a custom docker image and install this driver. I think the driver should be msodbcsql17
