### ISSUE TITLE
Usage of non declared global variables doesn't fail

### ISSUE THREAD

**Issue by ChStark** [mage-ai/mage-ai#3288]
**Describe the bug**
When a SQL block uses a variable that is not defined at a pipeline's level it doesn't fail

**To Reproduce**
1. Create a new pipeline
2. Create a loader block using an imaginary variable like `SELECT * FROM Table WHERE ID = '{{ some_var }}'`
3. See it run without failing because undeclared var

**Expected behavior**
The usage of a non declared variable should fail, because it could lead to undesired behaviors

**Comment by wangxiaoyou1993** [comment]
@ChStark this issue is fixed in version 0.9.30
