### ISSUE TITLE
How to do incremental replication for Postgres/GA/GSC to destination Postgres

### ISSUE THREAD

**Issue by mir1198yusuf** [mage-ai/mage-ai#3308]
Hello All,
Consider a destination postgres database.
1. I want to incrementally replicate from postgres source to postgres destination on schedule of every few hours. By incrementally, i mean there is one replication key column (timestamp) which gets updated whenever any row is updated. I want to replicate only updated rows since last sync and de-duplicate-and-insert them in destination postgres. Since data can be large first time and querying in batches will be heavy, I want to use pg-dump first time & for subsequent times, use batches of 1000-5000 updated rows. Is this possible ?
2. Same I want to do for all GA data every few hours incrementally. Next time the sync should take start date automatically as end date of previous sync. since for GA I am not sure about what data are there, which api to use, how the schema structure will be in destination, can you share some information on this area ? Also, does available existing connectors do this in incremental way and how destination postgres connector decide which schema to use for source GA connector ?

Thanks in advance.

**Comment by wangxiaoyou1993** [comment]
Hi @mir1198yusuf , your first question is a great use case of the data integration pipelines: https://docs.mage.ai/data-integrations/overview
You can use Postgres as source and destination in data integration pipeline, and use your timestamp column as the bookmark column.

**Comment by wangxiaoyou1993** [comment]
GA is also available as a data integration source: https://github.com/mage-ai/mage-ai/blob/master/mage_integrations/mage_integrations/sources/google_analytics/README.md

**Comment by mir1198yusuf** [comment]
@wangxiaoyou1993  thanks for your response

> Hi @mir1198yusuf , your first question is a great use case of the data integration pipelines: https://docs.mage.ai/data-integrations/overview

Can you also please guide me where is the documentation for batch/incremental replication. I can only find for Logical replication.

> GA is also available as a data integration source: https://github.com/mage-ai/mage-ai/blob/master/mage_integrations/mage_integrations/sources/google_analytics/README.md

Can you also guide me what all GA data it will sync and suppose i use postgres destination connector, how it will add there. i mean what will be the destination schema structure for GA source data. Also is this one time connector or this also supports incremental replication.(next sync copies only updated data from last sync and not full entire replication again)

**Comment by wangxiaoyou1993** [comment]
Hi @mir1198yusuf , here is the tutorial for data integration pipeline: https://docs.mage.ai/guides/data-integration-pipeline
It supports full table sync and incremental sync.

For GA, you will be able to select your dimensions and metrics in the Mage UI. It supports both full table sync and incremental sync as well.

**Comment by wangxiaoyou1993** [comment]
Close this issue now. Feel free to reopen it if you have more questions.
