### ISSUE TITLE
mage start [project terminated by signal SIGILL (Illegal instruction)

### ISSUE THREAD

**Issue by kimsanov** [mage-ai/mage-ai#3312]
Path: /community/contact

Hello! Is it possible to somehow make mage.ai work (maybe older version, or setting some ENV variable) if it is showing this error?

**Comment by wangxiaoyou1993** [comment]
Hi @kimsanov , can you share more information?
* Are you running Mage in your local machine or docker? How did you install Mage?
* Which OS are you using?
* What's the stacktrace?

**Comment by wangxiaoyou1993** [comment]
Same with this ticket: https://github.com/mage-ai/mage-ai/issues/2900

**Comment by wangxiaoyou1993** [comment]
Root cause: https://github.com/mage-ai/mage-ai/issues/3775
