### ISSUE TITLE
GitHub links in documentation are broken

### ISSUE THREAD

**Issue by deepyaman** [mage-ai/mage-ai#3379]
**Describe the bug**
If you visit https://docs.mage.ai/design/core-abstractions#pipeline, and click on [example](https://github.com/mage-ai/demo%5Fetl%5Fpipeline/blob/master/pipelines/etl%5Fdemo/metadata.yaml), the link is broken. Using underscores in the link would [fix it](https://github.com/mage-ai/demo_etl_pipeline/blob/master/pipelines/etl_demo/metadata.yaml). This is true throughout this page (and likely others?).

I don't know if the fix is simply to replace `%5F` with `_`, or if there's a bigger issue in how the docs are getting served, and haven't looked into it. But also didn't want to make a PR changing them all to `_`, if that wasn't the issue. :)

**Comment by mattppal** [comment]
Hi @deepyaman, I'm unable to replicate your issue. In fact, even the link you shared above works for me 🤔 

Are you using [Firefox](https://meta.stackexchange.com/questions/16004/link-with-underscore-does-not-work) by any chance?

**Comment by wangxiaoyou1993** [comment]
Close this ticket since the link works. Feel free to reopen it if you still have the issue.

**Comment by deepyaman** [comment]
> Hi @deepyaman, I'm unable to replicate your issue. In fact, even the link you shared above works for me 🤔
> 
> Are you using [Firefox](https://meta.stackexchange.com/questions/16004/link-with-underscore-does-not-work) by any chance?
> 
> ![image](https://user-images.githubusercontent.com/59450879/264109524-35dddbd3-1cdd-427a-8cf2-7b2c71aa41f0.png)

@mattppal @wangxiaoyou1993 Sorry, I forgot about this entirely. I'm using Safari; it seems to work on Chrome.

**Comment by wangxiaoyou1993** [comment]
@mattppal this issue doesn't seem have been resolved. could you follow up with mintlify?

**Comment by mattppal** [comment]
@wangxiaoyou1993 followed up, no response from Mintlify
