### ISSUE TITLE
Warning Message upon starting Mage

### ISSUE THREAD

**Issue by Keimya** [mage-ai/mage-ai#3380]
I installed mage using conda install. The localhost launches when running mage start [project] name but this error is thrown:
"WARNING:traitlets:Message signing is disabled.  This is insecure and not recommended!"
Please advise on what this error means and how to resolve. Thanks!

**Comment by wangxiaoyou1993** [comment]
Hi @Keimya , this is a warning instead of error. You can ignore it.

**Comment by Keimya** [comment]
Hi @wangxiaoyou1993 thanks for your response! Just curious, what is the cause of this warning?

**Comment by wangxiaoyou1993** [comment]
> Hi @wangxiaoyou1993 thanks for your response! Just curious, what is the cause of this warning?

That's the warning from the jupyter_client library that Mage uses as the notebook kernel.
