### ISSUE TITLE
API Trigger doesn't require authentication

### ISSUE THREAD

**Issue by jon-realsights** [mage-ai/mage-ai#3425]
Path: /orchestration/triggers/trigger-pipeline-api

As much as I don't love the api auth model, the new api triggers require NO authentication - which is worse.

**Comment by wangxiaoyou1993** [comment]
Hi @jon-realsights , this API requires the token that's generated by the trigger.

**Comment by wangxiaoyou1993** [comment]
Close this issue now. Feel free to reopen it if you have more questions.
