### ISSUE TITLE
Data loader using SQLAlchemy and dependencies

### ISSUE THREAD

**Issue by Keimya** [mage-ai/mage-ai#3431]
Hello,

I am trying to import a script to the data loader template to pull information from a MySQL database. The script uses SQLAlchemy, so I replaced the template code with the SQLAlchemy syntax for accessing MySQL.

Initially, I received an error that a function must have the data loader decorator, but then I get this error upon adding the decorator to my function to load the database engine: 

"Exception: Block holy_waterfall may be missing upstream dependencies. It expected to have 1 arguments, but only received 0. Confirm that the @data_loader method declaration has the correct number of arguments."

I was finally able to get this to work using a custom template and using the custom decorator, but I have another issue: AttributeError: 'list' object has no attribute 'connect' when connecting to MySQL.

How can I ensure my modules are being loaded properly when using mage ai? I tried to just list "import" and list the necessary modules at the top of the script, but do I need to re-install these when using mage ai.

Thanks.

**Comment by wangxiaoyou1993** [comment]
Hi @Keimya , here is the doc for installing dependencies: https://docs.mage.ai/development/dependencies/requirements

**Comment by wangxiaoyou1993** [comment]
You can check this ticket as well: https://github.com/mage-ai/mage-ai/issues/3512
