### ISSUE TITLE
OpenAI key on demo site

### ISSUE THREAD

**Issue by xssfox** [mage-ai/mage-ai#3471]
The demo site seems to have a valid OpenAI key available https://demo.mage.ai/settings/workspace/preferences

Tested using:
````
curl https://api.openai.com/v1/completions \
-H "Content-Type: application/json" \
-H "Authorization: Bearer KEY FROM THE URL ABOVE" \
-d '{"model": "text-davinci-003", "prompt": "Say this is a test", "temperature": 0, "max_tokens": 7}'
```

**Comment by wangxiaoyou1993** [comment]
Thanks for the reminder! Just removed the key.
We'll add warning to the demo site to not put the credentials.

**Comment by xssfox** [comment]
It might be worth making the API key field non retrievable ? Not sure what the case is with other secrets configured in Mage

**Comment by wangxiaoyou1993** [comment]
> It might be worth making the API key field non retrievable ? Not sure what the case is with other secrets configured in Mage

That's done in this PR: https://github.com/mage-ai/mage-ai/pull/3455
We'll publish a new version which includes this change soon.
