### ISSUE TITLE
Setting non-string global pipeline variable causes pipeline to become inoperable and disappear from the UI.

### ISSUE THREAD

**Issue by nyc-de** [mage-ai/mage-ai#3475]
**Describe the bug**

Using Mage set_global_variable to set an invalid global variable causes pipeline to disappear for UI.  Invalid is an ambiguous term perhaps "not a valid string" is better.

**To Reproduce**

Using the Titanic example pipeline

1. Execute the loader.
2. Put the following code in the Transformer and execute.

```python
from pandas import DataFrame
import math
from mage_ai.data_preparation.variable_manager import set_global_variable.   # import set_global_variable
import uuid    # import uuid

if 'transformer' not in globals():
    from mage_ai.data_preparation.decorators import transformer
if 'test' not in globals():
    from mage_ai.data_preparation.decorators import test

def select_number_columns(df: DataFrame) -> DataFrame:
    return df[['Age', 'Fare', 'Parch', 'Pclass', 'SibSp', 'Survived']]


def fill_missing_values_with_median(df: DataFrame) -> DataFrame:
    for col in df.columns:
        values = sorted(df[col].dropna().tolist())
        median_age = values[math.floor(len(values) / 2)]
        df[[col]] = df[[col]].fillna(median_age)
    return df


@transformer
def transform_df(df: DataFrame, *args, **kwargs) -> DataFrame:
    """
    Template code for a transformer block.

    Add more parameters to this function if this block has multiple parent blocks.
    There should be one parameter for each output variable from each parent block.

    Args:
        df (DataFrame): Data frame from parent block.

    Returns:
        DataFrame: Transformed data frame
    """
    # Specify your transformation logic here

    execution_id = uuid.uuid4()    # instantiate a uuid object

    set_global_variable("example_pipeline", "execution_id", execution_id).   # set global variable with uuid object instead of string

    return fill_missing_values_with_median(select_number_columns(df))


@test
def test_output(df) -> None:
    """
    Template code for testing the output of the block.
    """
    assert df is not None, 'The output is undefined'

```

**Expected behavior**

Test the variable prior to setting and raise error prior to setting the variable.

**Screenshots**

See attachments at the bottom

**Desktop (please complete the following information):**
 - OS: macOS Ventura Version 13.4.1
 - Browser: Chrome Version 116.0.5845.179

**Error message from setting the global variable**
![error message](https://github.com/mage-ai/mage-ai/assets/123569502/6f0b6846-aaea-4d12-bf32-cf1bdb420363)

**Pipeline gone from the UI**
![pipeline disappears from UI](https://github.com/mage-ai/mage-ai/assets/123569502/38cef7d0-f2b9-411c-8ae2-713c586344fa)

**Stack Trace**
![Stack Trace](https://github.com/mage-ai/mage-ai/assets/123569502/17b79865-d5f2-431e-9029-88a8dc118f01)

**Traceback**
![Traceback](https://github.com/mage-ai/mage-ai/assets/123569502/7c66f092-322f-4be3-9c1b-ce44a7e1b672)

**Comment by dy46** [comment]
we added a serialization check when creating the global variable.
