### ISSUE TITLE
Auto install requirements.txt

### ISSUE THREAD

**Issue by davigs** [mage-ai/mage-ai#3512]
Hi guys, I deployed the mage instance to Google cloud run, but whenever a new container is started, mage doesn't run pip install requirements.txt, I used the terraform template to deploy. and this is causing errors in the pipelines. Has anyone ever experienced this?

**Comment by wangxiaoyou1993** [comment]
You need to specify the USER_CODE_PATH environment variable https://docs.mage.ai/development/variables/environment-variables#default-variables

**Comment by davigs** [comment]
Thanks a lot @wangxiaoyou1993
