### ISSUE TITLE
Spark example dockerfile needs to be updated as JDK 11 was removed from Debian 12

### ISSUE THREAD

**Issue by PetarPeychev** [mage-ai/mage-ai#3536]
**Describe the bug**
In the Dockerfile examples for running spark, openjdk11 is being installed, however this was removed from the Debian 12 packages so the image as it stands can't be built. 

**To Reproduce**
Clone the dockerfile at https://github.com/mage-ai/mage-ai/blob/master/integrations/spark/Dockerfile and build it with `docker build -t mage_spark .`
You will get the following error:
`E: Unable to locate package openjdk-11-jdk`

**Expected behavior**
The image builds with JDK 11 and pyspark installed.

**Desktop (please complete the following information):**
 - OS: macOS 13.0.1
 - Version 0.9.23

**Additional context**
I solved it by adding the bullseye repository:
```
# Add Debian Bullseye repository
RUN echo 'deb http://deb.debian.org/debian bullseye main' > /etc/apt/sources.list.d/bullseye.list

# Install OpenJDK 11
RUN apt-get update -y && \
    apt-get install -y openjdk-11-jdk

# Remove Debian Bullseye repository
RUN rm /etc/apt/sources.list.d/bullseye.list
```

**Comment by wangxiaoyou1993** [comment]
We'll update the Dockerfile.
