### ISSUE TITLE
Data integration pipeline from MySQL to Snowflake threw an error

### ISSUE THREAD

**Issue by digit-minhnguyen** [mage-ai/mage-ai#3564]
**This threw me an error while I was trying to run data integration with full table method**

*I use 'use_batch_load: true'*

This is the full logs of this error:

Traceback (most recent call last):

  File "/usr/local/lib/python3.10/site-packages/mage_ai/data_preparation/executors/block_executor.py", line 260, in execute

    result = __execute_with_retry()

  File "/usr/local/lib/python3.10/site-packages/mage_ai/shared/retry.py", line 50, in retry_func

    raise e

  File "/usr/local/lib/python3.10/site-packages/mage_ai/shared/retry.py", line 34, in retry_func

    return func(*args, **kwargs)

  File "/usr/local/lib/python3.10/site-packages/mage_ai/data_preparation/executors/block_executor.py", line 241, in __execute_with_retry

    return self._execute(

  File "/usr/local/lib/python3.10/site-packages/mage_ai/data_preparation/executors/block_executor.py", line 383, in _execute

    result = self.block.execute_sync(

  File "/usr/local/lib/python3.10/site-packages/mage_ai/data_preparation/models/block/__init__.py", line 922, in execute_sync

    raise err

  File "/usr/local/lib/python3.10/site-packages/mage_ai/data_preparation/models/block/__init__.py", line 857, in execute_sync

    output = self.execute_block(

  File "/usr/local/lib/python3.10/site-packages/mage_ai/data_preparation/models/block/__init__.py", line 1095, in execute_block

    outputs = self._execute_block(

  File "/usr/local/lib/python3.10/site-packages/mage_ai/data_preparation/models/block/integration/__init__.py", line 375, in _execute_block

    print_log_from_line(

  File "/usr/local/lib/python3.10/site-packages/mage_ai/data_integrations/logger/utils.py", line 83, in print_log_from_line

    raise Exception(message)

Exception: 2023-09-21T08:10:28 Snowflake process failed with error 001757 (42601): 01af220a-0102-d483-0001-20fa01cbbc3e: SQL compilation error:

Table '*********.PUBLIC."temp_***************"' does not exist. {"error": "001757 (42601): 01af220a-0102-d483-0001-20fa01cbbc3e: SQL compilation error:

Table '*********.PUBLIC.\"temp_***************\"' does not exist", "errors": ["  File \"/usr/local/lib/python3.10/site-packages/mage_integrations/destinations/snowflake/__init__.py\", line 431, in <module>

    main(Snowflake)

", "  File \"/usr/local/lib/python3.10/site-packages/mage_integrations/destinations/sql/base.py\", line 367, in main

    destination.process(sys.stdin.buffer)

", "  File \"/usr/local/lib/python3.10/site-packages/mage_integrations/destinations/base.py\", line 332, in process

    errors=traceback.format_stack(),

"], "message": "Traceback (most recent call last):

  File \"/usr/local/lib/python3.10/site-packages/mage_integrations/destinations/base.py\", line 327, in process

    self._process(input_buffer)

  File \"/usr/local/lib/python3.10/site-packages/mage_integrations/destinations/base.py\", line 453, in _process

    self.__process_batch_set(

  File \"/usr/local/lib/python3.10/site-packages/mage_integrations/destinations/base.py\", line 530, in __process_batch_set

    raise err

  File \"/usr/local/lib/python3.10/site-packages/mage_integrations/destinations/base.py\", line 496, in __process_batch_set

    self.process_record_data(record_data, stream)

  File \"/usr/local/lib/python3.10/site-packages/mage_integrations/destinations/base.py\", line 242, in process_record_data

    self.export_batch_data(batch_data, stream)

  File \"/usr/local/lib/python3.10/site-packages/mage_integrations/destinations/sql/base.py\", line 74, in export_batch_data

    data = self.process_queries(

  File \"/usr/local/lib/python3.10/site-packages/mage_integrations/destinations/snowflake/__init__.py\", line 406, in process_queries

    self.write_dataframe_to_table(df, database, schema, f'temp_{table}')

  File \"/usr/local/lib/python3.10/site-packages/mage_integrations/destinations/snowflake/__init__.py\", line 331, in write_dataframe_to_table

    success, num_chunks, num_rows, output = write_pandas(

  File \"/usr/local/lib/python3.10/site-packages/snowflake/connector/pandas_tools.py\", line 244, in write_pandas

    copy_results = cursor.execute(copy_into_sql, _is_internal=True).fetchall()

  File \"/usr/local/lib/python3.10/site-packages/snowflake/connector/cursor.py\", line 799, in execute

    Error.errorhandler_wrapper(self.connection, self, error_class, errvalue)

  File \"/usr/local/lib/python3.10/site-packages/snowflake/connector/errors.py\", line 276, in errorhandler_wrapper

    handed_over = Error.hand_to_other_handler(

  File \"/usr/local/lib/python3.10/site-packages/snowflake/connector/errors.py\", line 331, in hand_to_other_handler

    cursor.errorhandler(connection, cursor, error_class, error_value)

  File \"/usr/local/lib/python3.10/site-packages/snowflake/connector/errors.py\", line 210, in default_errorhandler

    raise error_class(

snowflake.connector.errors.ProgrammingError: 001757 (42601): 01af220a-0102-d483-0001-20fa01cbbc3e: SQL compilation error:

Table '*********.PUBLIC.\"temp_***************\"' does not exist

", "caller": "Snowflake", "level": "EXCEPTION", "timestamp": 1695283828, "uuid": "fd861b12e99e441eac9c206c1916ee0e", "type": "LOG"}
---------

This returned me an error indicating that there is no table with prefix temp_ exists on Snowflake, but I checked on Snowflake, it still there, and Mage did't recognize that table

**Comment by wangxiaoyou1993** [comment]
@digit-minhnguyen This issue should've been fixed in version 0.9.35. 
https://github.com/mage-ai/mage-ai/pull/3761
