### ISSUE TITLE
 No module named 'dbt'

### ISSUE THREAD

**Issue by Somnathpaul** [mage-ai/mage-ai#3618]
Suddenly showing the error. Installed dbt core but still not working. **Fix this issue as soon as possible.**

**Comment by tommydangerous** [comment]
Can you show the entire stack trace please?

Are you installing via pip or Docker?

**Comment by tommydangerous** [comment]
What version are you on?

**Comment by Somnathpaul** [comment]
Using pip on Google Compute engine. Using the latest version. 

**Errors:** 
usr/local/lib/python3.9/dist-packages/mage_ai/data_preparation/models/block/dbt/dbt_adapter.py: │
│ 6 in <module>                                                                                    │
│                                                                                                  │
│     3 from dataclasses import dataclass                                                          │
│     4 from typing import Any, Dict, Optional, Tuple, Union                                       │
│     5                                                                                            │
│ ❱   6 import dbt.flags as flags                                                                  │
│     7 import pandas as pd                                                                        │
│     8 from dbt.adapters.base import BaseRelation, Credentials                                    │
│     9 from dbt.adapters.factory import (            



Error 2:
 /usr/local/lib/python3.9/dist-packages/mage_ai/data_preparation/models/block/dbt/block.py:14 in  │
│ <module>                                                                                         │
│                                                                                                  │
│    11 from jinja2 import Template                                                                │
│    12                                                                                            │
│    13 from mage_ai.data_preparation.models.block import Block                                    │
│ ❱  14 from mage_ai.data_preparation.models.block.dbt.dbt_adapter import DBTAdapter               │
│    15 from mage_ai.data_preparation.models.block.dbt.dbt_cli import DBTCli                       │
│    16 from mage_ai.data_preparation.models.block.dbt.profiles import Profiles                    │
│    17 from mage_ai.data_preparation.models.block.dbt.project import Project

**Comment by Somnathpaul** [comment]
Using Latest version on Google cloud console with pip3 

errors:  

 /usr/local/lib/python3.9/dist-packages/mage_ai/data_preparation/models/block/dbt/block.py:14 in  │
│ <module>                                                                                         │
│                                                                                                  │
│    11 from jinja2 import Template                                                                │
│    12                                                                                            │
│    13 from mage_ai.data_preparation.models.block import Block                                    │
│ ❱  14 from mage_ai.data_preparation.models.block.dbt.dbt_adapter import DBTAdapter               │
│    15 from mage_ai.data_preparation.models.block.dbt.dbt_cli import DBTCli                       │
│    16 from mage_ai.data_preparation.models.block.dbt.profiles import Profiles                    │
│    17 from mage_ai.data_preparation.models.block.dbt.project import Project    





Error 2: 
 /usr/local/lib/python3.9/dist-packages/mage_ai/data_preparation/models/block/dbt/dbt_adapter.py: │
│ 6 in <module>                                                                                    │
│                                                                                                  │
│     3 from dataclasses import dataclass                                                          │
│     4 from typing import Any, Dict, Optional, Tuple, Union                                       │
│     5                                                                                            │
│ ❱   6 import dbt.flags as flags                                                                  │
│     7 import pandas as pd                                                                        │
│     8 from dbt.adapters.base import BaseRelation, Credentials                                    │
│     9 from dbt.adapters.factory import (

**Comment by wangxiaoyou1993** [comment]
It has been fixed in the latest version https://github.com/mage-ai/mage-ai/pull/3608
