### ISSUE TITLE
Error in cron expression format throws terminal exception only, and not show in the pipeline UI.

### ISSUE THREAD

**Issue by iamsabin** [mage-ai/mage-ai#3639]
**Error in cron expression format throws terminal exception only, and not show in the pipeline UI.**
For an incorrect cron expression, Mage only generates logs in the terminal. It is a main blocker for us when finding the issues.

**To Reproduce**
1. Create code triggers in yaml file
2. Set schedule_interval value to: (1 5 * * *). With the brackets.
3. Save the file
4. You won't be able to see that trigger in "Triggers" section for the pipeline
5. You will see panics in the logs.

**Expected behavior**
Error message indicating that the cron expression is wrong in the UI.

**Screenshots**
![image](https://github.com/mage-ai/mage-ai/assets/16878620/ddaf2040-0e11-4aa3-a6b7-c789b2e0ec5a)

**Desktop (please complete the following information):**
 - OS: [MacOS]
 - Browser [Chrome]
 - Version [17.0.5938.92]

**Additional context**
It would really be helpful to see something in the UI that there is an error in expression or for similar errors. We are using mage in production, and this tends to create quite a few amount of logs.

**Comment by johnson-mage** [comment]
@iamsabin Thanks for reporting. Will look into this.

**Comment by wangxiaoyou1993** [comment]
This issue is fixed in this PR https://github.com/mage-ai/mage-ai/pull/3696 . You can upgrade to latest version to test it.

**Comment by iamsabin** [comment]
Thank you
