### ISSUE TITLE
Terminal unresponsive in Production

### ISSUE THREAD

**Issue by dumim** [mage-ai/mage-ai#3642]
**Describe the bug**
Terminal unresponsive in Production. Commands can be typed in but when pressed enter, they are disappeared with no output. The cursor is as below. 

This is deployed on AWS ECS.

**Screenshots**
![image](https://github.com/mage-ai/mage-ai/assets/30994223/a5bf3447-e314-4f18-8bbb-17c991087451)

**Comment by dumim** [comment]
Can confirm that the `DISABLE_TERMINAL` variable is not set

**Comment by wangxiaoyou1993** [comment]
@dumim How did you deploy Mage? Do you use Nginx?

**Comment by dumim** [comment]
We have deployed Mage in production using an ECS cluster setup as recommended for AWS (using Terraform).

**Comment by wangxiaoyou1993** [comment]
> We have deployed Mage in production using an ECS cluster setup as recommended for AWS (using Terraform). We do not use Nginx

can you check whether your websocket connection has any errors?

**Comment by dumim** [comment]
> > We have deployed Mage in production using an ECS cluster setup as recommended for AWS (using Terraform). We do not use Nginx
> 
> can you check whether your websocket connection has any errors?

They are returned as `finished` wit no response
<img width="1439" alt="image" src="https://github.com/mage-ai/mage-ai/assets/30994223/f7e3789f-3e01-453f-a2c3-7468e3e5e709">

**Comment by wangxiaoyou1993** [comment]
> > > We have deployed Mage in production using an ECS cluster setup as recommended for AWS (using Terraform). We do not use Nginx
> > 
> > 
> > can you check whether your websocket connection has any errors?
> 
> They are returned as `finished` wit no response <img alt="image" width="1439" src="https://user-images.githubusercontent.com/30994223/272116511-f7e3789f-3e01-453f-a2c3-7468e3e5e709.png">

Do you want to join our slack channel? I can help you debug via a slack huddle call. https://www.mage.ai/chat

**Comment by dumim** [comment]
The issue was with the configuration of the Pomerium server that sat in front of Mage for authentication, which was blocking the websocket connections
Had to add `allow_websockets: true` to the policy as per https://github.com/pomerium/pomerium/issues/412
Not a mage issue.
