### ISSUE TITLE
PySpark kernel with EMR cluster displays a restart warning and remains non-functional despite multiple restart attempts."

### ISSUE THREAD

**Issue by ApurvaLokare** [mage-ai/mage-ai#3699]
I am using pyspark kernel attached with EMR cluster. Mage is not functioning on native cloud platform (Aws), it continues to display restart warning. Cluster has been restarted multiple times, but the problem persists.". Also restarted page and kernel many times.

![Screenshot (251)](https://github.com/mage-ai/mage-ai/assets/67950034/4fa82378-4b61-4132-9aff-cddcdcd0bf68)

![Screenshot (246)](https://github.com/mage-ai/mage-ai/assets/67950034/b397f6e8-fc1d-4233-8e0a-438f38d94d24)

![Screenshot (243)](https://github.com/mage-ai/mage-ai/assets/67950034/433a903f-b5e8-440d-a66f-e94c8c4b5be5)

**Comment by wangxiaoyou1993** [comment]
We're looking into this issue

**Comment by wangxiaoyou1993** [comment]
I think that's the network connectivity issue. Make sure you whitelist ECS task's security group or IP with port 8998 in your EMR's security group

**Comment by wangxiaoyou1993** [comment]
Add debug instruction in the doc: https://docs.mage.ai/integrations/spark-pyspark#7-debugging
