### ISSUE TITLE
DBT models are evaluated/build/run before a condition on the dbt block is evaluated to true

### ISSUE THREAD

**Issue by jamesking-github** [mage-ai/mage-ai#3702]
**Describe the bug**
Pipelines fail if there is an issue with dbt model in a block that should not run because a condition on the block evaluates to false

**To Reproduce**
1. Create a pipeline with a data loader leading to a dbt model
2. add a condition to the dbt model to always evaluate to false
3. Make an error in the dbt model such as the one described in https://github.com/mage-ai/mage-ai/issues/3701
4. See the pipeline errors due to the dbt model that should not be run

**Expected behavior**
In 0.9.27 the dbt model was not executed and therefore the pipeline did not fail

**Screenshots**

**Desktop (please complete the following information):**
N/A

**Smartphone (please complete the following information):**
N/A

**Additional context**

**Comment by wangxiaoyou1993** [comment]
Working on this ticket.
