### ISSUE TITLE
Version the chart and dashboard

### ISSUE THREAD

**Issue by iamsabin** [mage-ai/mage-ai#3754]
**Charts that are made locally do not have the feature to commit to the Git**
It would be nice to have charts info saved and committed in Git. Just like how you guys did with triggers.

**Save charts in dashboard to Git**
Able to commit and push changes that you have made in charts (not the coding in the chart itself). This would include all the charts that you have in the dashboard.

**Create charts in both local environment and production**
It can be a bit time consuming when you create the same chart both locally and in other environments.

**Comment by wangxiaoyou1993** [comment]
Hi @iamsabin , by default, the dashboard data is stored in `.presenters` folder in the data directory.
If you want to include the dashboard data in your git repository. you can specify the custom directory in the environment variable `MAGE_PRESENTERS_DIRECTORY`

**Comment by wangxiaoyou1993** [comment]
Close this ticket since it's answered. Feel free to reopen if you have more questions.

**Comment by iamsabin** [comment]
thanks @wangxiaoyou1993

Although creating charts seem to have moved from global dashboard to pipelines, it did work for me on an earlier vesion.
