### ISSUE TITLE
Snowflake Data Export Bug

### ISSUE THREAD

**Issue by ethanbailie** [mage-ai/mage-ai#3755]
**Describe the bug**
When exporting to Snowflake via the data exporter block, there is an error which causes the block to fail.
This appears to be caused by a missing library (libcrypto)

**To Reproduce**
1. Create a data exporter block
2. Set valid credentials
3. Attempt to run the block with a valid data frame as the input

**Expected behavior**
Expected to have the block successfully run and write to the table within Snowflake

**Screenshots**
![image](https://github.com/mage-ai/mage-ai/assets/6435416/6edcf846-d3ed-47ac-88d3-462aeadad2a7)

**Desktop (please complete the following information):**
 - OS: Mac OS
 - Browser: Chrome
 - Version: Ventura 13.4.1

**Additional context**
Only occurs on 0.9.34, when rolled back to 0.9.32 the error does not occur. These pipelines that failed were already running in prod with no issues until updated to 0.9.34

**Comment by wangxiaoyou1993** [comment]
It's an issue from the oscrypto library https://github.com/wbond/oscrypto/issues/78
Related Snowflake post: https://community.snowflake.com/s/question/0D5Do000010NAVzKAO/hi-snowflake-teami-am-facing-issues-while-connecting-to-snowflake-using-snowflake-connector-with-oscryptoerrorslibrarynotfounderror-error-detecting-the-version-of-libcrypto
We'll include a fix for this issue in the newer version.
