### ISSUE TITLE
pip install mage-ai error (windows 11)

### ISSUE THREAD

**Issue by danielcaz2200** [mage-ai/mage-ai#3762]
I keep getting this error when running pip install mage-ai:

 Getting requirements to build wheel did not run successfully.
  │ exit code: 1
  ╰─> [9 lines of output]
      C:\Users\username\AppData\Local\Temp\pip-build-env-__8ts6sd\overlay\Lib\site-packages\setuptools\_distutils\dist.py:265: UserWarning: Unknown distribution option: 'cffi_modules'
        warnings.warn(msg)
      running egg_info
      writing pyzmq.egg-info\PKG-INFO
      writing dependency_links to pyzmq.egg-info\dependency_links.txt
      writing requirements to pyzmq.egg-info\requires.txt
      writing top-level names to pyzmq.egg-info\top_level.txt
      running configure
      error: Microsoft Visual C++ 14.0 or greater is required. Get it with "Microsoft C++ Build Tools": https://visualstudio.microsoft.com/visual-cpp-build-tools/
      [end of output]

After installing Visual C++, I now get this error:

 -- Running CMake for PyArrow C++
      cmake -DARROW_BUILD_DIR=build -DCMAKE_BUILD_TYPE=release -DCMAKE_INSTALL_LIBDIR=lib -DCMAKE_INSTALL_PREFIX=C:\Users\dcazarez\AppData\Local\Temp\pip-install-no6a91rs\pyarrow_25fbc1ee20ee455a92f6955e1bfe137f\build\dist -DPYTHON_EXECUTABLE=C:\Users\dcazarez\AppData\Local\Programs\Python\Python312\python.exe -DPython3_EXECUTABLE=C:\Users\dcazarez\AppData\Local\Programs\Python\Python312\python.exe -DPYARROW_CXXFLAGS= -DPYARROW_WITH_DATASET=off -DPYARROW_WITH_PARQUET_ENCRYPTION=off -DPYARROW_WITH_HDFS=off -DPYARROW_WITH_FLIGHT=off -G "Visual Studio 15 2017 Win64" C:\Users\dcazarez\AppData\Local\Temp\pip-install-no6a91rs\pyarrow_25fbc1ee20ee455a92f6955e1bfe137f\pyarrow/src
      error: command 'cmake' failed: None
      [end of output]

  note: This error originates from a subprocess, and is likely not a problem with pip.
  ERROR: Failed building wheel for pyarrow
  Building wheel for tornado (setup.py) ... done
  Created wheel for tornado: filename=tornado-6.1-cp312-cp312-win_amd64.whl size=419576 sha256=b25ebc0ea01e6686bd7231e3a84a1f988072d25a9a9ea73962414fd7dff11b41
  Stored in directory: c:\users\dcazarez\appdata\local\pip\cache\wheels\38\ba\89\c3c5a1ec85a3aa58099c8c1ba24fa7a54eaec302931798e016

does anyone know how to help please?

**Comment by edmondwinston** [comment]
Hi @danielcaz2200.

Some Python packages take for granted quite a few core functionalities that are not available on Windows, so you need to install their prebuilds, see the fantastic (but archived) [pipwin](https://github.com/lepisma/pipwin) and [this issue](https://github.com/lepisma/pipwin/issues/64) for more options.

**Comment by mlamagna1** [comment]
@danielcaz2200 - Hello - I ran into this issue recently as well installing with python 3.12 and having build tools installed already. I was able to get mage up and running by rolling back to python 3.11.

**Comment by danielcaz2200** [comment]
> @danielcaz2200 - Hello - I ran into this issue recently as well installing with python 3.12 and having build tools installed already. I was able to get mage up and running by rolling back to python 3.11.

Hey rolling back to an earlier Python version seemed to work! I believe it's because PyArrow does not have a corresponding wheel yet for python 3.12.
