### ISSUE TITLE
DISABLE_NOTEBOOK_EDIT_ACCESS environment variable not working

### ISSUE THREAD

**Issue by aggelito** [mage-ai/mage-ai#3793]
**Describe the bug**
When setting the DISABLE_NOTEBOOK_EDIT_ACCESS to 1, the platform still lets you edit pipelines in the editor.

**To Reproduce**
1. Set DISABLE_NOTEBOOK_EDIT_ACCESS environment variable to 1
2. Restart with docker compose up -d
3. Try and edit a pipeline

**Expected behavior**
Mage shouldn't allow to edit pipelines in the browser

**Environment:**
- Ubuntu 22
- Docker version 23.0.4
- Docker Compose version v2.17.2

**Additional context**
When downgrading to a previous version (0.9.32 in my case since that's what i used before it stopped working) it works.

I can see a new release is on the way but don't know if it contains a fix for this. Will try when the docker is finished building :)

**Comment by stickeraugust** [comment]
tried with latest, still not working

**Comment by aggelito** [comment]
tried with latest version (0.9.36), still not working

**Comment by dy46** [comment]
thanks for reporting this. we'll take a look

**Comment by aggelito** [comment]
hello again! i noticed this issue has been resolved <3

**Comment by dy46** [comment]
@aggelito was just about to let you know, but seems like you found out on your own 😅

**Comment by aggelito** [comment]
> @aggelito was just about to let you know, but seems like you found out on your own 😅

haha i've been waiting! recently discovered mage and we really like it. so thank you, great work :clap:
