### ISSUE TITLE
Blocks depending from reduced blocks won't start anymore

### ISSUE THREAD

**Issue by gabrieleiacono** [mage-ai/mage-ai#3794]
**Describe the bug**
Starting from v0.9.35, all blocks depending from dynamic children with the reduced output flag turned on, won't start even when their starting conditions are all verified.

The bug is not present in v0.9.34 and older.

**To Reproduce**
1. Create a standard pipeline with dynamic blocks just like the one described in the [docs](https://docs.mage.ai/design/blocks/dynamic-blocks)
2. Turn on the Reduced Output option for the second block
3. Trigger once the pipeline
4. Watch it getting stuck after the first four blocks (dynamic block + 3 dynamic children), the last block stays in status `initial`

**Expected behavior**
The output of the dynamic children gets reduced and passed to the next block, that gets scheduled correctly accordingly to its dependencies

**Screenshots**
![image](https://github.com/mage-ai/mage-ai/assets/18249872/4b8ae2d5-760c-4e0d-aae6-beca52090ee4)

**Environment**
 - ECS mage instance deployed using the official terraform scripts
- Reproduced on v0.9.35 and v0.9.36

**Comment by wangxiaoyou1993** [comment]
It's fixed in this PR: https://github.com/mage-ai/mage-ai/pull/3847
Will include it in the upcoming version

**Comment by vramirezgalleria** [comment]
Good morning @wangxiaoyou1993 . Is this fix already live? If not, what's the ETA?
Thanks

**Comment by wangxiaoyou1993** [comment]
> Good morning @wangxiaoyou1993 . Is this fix already live? If not, what's the ETA? Thanks

We'll publish a new version tomorrow

**Comment by wangxiaoyou1993** [comment]
This issue has been fixed in version 0.9.41
