### ISSUE TITLE
No Slack notification for failed pipeline

### ISSUE THREAD

**Issue by hanslemm** [mage-ai/mage-ai#3802]
**Describe the bug**
When a pipeline fail due to `Fail to initialize block runs`, it does not send a notification in Slack.

**To Reproduce**
1. Create an integration pipeline that has a `psycopg2.errors.InsufficientPrivilege: permission denied for table` error in the loading block.
2. Have a Slack notification set up.

**Expected behavior**
To send me a notification when a pipeline fails, regardless of the error.

**Screenshots**
![image](https://github.com/mage-ai/mage-ai/assets/32077629/0447cf77-99a7-40b0-bb3e-6943d77c8719)

**System**
 - OS: running on k8s, I added my Mage project to the Mage official image and created a versioned custom image.
 - Browser : Chrome
 - Version: now at 0.9.36 - but I can observe that since I created this pipeline I have the issue (perhaps since 0.9.32).

**Comment by hanslemm** [comment]
@mattppal

**Comment by mattppal** [comment]
Thanks @hanslemm :)
