### ISSUE TITLE
Suggestion: Swap out the quick start text in the README for a hyperlink to the docs

### ISSUE THREAD

**Issue by Andrew-S-Rosen** [mage-ai/mage-ai#3822]
The [quick start](https://github.com/mage-ai/mage-ai#%EF%B8%8F-quick-start) section in the docs initially confused me because I am on Windows, and the commands are specifically for Mac/Linux (but it does not specify this). After some struggling, I then opened the documentation and found the [much more helpful](https://docs.mage.ai/getting-started/setup#get-mage) "get mage" setup instructions, which clarified everything for me.

Since the official documentation is so nice, perhaps it would be better to simply hyperlink to it in the README instead?

**Comment by mattppal** [comment]
@Andrew-S-Rosen Thanks! I like this idea. Here's a PR to do just that: https://github.com/mage-ai/mage-ai/pull/3934
