### ISSUE TITLE
Oracle data integration pipelines fail when protected names are used

### ISSUE THREAD

**Issue by mattppal** [mage-ai/mage-ai#3858]
Using quotes _should_ escape protected phrases, but Oracle DI pipelines unexpectedly fail.

https://mageai.slack.com/archives/C05T5RVPP40/p1698346851745829

> I have an issue with Oracle Data Integration pipeline. I want to grab data from the "RAW" schema. But afaik RAW is a reserved keyword in oracle, so when I run a query I need to use " for the schema. e.g. select * from "RAW".sometable otherwise if I select * from RAW.sometable I get an error about invalid table name. Can we have a list of reserved keywords that should be quoted? I see debezium and airbyte somehow handling this.

**Comment by wangxiaoyou1993** [comment]
There's no follow up on this issue. 
Feel free to reopen the ticket if the issue still exists.
