### ISSUE TITLE
Manage different projects with one entry point

### ISSUE THREAD

**Issue by kreopt** [mage-ai/mage-ai#3860]
Hi! We're have different independent integration processes developed by different teams. What we'd like to have is centralized ability to run and schedule pipelines from these projects. 

As I see according to current architecture there is only way to manage multiple pipelines from one project at one entry point (=http port) so there are two possible ways to manage our processes:
1. host each independent project on different ports and somehow route to desired one (this is not very convenient cause you should either know project name to type it in address bar manually or write own web page to route to these projects)
2. mix all processes in one project and manage only pipelines (this is not very good cause different teams should use one repository and project once will became like big garbage dump)

I see a possible minimal solution as simple ability to switch project using dropdown list at top level breadcrumb. This can be done by simply get all projects from specified folder while starting management frontend

**Comment by wangxiaoyou1993** [comment]
Hey @kreopt , you can check the "workspace management" feature: https://docs.mage.ai/production/developing-in-the-cloud/workspaces/overview

**Comment by kreopt** [comment]
Looks like what we want. Missed that. Thanks!
