### ISSUE TITLE
API source support  csv from application/gzip

### ISSUE THREAD

**Issue by mosenturm** [mage-ai/mage-ai#3900]
I have a lot of API sources which are from type `application/gzip` or `application/x-gzip` and contains `csv` files. Is there a way to integrate these mime type into API source?

**Comment by wangxiaoyou1993** [comment]
@mosenturm Could you remind me when you need this feature by?

**Comment by wangxiaoyou1993** [comment]
@mosenturm is this feature still urgent for you?

**Comment by mosenturm** [comment]
Put it on the roadmap till end of the year.
