### ISSUE TITLE
Use a global or environment variable to dbt command

### ISSUE THREAD

**Issue by csauge** [mage-ai/mage-ai#3920]
**Is your feature request related to a problem? Please describe.**
I cannot use the same dbt block for all pipelines

**Describe the solution you'd like**
Use a global or environment variable in the generic dbt command for --select option to select only a specific model and not all models. Ex: dbt run --select ${DBT_MODEL}.*

**Describe alternatives you've considered**
Create different blocks one for each dbt command 

**Additional context**
No

**Comment by wangxiaoyou1993** [comment]
This feature is added in this PR: https://github.com/mage-ai/mage-ai/pull/3945
Doc: https://docs.mage.ai/dbt/run-selected-model#variables-2
The feature is available in version 0.9.44.
