### ISSUE TITLE
Can't Update Backfill Variable using Update API

### ISSUE THREAD

**Issue by fajrifernanda** [mage-ai/mage-ai#3928]
**Describe the bug**
this docs https://docs.mage.ai/api-reference/backfills/update-backfill says i can update backfill variable using api

**To Reproduce**
hit api:  PUT /api/pipelines/:pipeline_uuid/backfills/:backfill_id
using variables on the body, and it didn't update the variables

**Expected behavior**
the variables should be updated

**Screenshots**
![Screenshot 2023-11-07 at 16 44 53](https://github.com/mage-ai/mage-ai/assets/26200571/ee9c84da-a643-4c5e-86f3-df9998c6ba29)

**Comment by fajrifernanda** [comment]
the ALLOWED_PAYLOAD_KEYS  on this file https://github.com/mage-ai/mage-ai/blob/master/mage_ai/api/resources/BackfillResource.py does not include `variables`

**Comment by johnson-mage** [comment]
@fajrifernanda Thanks for bringing this to our attention. Will look into this.
