### ISSUE TITLE
Side view not working properly when folding every blocks except one

### ISSUE THREAD

**Issue by KyllianBeguin** [mage-ai/mage-ai#3947]
**Describe the bug**
Data view when choosing the side view does not display properly when folding every blocks except one.

**To Reproduce**
1. Go to your pipeline
2. Click on `side view`
3. Click on `Files in pipeline`
4. Hide every block except one

**Expected behavior**
Data should appear next to the corresponding block

**Screenshots**
![image](https://github.com/mage-ai/mage-ai/assets/50613619/da53d04b-aa3b-4630-82bf-5c5fc8581e97)

**Desktop (please complete the following information):**
 - OS: Debian GNU/Linux 12 (bookworm)
 - Browser: Firefox
 - Version 0.9.43

**Smartphone (please complete the following information):**

**Additional context**

**Comment by wangxiaoyou1993** [comment]
@tommydangerous could you take a look?

**Comment by tommydangerous** [comment]
On it!

**Comment by tommydangerous** [comment]
Fix: https://github.com/mage-ai/mage-ai/pull/4005

**Comment by tommydangerous** [comment]
Fixed!
