### ISSUE TITLE
Data Integration: Conversion errors

### ISSUE THREAD

**Issue by joshpachner** [mage-ai/mage-ai#3958]
**Describe the bug**
when pulling in data from postgres to snowflake, the stream will fail due to a pyarrow conversion. The attempted conversion is on a value within a JSON object. 

**To Reproduce**
A postgres database that has a JSON column, and the json structure is not consistent. 

**Expected behavior**
I would expect it to just retain that its JSON/Variant and load it into the destination. Without doing a full scan on the json key and values. 

Another thing i would expect, is that if i set the type to "string". That it would be the catch-all safe way to load date from one source to another. Since it should just then take the JSON and string-it, and then load that string into the destination. No fancy checking required.  (This would also hopefully solve the other issue I'm seeing with the postgres DB having a date of "25232-10-10", which then throws a year 25232 is not in range., when trying to load it.)

**Screenshots**
<img width="379" alt="image" src="https://github.com/mage-ai/mage-ai/assets/65133879/0b7696f0-1502-45c7-adda-1f6aeae18760">

**Additional context**

My slack msg below
What im seeing
```
(\"Could not convert '25%' with type str: tried to convert to double\", 'Conversion failed for column RECENTDATA with type object')
that field is "JSON" in postgress, and the configuration does see it as an object...
```
'Conversion failed for column RECENTDATA with type object')", "errors": ["  File \"/usr/local/lib/python3.10/site-packages/mage_integrations/destinations/snowflake/__init__.py\
looks like in the destination portion
 File \"pyarrow/array.pxi\", line 316, in pyarrow.lib.array

  File \"pyarrow/array.pxi\", line 83, in pyarrow.lib._ndarray_to_array

  File \"pyarrow/error.pxi\", line 100, in pyarrow.lib.check_status

pyarrow.lib.ArrowInvalid:
something about pyarrow tryna check the types within the object?
[this is what the object looks like
`{"reportSafeleaseUnits":0,"reportAttachRate":"0%","reportAutoEnrollEligibleRevenue":0,"reportAutoEnrollInitialRevenue":null,"reportSafeleaseRevenue":0,"reportDelinquentUnits":0,"reportOccupiedUnits":0,"reportRevenueSharePercent":"100%","reportAutoEnrollEligibleUnits":null,"reportMoveOutUnits":0,"reportTotalMonthlyRevenue":0,"reportCustomerRevenue":0,"emailSentAt":null,"eligible":0}`
[another sample
`{"reportSafeleaseUnits":3,"reportAttachRate":"5%","reportAutoEnrollEligibleRevenue":54900,"reportAutoEnrollInitialRevenue":null,"reportSafeleaseRevenue":900,"reportDelinquentUnits":1,"reportOccupiedUnits":66,"reportRevenueSharePercent":25,"reportAutoEnrollEligibleUnits":61,"reportMoveOutUnits":0,"reportTotalMonthlyRevenue":3600,"reportCustomerRevenue":2700,"reportTotalCoverage":200000,"emailSentAt":null,"eligible":61,"reportTotalAutoEnrollEligibleRevenue":58500,"reportRevenue":3600,"reportUninsurableUnits":0,"reportPrivatePolicies":1}`

**Comment by joshpachner** [comment]
This is mission critical for me, since the JSON field contains information that I do need in my snowflake(Snowflake handles the JSON fine, (its already in my snowflake but replicated via stitch)). So I can't just not replicate that field.

**Comment by joshpachner** [comment]
If you notice in the JSON examples.
The "reportRevenueSharePercent" is  "100%" and then the other is "25".
So pyarrow thinks all reportRevenueSharePercent should be an number, and thus tries to convert the 100% to number.

(I'm not responsible for generating the data. Whatever dev that is being inconsistent with their json structure should never code again)

**Comment by joshpachner** [comment]
Im not sure where in all the mage_integration code that this is happening, but something like this might be what's causing it 

`import pandas as pd
import pyarrow as  pa
df = pd.DataFrame({"c0": [{"bugs":"25%"}, {"bugs":100}]})
print(df)
schema = pa.Schema.from_pandas(df=df[["c0"]])`


maybe like a pyarrow read of a parquet? or pandas df to pyarrow schema?

**Comment by joshpachner** [comment]
Ok doing more research on this. a way to get around this is if setting pyarrow's safe to False.
However, i couldn't figure out how to do that. Bard AI was no help 🙄 

Once i switched the engine from 'pyarrow' to 'fastparquet', it worked no issue

```
df = pd.DataFrame({"c0": [{"bugs":"25%"}, {"bugs":100}]}) 
df.to_parquet('ee',engine= 'pyarrow')
# fails
df.to_parquet('ee', engine='fastparquet')

```

Sooo maybe thats something to consider... 🤷‍♂️

**Comment by joshpachner** [comment]
Update on my one comment 

>  (This would also hopefully solve the other issue I'm seeing with the postgres DB having a date of "25232-10-10", which then throws a year 25232 is not in range., when trying to load it.)

This appears to be a python datetime issue. 
`datetime.datetime(25323,1,1)`
Throws the error of "Year out of range".

But ideally if i was setting the source type as "string", mage ideally would not try to convert it to a datetime... so issue would still be resolved by allowing a string set. 

Just now checked. and it appears if the json is stringified then pyarrow won't throw the error for the JSON object

**Comment by pachnerEncor** [comment]
Ok im noticing something else. i might be absolutely confused here. BUT. im not seeing how "disable_column_type_check" is associated to a stream.

Which i dont know what this is doing, but it seems important and possibly something happening where the disable_column_type_check is never actually being able to set to True.

screenshot is of file mage_integrations/sources/base.py

![image](https://github.com/mage-ai/mage-ai/assets/135995237/c6227189-b3ea-4220-b09b-cabfcabac022)

**Comment by pachnerEncor** [comment]
and then there's something in the singer docs about this type conformance stuff

![image](https://github.com/mage-ai/mage-ai/assets/135995237/28e32350-fd59-4ac3-8768-d1c72f797c02)

**Comment by joshpachner** [comment]
Bard is saying that singer by default has it set to strict.

So maybe thats the issue?? Singer's underlying code is checking the types of the JSON records and thats why its throwing those errors, because in the mage_integrations code its not actually toggling to "None", or "Lax" or whatever it is suppose to be.  🤷 

<img width="738" alt="image" src="https://github.com/mage-ai/mage-ai/assets/65133879/d6cd813e-2b4b-41d2-bd74-d5b16d1b1fe5">

**Comment by joshpachner** [comment]
@pachnerEncor  what an effing roller coaster of emotions we've been on today, huh?

**Comment by wangxiaoyou1993** [comment]
That's an error of the snowflake's library's `write_pandas` method. https://docs.snowflake.com/en/developer-guide/python-connector/python-connector-api#write_pandas
