### ISSUE TITLE
I can't connect MySQL that requires ssh

### ISSUE THREAD

**Issue by Jgerardopine** [mage-ai/mage-ai#3964]
**Describe the bug**
When trying to use the integrations or the MYSQL data loader, I can't connect to MySQL DB. However, when I use the normal Python code in a transformer code, it works fine

**To Reproduce**
1. Go to Main page
2. Click on 'NEW'
3. Select 'Data Integration'
4. Select MySQL from the 'Select source' dropdown
5. There are no SSH variable options.
6. Add the  variables for ssh_username, ssh_pwd, ssh_pkey
7. Click on 'Test' connection
8. See error: Database error 2003 

Same when using the io_config.yaml and using the MySQL Data Loader connector. 

**Expected behavior**
Conneciton  established

**Desktop (please complete the following information):**
 - OS: Docker container using Windows Docker desktop
 - Browser : Chrome 
 - Version  119.0.6045.124 

**Additional context**
No existing documentation on Mage's site when ssh tunnel is required on MySQL

**Comment by wangxiaoyou1993** [comment]
You also need `connection_method`, `ssh_host` and `ssh_port` variable. Please follow the doc: https://github.com/mage-ai/mage-ai/blob/master/mage_integrations/mage_integrations/sources/mysql/README.md

**Comment by wangxiaoyou1993** [comment]
@Jgerardopine does this doc help you^

> You also need `connection_method`, `ssh_host` and `ssh_port` variable. Please follow the doc: https://github.com/mage-ai/mage-ai/blob/master/mage_integrations/mage_integrations/sources/mysql/README.md

@Jgerardopine does this doc help you^

**Comment by Jgerardopine** [comment]
I will test it later today or tomorrow as there is some maintenance in our DBs and I can't test it today. I'll get back to you as soon as I test it.

**Comment by wangxiaoyou1993** [comment]
Hi @Jgerardopine , following up on this issue, have you got the chance to test the configs?

**Comment by wangxiaoyou1993** [comment]
Hi @Jgerardopine , have you got the change to test it?

**Comment by wangxiaoyou1993** [comment]
Close this issue now. Feel free to reopen if you still can't connect.
