### ISSUE TITLE
An option in s3 destination to lower the case for columns

### ISSUE THREAD

**Issue by PrincipalJohnShepherd** [mage-ai/mage-ai#3977]
When using Data Integrations to move data from sql to S3 as parquet. Make an option to lower case the column names when uploading the parquet file.
I tried a transformer but it takes for ever with batches of 3m rows.

**Comment by PrincipalJohnShepherd** [comment]
Any ideas on when this enhancement could go live?

**Comment by PrincipalJohnShepherd** [comment]
maybe add support for json and gz. That should lower case column names

**Comment by dy46** [comment]
hey @PrincipalJohnShepherd i'll be working on this in the upcoming week
