### ISSUE TITLE
No permission for admin after changed password

### ISSUE THREAD

**Issue by KyllianBeguin** [mage-ai/mage-ai#3987]
**Describe the bug**
After changing the password for admin, I can log in but Mage day that the user doesn't have any permission

**To Reproduce**
1. Log in as admin with basci credential
2. Go to user profile
3. Change password
4. Log out
5. Log in

**Expected behavior**
Permissions stay the same

**Screenshots**
![ErrorMageNoPermissionAfterAdminPasswordChanges](https://github.com/mage-ai/mage-ai/assets/50613619/f5753f75-fb41-4ba8-85f3-a8e87b64a3d6)

**Desktop (please complete the following information):**
 - OS: Debian GNU/Linux 12 (bookworm)
 - Browser Firefox
 - Version 0.9.43

**Additional context**
None

**Comment by wangxiaoyou1993** [comment]
@KyllianBeguin can you try version 0.9.45 and see whether you still can reproduce the issue?

**Comment by wangxiaoyou1993** [comment]
I think it's fixed in this PR: https://github.com/mage-ai/mage-ai/pull/3982
