### ISSUE TITLE
Cannot more than three connections to a block

### ISSUE THREAD

**Issue by KyllianBeguin** [mage-ai/mage-ai#3989]
**Describe the bug**
When adding a fourth connection to a block, the third switch from previous to other block

**To Reproduce**
1. Pick a block with 3 connections
2. Select a block not connected to the 3-connections one
3. Drag and drop a link from block to 3-connections block

**Expected behavior**
Add more than 3 connections

**Screenshots**
![ErrorMageNoMoreThanThreeConnexions](https://github.com/mage-ai/mage-ai/assets/50613619/0a57095f-7cf6-4693-b30e-1f2298dfe348)

**Desktop (please complete the following information):**
 - OS: Debian GNU/Linux 12 (bookworm)
 - Browser Firefox
 - Version 0.9.43

**Additional context**
None

**Comment by KyllianBeguin** [comment]
Seems that droping inside the box actually allow the fourth connection
![ErrorMagenoMoreThanThreeConnexions-CaseOK](https://github.com/mage-ai/mage-ai/assets/50613619/c0e856fd-8c74-4976-a8cd-2ecc038078d2)

**Comment by johnson-mage** [comment]
@KyllianBeguin Yeah, the connecting line from a block should be placed on the block itself, rather than the port that appears when hovering over a block in the dependency graph. But this is still helpful to know so we can improve the UX for the dep graph.
