### ISSUE TITLE
Add another check to re-enqueue the job if it’s not enqueued/dequeued correctly

### ISSUE THREAD

**Issue by PrincipalJohnShepherd** [mage-ai/mage-ai#3998]
Pipeline blocks are stuck on queued. 

These are screen shots of different block on different pipelines on different days
![image](https://github.com/mage-ai/mage-ai/assets/119837673/5606fd1c-9272-4a8b-87db-6872b8650134)
![image (21)](https://github.com/mage-ai/mage-ai/assets/119837673/4a4c1787-d3a6-4383-8961-42d430a4d38c)
![image (22)](https://github.com/mage-ai/mage-ai/assets/119837673/1428c4bd-7911-4904-b149-221e32d2fa4f)

**Comment by wangxiaoyou1993** [comment]
will include it in version 0.9.46

**Comment by wangxiaoyou1993** [comment]
This enhancement has been released
