### ISSUE TITLE
Issue on docs

### ISSUE THREAD

**Issue by slamer59** [mage-ai/mage-ai#3999]
Path: /design/blocks/extension

A full exemple to be more explicit would help to understand how to extend capabilities.

**Comment by mattppal** [comment]
@slamer59 Thanks for opening the issue! Could you elaborate on what's missing from the current example?

https://docs.mage.ai/design/blocks/extension#example

**Comment by wangxiaoyou1993** [comment]
Close this issue since there's no followup. Feel free to reopen it if you want to follow up on this ticket.
