### ISSUE TITLE
K8S block runs not working as expected

### ISSUE THREAD

**Issue by khalit23** [mage-ai/mage-ai#4033]
**Describe the bug**
Mage offers the option of running a k8s executor for pipeline runs. This feature works and will create a new k8s pod that the job can run in. However, mage also allows you to specify block level executors. When specifying the block level executor as k8s, I am experiencing that a new pod is not created and the block is not run in k8s. Instead it is still using the local python executor. I have specified the executor as k8s in the block component of the pipeline's metadata.yaml as well as specifying extra k8s configuration in the projects metadata.yaml (see the attached screenshot below). I'd also like to add that I have deployed the web server as it's own pod and the scheduler as another pod. So I have not deployed them together in a single container. It seems as though instead of using a k8s executor, it is using a local python executor within the mage web pod.

**To Reproduce**
1. Create a cluster
2. Deploy Mage on cluster with a web server pod and scheduler pod (see screenshot below)
3. Create pipeline with multi-blocks
4. Specify the block level executor as k8s and attempt to run only one block from the pipeline

**Expected behavior**
A new pod is created in k8s in which the block is executed and the local python executor isn't used. Similar behaviour to running a pipeline using k8s executor.

**Screenshots**
![image](https://github.com/mage-ai/mage-ai/assets/103213383/e081a9d7-209d-4289-a62d-a70f2aa6d77d)
![image](https://github.com/mage-ai/mage-ai/assets/103213383/3b4abece-6f88-4219-a118-5389abdb3e46)
![image](https://github.com/mage-ai/mage-ai/assets/103213383/fd25d7ce-02ba-468c-abfe-a0014c3ce802)
![image](https://github.com/mage-ai/mage-ai/assets/103213383/d9c93123-924f-4d84-8fe8-ce29c996c309)

**Comment by wangxiaoyou1993** [comment]
@khalit23 do you run the block in the notebook or do you run it through triggers?

**Comment by khalit23** [comment]
When running through triggers the executor works as expected. It creates a k8s job which in turn creates a pod where the pipeline is executed. However, when running a block through the notebook and specifying k8s as the block executor, then the behavior is not as expected.

**Comment by wangxiaoyou1993** [comment]
> When running through triggers the executor works as expected. It creates a k8s job which in turn creates a pod where the pipeline is executed. However, when running a block through the notebook and specifying k8s as the block executor, then the behavior is not as expected.

@khalit23 That's expected. The notebook is for development, it runs the code in the kernel instead of separate executors. The notebook allows you to do interactive development.
