### ISSUE TITLE
Option to use EU servers on Amplitude

### ISSUE THREAD

**Issue by PrincipalJohnShepherd** [mage-ai/mage-ai#4052]
EU users can't pull data from Amplitude 
Make an option to add another server

```
Region.                     Endpoint
Standard Server	        https://amplitude.com/api/2/export
EU Residency Server	https://analytics.eu.amplitude.com/api/2/export

```
https://github.com/mage-ai/mage-ai/blob/4228835c0d710eef624d1fa51c750f76ffc68a3e/mage_integrations/mage_integrations/connections/amplitude/constants.py

**Comment by wangxiaoyou1993** [comment]
@PrincipalJohnShepherd this feature is available in version 0.9.47 https://github.com/mage-ai/mage-ai/blob/master/mage_integrations/mage_integrations/sources/amplitude/README.md#optional-configs
