### ISSUE TITLE
Destinations technical doc misleading

### ISSUE THREAD

**Issue by suvhotta** [mage-ai/mage-ai#4053]
**Describe the bug**
In the Data Integration section, [destinations technical documentation](https://docs.mage.ai/data-integrations/destinations/overview), the description is the same as that of the [sources technical documentation](https://docs.mage.ai/data-integrations/sources/overview).

**Expected behavior**
Ideally it should have some description regarding what the destination is as part of data integration.

**Additional context**
I can work on contribute and fix this, if provided with what we need to write as part of the description.

**Comment by mattppal** [comment]
@suvhotta we'd love to have your contribution! Want to take a crack at what a Mage destination is and I can review?

**Comment by suvhotta** [comment]
@mattppal Sure will take a shot at it and raise a PR for the same. Just for confirmation, this is the only doc where it needs updation: https://github.com/mage-ai/mage-ai/blob/master/docs/data-integrations/destinations/overview.mdx
or anywhere else as well? 😮

**Comment by suvhotta** [comment]
@mattppal Could u plz confirm the same?

**Comment by mattppal** [comment]
Yes, that's the only doc

**Comment by suvhotta** [comment]
@mattppal I've raised a PR for the same: https://github.com/mage-ai/mage-ai/pull/4097

**Comment by mattppal** [comment]
@suvhotta thanks so much :)
