### ISSUE TITLE
Missing Reduce Output button on child blocks > level-1

### ISSUE THREAD

**Issue by sketeber** [mage-ai/mage-ai#4065]
**Describe the bug**
In my pipelines i use dynamic blocks. Dynamic blocks produce the dynamic childs, in ints turn dynamic childs produce the other dynamic childs. I want to reduce output after several levels of childs block.
If there are several levels of children blocks, then there is no reduce output button.

**To Reproduce**
1. Create dynamic block
2. Click on add 2 blocks after the dynamic block
3. Try to reduce output of the 2nd dynamic child.
4. There is no "Reduce output" button

**Expected behavior**

**Desktop (please complete the following information):**
 - OS: macOS
 - Browser: chrome
 - Version: 119.0.6045.159

**Comment by wangxiaoyou1993** [comment]
@tommydangerous does this [PR](https://github.com/mage-ai/mage-ai/pull/4067) fix this ticket?

**Comment by wangxiaoyou1993** [comment]
This is fixed in version 0.9.47
