### ISSUE TITLE
How to join Mage Slack for support?

### ISSUE THREAD

**Issue by nandubatchu** [mage-ai/mage-ai#4077]
I see there is a restriction on the email domain 
<img width="477" alt="image" src="https://github.com/mage-ai/mage-ai/assets/8403524/4ce14a14-c5fe-45c3-a428-466ca71b07f2">

**Comment by wangxiaoyou1993** [comment]
@nandubatchu There's no restriction on the email domain

**Comment by wangxiaoyou1993** [comment]
@nandubatchu are you able to join the slack channel?

**Comment by nandubatchu** [comment]
Yep, I am able to. Thanks!
