### ISSUE TITLE
Unable to run R scripts 

### ISSUE THREAD

**Issue by Zishan-IA** [mage-ai/mage-ai#4140]
Hi everyone! I am trying to build a data pipeline using R in mage but while executing the code "FileNotFoundError: [Errno 2] No such file or directory: '/tmp/84842c48-c953-4155-9ae6-14447e19467e.r'" I am getting this error, I am just trying to use same code which was available in documentation "https://docs.mage.ai/guides/blocks/r-blocks" If anyone can help me on this it would be a great help thanks in advance. It's working in live but I am facing this issue in my system

**Comment by thomaschung408** [comment]
Hi Zishan! Are you still facing this issue?

**Comment by Zishan-IA** [comment]
I have installed mage in my local windows and I have tried to build a sample pipeline through it,I was using the same sample codes which given in the documentation of mage ai however all the Python codes were working fine locally but when I tried to create a pipeline using R code its reflecting errors 

https://github.com/mage-ai/mage-ai/assets/123532227/dfe2ad03-556a-4912-9638-f5c66c1fa4f7

![Screenshot 2023-12-26 122041](https://github.com/mage-ai/mage-ai/assets/123532227/80b7e847-1b0f-48e0-b6c8-f5087bc3e822)

**Comment by wangxiaoyou1993** [comment]
Hi @Zishan-IA , the R block only works in docker right now.

**Comment by Zishan-IA** [comment]
do I need to install docker or what?? how do I resolve this @wangxiaoyou1993  any suggestion?

**Comment by wangxiaoyou1993** [comment]
@Zishan-IA follow this doc to run Mage in docker: https://docs.mage.ai/getting-started/setup#get-mage

**Comment by Zishan-IA** [comment]
Thanks @wangxiaoyou1993
