### ISSUE TITLE
First Review

### ISSUE THREAD

**Issue by Tamoghna-Saha** [mage-ai/mage-ai#415]
**Bugs:**
_Environment: Virtual Env in WSL 2_
* While installing: `pyproject.toml` file format issue.
* While launching .py script: `ModuleNotFoundError: No module named 'requests'`
* While launching .py script: Unable to access `localhost:5789` from browser

**Operations Performed:**
* Removing duplicates
* Formatting columns value that was suggested
* Custom code implementation - typecast values in certain columns using regex

**Scope of Improvements:**
* Option to edit `custom code` selected from `New Actions`
* Error info displaying in the UI is not redirecting to the root-cause. Was able to figure out from logs.
* **Info icon** which on hover can explain some terminology like `category_high_cardinality`
* Similar info icon or **hyperlink** that redirects to what certain outliers means when selecting, specially how `auto` is performed
* Option to download the processed data in `CSV`/`Excel` format, currently only `JSON` format

**Comment by tommydangerous** [comment]
Thank you @Tamoghna-Saha so much for the feedback!

**Comment by tommydangerous** [comment]
@Tamoghna-Saha will definitely review and incorporate the feedback in the tool.

In the meantime, would you please join our online Slack community so we can keep you up to date? https://www.mage.ai/chat

Thank you!

**Comment by tommydangerous** [comment]
@Tamoghna-Saha for the 3 Bugs:

- While installing: pyproject.toml file format issue.
- While launching .py script: ModuleNotFoundError: No module named 'requests'
- While launching .py script: Unable to access localhost:5789 from browser

Was this caused by running `pip install mage-ai`?

**Comment by Tamoghna-Saha** [comment]
Initially, I was trying to create venv using the toml but it wasn't working.
The next thing happened after I was trying `pip install mage-ai` in a clean venv.
