### ISSUE TITLE
R blocks not running after being removed and re-added to pipeline

### ISSUE THREAD

**Issue by polymathematic** [mage-ai/mage-ai#4171]
**Describe the bug**
After creating a new pipeline, click "Templates" and add a generic R template from the "Data loader" tree. Enter this code:

```
load_data <- function() {
    # Specify your data loading logic here
    # Return value: loaded dataframe
    df <- read.csv(url('https://raw.githubusercontent.com/datasciencedojo/datasets/master/titanic.csv'))
    df
}
```
Running this block should be successful.

Next, remove the block from the pipeline and then re-add it by selecting the saved file on the left and clicking "Add to current pipeline." Any subsequent attempt to run the pipeline will result in something like the following error:

```
Error: unexpected symbol in "2-13 13:18:52.052405', interval_end_datetime='None', interval_seconds='None', interval_start_datetime='2023-12-13 13:18:52.052405', interval_start_datetime_previous='None', event='{}', logger="

Execution halted

 

---------------------------------------------------------------------------

CalledProcessError                        Traceback (most recent call last)

/usr/local/lib/python3.10/site-packages/mage_ai/data_preparation/models/block/r/__init__.py in __execute_r_code(file_path)

    127 

    128 def __execute_r_code(file_path: str):

--> 129     subprocess.run(

    130         [

    131             'Rscript',

 

/usr/local/lib/python3.10/subprocess.py in run(input, capture_output, timeout, check, *popenargs, **kwargs)

    524         retcode = process.poll()

    525         if check and retcode:

--> 526             raise CalledProcessError(retcode, process.args,

    527                                      output=stdout, stderr=stderr)

    528     return CompletedProcess(process.args, retcode, stdout, stderr)

 

CalledProcessError: Command '['Rscript', '--vanilla', '/tmp/9086f1be-3b51-493d-8ff5-1d58c9c750dc.r']' returned non-zero exit status 1.
```

**Additional context**
Running Mage.AI 0.9.50 on Docker with Portainer.

**Comment by johnnatanjc** [comment]
I have the same issue, doing that with R does not work. I have tried using Python and it worked well. Am I missing some dependency?

**Comment by polymathematic** [comment]
A quick update: the proximate cause is that in the temporary R script with global_vars prepended has unescaped singe quotes:
![image](https://github.com/mage-ai/mage-ai/assets/11356756/3353b60c-71ca-44f5-8c91-e7f4fe48209c)

**Comment by thomaschung408** [comment]
Thank you @polymathematic for reporting this! Will have the team take a look and get back to you. Glad you've found a work around for now.

**Comment by Zishan-IA** [comment]
#4140  facing the same
