### ISSUE TITLE
RabbitMQ "amqps" configuration

### ISSUE THREAD

**Issue by veekungx** [mage-ai/mage-ai#4184]
There is some RabbitMQ start with "amqps://..."

But this dataloader missing this part to configure it.

https://github.com/mage-ai/mage-ai/blob/c95489485ba76f11353d183939ad01fa3070f3c3/mage_ai/streaming/sources/rabbitmq.py#L52

**Comment by thomaschung408** [comment]
Hi @veekungx! Thanks for pointing this out. Will review and get back to you. Thank you!
