### ISSUE TITLE
kwargs[“context”] is set globally instead of passed though connected blocks

### ISSUE THREAD

**Issue by csauge** [mage-ai/mage-ai#4210]
**Describe the bug**
I use v0.9.48 Mage version.
I have set run_pipeline_in_one_process: true
It seems that kwargs[“context”] is global to a pipeline and not passed through connected blocks.

**To Reproduce**
1. Click on "Edit Pipeline"
2. Run manually seed_initiatives block (setting a kwargs[“context”])
3. Run manually seed_initiatives_autonomes block (setting another kwargs[“context”])
4. Run manually airtable block (only connected to seed_initiatives)
5. Data in airtable block are related from seed_initiatives_autonomes kwargs[“context”] instead of seed_initiatives kwargs[“context”].

**Expected behavior**
kwargs[“context”] should be passed from a block to another connected block, but not from the last manually run block even if not connected. 

**Screenshots**
<img width="386" alt="Screenshot 2023-12-18 at 19 54 41" src="https://github.com/mage-ai/mage-ai/assets/9370091/fc5dba8e-d94c-4f40-875a-884ef125b81b">

**Desktop (please complete the following information):**
 - OS: MacOS Ventura 13.4.1
 - Browser: Chrome
 - Version: 120.0.6099.109 (Official Build) (arm64)

**Additional context**
No

**Comment by johnson-mage** [comment]
@csauge Thanks for reporting, we'll look into this.

**Comment by Luxi36** [comment]
The `kwargs["context"]` has different behaviour in the editor vs a trigger. Because the editor does automatically run in `run_pipeline_in_one_process: true` mode where as the pipeline itself through triggers doesn't.

To make us of `kwargs["context"]` one needs to make sure that their pipeline config uses `run_pipeline_in_one_process: true`

**Comment by wangxiaoyou1993** [comment]
`kwargs['context']` can only be used when `run_pipeline_in_one_process: true` is set in pipeline metadata.yaml
