### ISSUE TITLE
When changing a block, replicas ones become duplicated

### ISSUE THREAD

**Issue by csauge** [mage-ai/mage-ai#4212]
**Describe the bug**
Given a block with a replica, when changing original one then the replica is duplicated as a new file

**To Reproduce**
1. Create a block (airtable in example)
2. Create a replica in the pipeline (airtable_2 in example)
3. Modify the original block and save it
4. The replica block is duplicated as a new file (airtable_2.py in example)

**Expected behavior**
When changing the original block, replica should not be duplicated as a new file and still point to the original file

**Screenshots**
<img width="239" alt="Screenshot 2023-12-18 at 22 59 47" src="https://github.com/mage-ai/mage-ai/assets/9370091/25faf4cd-5356-4eed-8649-00493155cbe4">
<img width="541" alt="Screenshot 2023-12-18 at 22 59 41" src="https://github.com/mage-ai/mage-ai/assets/9370091/c1eb093d-2340-4f7c-8610-fbec83337b07">

**Desktop (please complete the following information):**
 - OS: MasOS ventura
 - Browser: chrome
 - Version: 120.0.6099.109 (Official Build) (arm64)

**Additional context**
No

**Comment by johnson-mage** [comment]
@csauge Is this issue still happening for you? I tried to recreate it but it seems fine for me (making a change to the original block and saving it did not create a new file for the replica block). I tested this on the latest version of Mage (v0.9.62)

Which version of Mage are you using?
