### ISSUE TITLE
multiple pipelines triggered at same time fail to start - tuple concurrently updated

### ISSUE THREAD

**Issue by octav-s** [mage-ai/mage-ai#4217]
**Describe the bug**
Having multiple pipelines scheduled for same time - example setting them to daily starts them at the same time 00:00:00 - will lead to pipelines starting, but only one will usually run, the rest will fail with error 
'**InternalError: (psycopg2.errors.InternalError_) tuple concurrently updated**'.

After digging deeper in the logs, we found the actual query that fails: **'ALTER ROLE mage IN DATABASE mage SET search_path TO mage'**

We use PostgreSQL for mage backend, to store orchestration data

**To Reproduce**
1. Create multiple pipelines with same daily trigger (we use PostgreSQL  for mage internal DB - not sure if that makes a difference). We had up to 12 or 15 pipelines set to start daily.
2. When the pipelines are triggered, at midnight, they will try to start , only one will actually run, rest will fail 
3. We got the error messages from K8S, as we are running each job in its own pod, but I believe that it happened locally as well
4. The ones that fail will have the 'tuple concurrently updated error'

**Expected behavior**
Pipelines started by triggers at the same time should not fail because of mage internal query, they should either run or fail because of logic error or insufficient/incorrectly configured resources.

**Screenshots**
![magesql error (2)](https://github.com/mage-ai/mage-ai/assets/17203247/734a2825-0256-4cd4-bbdb-6cf28a8d48b5)
![image](https://github.com/mage-ai/mage-ai/assets/17203247/767c589f-911b-421d-98c0-ac6bf2c1547a)

**Desktop (please complete the following information):**
 - OS: official mage docker container

**Additional context**
This happened in version 0.9.45 and previous versions. We have updated to 0.9.50 and will update bug report if this happens again. But we were forced to space out scheduled runs and might not encounter the situation .

**Comment by dy46** [comment]
thanks for reporting this. we will take a look
