### ISSUE TITLE
Cron expression changes if being set to midnight in GMT+8

### ISSUE THREAD

**Issue by KamarulAdha** [mage-ai/mage-ai#4266]
**Describe the bug**
Cron expression changes after saving it. Currently on GMT+8. When I created a trigger for my pipeline to run at every midnight using this crone expression `0 0 * * *`, it shows the conversion that it will trigger every midnight. But after saving the configuration, I can see the cron expression changed to `0 16 * * *`, but the next run is still at midnight. When I try to edit it again, it kept the `0 16 * * *` setting and showed 4PM in the conversion. 

**To Reproduce**
1. Go to a pipeline.
2. Go to trigger.
3. Set custom time.
4. Set `0 0 * * *`.
5. See the conversion as midnight.
6. Save setting.
7. Check the cron expression changed.
8. Current timezone that triggered this bug is at GMT+8.

**Expected behavior**
After creating the cron expression, it should stay that way. If I set it to `0 0 * * *`, it should stay like that after saving the configuration. 

**Screenshots**
1) 
![image](https://github.com/mage-ai/mage-ai/assets/52944294/b3a4574c-bdca-41a0-9142-65240090a7bb)
2) 
![image](https://github.com/mage-ai/mage-ai/assets/52944294/462c150a-fe69-4320-905b-6ace25a74dc8)

**Desktop (please complete the following information):**
 - OS: Ubuntu 22.04
 - Browser: Edge
 - Version: Version 120.0.2210.91 (Official build) (64-bit)

**Smartphone (please complete the following information):**
- Did not test on smartphone as I had to port-forward it to my browser.

**Additional context**
N/A

**Comment by johnson-mage** [comment]
@KamarulAdha Thanks for bringing up this issue. It was addressed in this [PR](https://github.com/mage-ai/mage-ai/pull/4359) and should be fixed in the next version.

**Comment by johnson-mage** [comment]
@KamarulAdha New version is live (v0.9.60). You can try out the midnight cron expression again and see if there are any issues. Thanks!
