### ISSUE TITLE
Unable to update submodule using one-way sync with https

### ISSUE THREAD

**Issue by miello** [mage-ai/mage-ai#4305]
**Describe the bug**
Could not update or init submodule using one-way sync option with HTTPS authentication type if repository contains submodule which path does not in the top-level folder such as `/utils/helper` or `/utils/aaa`

**To Reproduce**
1. Setup repository with `utils/helper` submodule
2. Go to `/settings/workspace/sync-data`
3. Configure git authentication credentials to be **HTTPS** and check `Include submodules`
4. Click `Synchronize code`
5. We will see fatal error in logs with success snackbar in browser

**Expected behavior**
fatal error should not appear in console and submodule should be updated or initialized

**Screenshots**

After synchronizing code in git settings with enabled `Include Submodules`, it appears fatal error about `.git/config` in container logs

![image](https://github.com/mage-ai/mage-ai/assets/35169079/7b811d20-afe0-40f8-b8f9-1f23673373bc)

I have partially run this method in local with some modifications, it gives me malformed config in `.git/config` when submodule is not top-level folder https://github.com/mage-ai/mage-ai/blob/e98291dbaedccc391b7b699dd0338d4663bde93f/mage_ai/data_preparation/git/__init__.py#L271

![image](https://github.com/mage-ai/mage-ai/assets/35169079/1befcedd-3590-400b-8996-880df5340287)

**Desktop (please complete the following information):**
 - OS
    - Windows 10 22H2
 - Browser: 
    - Microsoft Edge Version 120.0.2210.91 (Official build) (64-bit)
 - Version
    - mage-ai (v0.9.58) running via Docker (mageai/mageai:latest)

**Comment by dy46** [comment]
hey @miello, thanks for looking into the issue! we will work on a fix 

can you specify your project structure? it's a little unclear how the `utils/helper` folder and your project folder is related
