### ISSUE TITLE
Getting data from multiple upstream blocks not working in Data exporter

### ISSUE THREAD

**Issue by yiyu2024** [mage-ai/mage-ai#4323]
Path: /design/blocks/transformer

it is saying that "All blocks (except Scratchpads and Sensors) pass their data from the return statement in their decorated function to all their downstream blocks."
I can't get more than 1 upstream block data in Data exporter

**Comment by wangxiaoyou1993** [comment]
@yiyu2024 here is an example of getting multiple upstream block data
<img width="726" alt="image" src="https://github.com/mage-ai/mage-ai/assets/80284865/9b8796b1-9b50-47b8-9ae7-d2635c648cbd">
<img width="492" alt="image" src="https://github.com/mage-ai/mage-ai/assets/80284865/a91093b8-bcc9-47d4-b7eb-74b358407ce2">

**Comment by reidlai** [comment]
using data, and data_2 are too risky.   can we use block name or named parameters instead of positional parameter
