### ISSUE TITLE
execution_date not set for pipeline in 0.9.59

### ISSUE THREAD

**Issue by octav-s** [mage-ai/mage-ai#4351]
**Describe the bug**
Pipelines using execution_date variable in SQL code are failing in v 0.9.59 because the variable is not set to a datetime.

Error message:

`InvalidDatetimeFormat: invalid input syntax for type date: ""

LINE 3: WHERE date_id = ''::date - INTERVAL '1 DAY'
                        ^`

`DatabaseError: Execution failed on sql 'DELETE  

FROM interim.aggregate_launch_stat_facts

WHERE date_id = ''::date - INTERVAL '1 DAY'

RETURNING *': invalid input syntax for type date: ""

LINE 3: WHERE date_id = ''::date - INTERVAL '1 DAY'
                        ^`

(the up arrow is pointing at the empty date interval)

**To Reproduce**
1. SQL block that uses execution_date pipeline variable in v 0.9.50 runs correctly
2. in v 0.9.59 the SQL block fails with error message above

**Expected behavior**
In v 0.9.50 and before the variable execution_date was being replaced with either the current date or the backfill date.

**Screenshots**
![image](https://github.com/mage-ai/mage-ai/assets/17203247/ff87450e-6a62-4d7e-91d3-884a91c79b0f)

![image](https://github.com/mage-ai/mage-ai/assets/17203247/8b36af5b-de06-4077-9d39-d1fa3f3a4d8b)

![image](https://github.com/mage-ai/mage-ai/assets/17203247/4c7dfadb-2387-495c-a1ec-35faef3328dd)

**Desktop (please complete the following information):**
 - OS: Windows 11
 - Browser Edge
 - Version 120.0.2210.121

**Comment by wangxiaoyou1993** [comment]
@octav-s are you using docker? can you try docker image `mageai/mageai:latest`. we made a fix yesterday.

**Comment by wangxiaoyou1993** [comment]
Close this issue. The fix will be included in the 0.9.60. You can use `mageai/mageai:latest` docker image for now.
