### ISSUE TITLE
Widget object has no attribute 'write_async'

### ISSUE THREAD

**Issue by machzqcq** [mage-ai/mage-ai#4364]
**Describe the bug**
When trying to add any chart from UI , throws error "Widget object has no attribute 'write_async'"

**To Reproduce**
1. Follow instructions on quickstart to up docker-compose stack - https://docs.mage.ai/getting-started/setup#get-mage 
2. Access the UI using IP address (e.g. http://192.168.0.111:6789)
3. Pipelines > example_pipelines > edit
4. Execute the first data_loader block (load_titanic) - works fine as expected
5. Now click the chart icon on the data_loader block (so as to view the data)
6. Error appears

**Expected behavior**
Expect to have a chart/visual on the right side (as shown in all demo videos)

**Screenshots**
<img width="1322" alt="image" src="https://github.com/mage-ai/mage-ai/assets/6425159/3ff5efa3-50f4-4c98-982c-67f29ddb6e2c">

**Desktop (please complete the following information):**
 - Server on which docker-compose was launched: ubuntu 20.04, server from which url was accessed: macOS
 - Browser [Chrome Version 120.0.6099.109 (Official Build) (x86_64]

**Comment by wangxiaoyou1993** [comment]
Thanks for reporting the issue. We'll fix it.
