### ISSUE TITLE
Microsoft SQL Driver issue: Driver 11

### ISSUE THREAD

**Issue by Orionku14** [mage-ai/mage-ai#4369]
My request is timing out when trying to connect a data loader to my MS SQL server. It seam that I am using " ODBC Driver 11 for my SQL Server ", but mage io does not support this driver.

If I run the loader with " ODBC Driver 18 for SQL Server " in the config file I get the error message

![image](https://github.com/mage-ai/mage-ai/assets/152406784/5403f430-b0dd-49fe-8aab-27096917bdbc)

 and if I run the loader with  " ODBC Driver 11 for SQL Server " in the config file I get the error message 

![image](https://github.com/mage-ai/mage-ai/assets/152406784/7c8acac7-8e2c-4e2f-927f-55c23f17a945)

Is there anyone that can assist me with this as I am not sure how to change the ODBC Driver to 11.

**Comment by wangxiaoyou1993** [comment]
Hi @Orionku14 ODBC Driver is installed in the docker image by default. https://github.com/mage-ai/mage-ai/blob/master/Dockerfile#L17
If you want to use ODBC Driver 11, you'll need to build a custom docker image and install this driver. I think the driver should be `msodbcsql11`

**Comment by Orionku14** [comment]
Hi @wangxiaoyou1993 thank you. I will try this fix. Much appreciated.
