### ISSUE TITLE
User authentication via Identity server 4

### ISSUE THREAD

**Issue by ZaighamRaza** [mage-ai/mage-ai#4401]
**Is your feature request related to a problem? Please describe.**
Currenlty, user authentication is environment variable based and not much secured. We need SSO and user authentication via IDS4.

**Describe the solution you'd like**
Mage should provide support for IDS4 so that we can enable SSO and user authentication

**Comment by wangxiaoyou1993** [comment]
Hi @ZaighamRaza , is this a duplicate ticket with this one? https://github.com/mage-ai/mage-ai/issues/4381

**Comment by ZaighamRaza** [comment]
@wangxiaoyou1993 yes. can you please tell me when this feature will be available

**Comment by wangxiaoyou1993** [comment]
Yes. @ZaighamRaza could you let us know when do you need this feature by?

**Comment by ZaighamRaza** [comment]
@wangxiaoyou1993 i next month if possible

**Comment by unmovable-october-barricade** [comment]
We would also be very happy about getting OIDC or OAuth2.0 support (Keycloak). The sooner the better

**Comment by dy46** [comment]
Hi, we recently added a generic OIDC authentication provider. Here is the documentation for enabling it: https://docs.mage.ai/production/authentication/oidc.

Let me know if you run into any issues integrating your OIDC provider. There could potentially be some issues for specific providers.
