### ISSUE TITLE
Time-out triggers to be marked as cancelled instead of failed

### ISSUE THREAD

**Issue by Shreyasi3521** [mage-ai/mage-ai#4420]
**Is your feature request related to a problem? Please describe.**
Yes, We are not able to identify actual pipeline failures and timeouts, it's causing problems in analysis.

**Describe the solution you'd like**
it'd be great if the timed-out triggers were marked as canceled or any other marking and not failed.

**Comment by dy46** [comment]
hey this feature should be included in the latest mage version (0.9.63), you should be able to select the status when configuring the trigger.
