### ISSUE TITLE
[BUG] SQL Block Errors when creating table (BigQuery)

### ISSUE THREAD

**Issue by JamesBoz** [mage-ai/mage-ai#4423]
### Mage version

v0.9.60

### Describe the bug

Hi, I’m encountering some errors when attempting to run this SQL block:

<img width="533" alt="Screenshot 2024-01-22 at 16 08 43" src="https://github.com/mage-ai/mage-ai/assets/157396971/ff5f9089-d484-49d6-8f9c-007d5430eb57">

The errors are:
ValueError: Circular reference detected and 
ValueError: Please provide dataframe or json serializable data as output.

(I can fix this error when ticking the ‘Disable query preprocessing’ option. However, when I swap ‘bcfc.SB_teaminfo’ with the variable {{ df_1 }} from the previous block, I encounter a different issue. Hence, I am trying to avoid using this ‘Disable query preprocessing’ option.)

**Comment by tommydangerous** [comment]
Can you also share the other issue so we can address as well? Thank you!

**Comment by tommydangerous** [comment]
Fixed here: https://github.com/mage-ai/mage-ai/pull/4428

**Comment by JamesBoz** [comment]
> Can you also share the other issue so we can address as well? Thank you!

Hi Tommy,
When using {{ df_1 }} with the 'Disable query preprocessing' option ticked, the following error is returned:
BadRequest: 400 Not found: Dataset arctic-idiom-411713:arctic-idiom-411713 was not found in location europe-west2 at [3:1] 

This is also the case when I explicitly state the project, dataset, and table. I.e. When I replace bcfc.test with `arctic-idiom-411713.bcfc.test` (with 'arctic-idiom-411713' being my BigQuery project name).

Also, it may be useful to know that the following output is also returned:
Exporting data from upstream block sb_competitions_loader to arctic-idiom-411713.None.dev_data_run_sb_competitions_loader_v1.

Does the database being 'None' here indicate an issue?

<img width="743" alt="Screenshot 2024-01-23 at 09 08 45" src="https://github.com/mage-ai/mage-ai/assets/157396971/46b128a7-77b5-4944-abc4-bab38e7094f9">

**Comment by JamesBoz** [comment]
In fact, a simple block of `SELECT * FROM {{ df_1 }}` returns a similar error:
NotFound: 404 Not found: Dataset arctic-idiom-411713:arctic-idiom-411713 was not found in location US

Note how the location has changed from 'europe-west2' to 'US'
