### ISSUE TITLE
Issue on docs

### ISSUE THREAD

**Issue by mts-dyt** [mage-ai/mage-ai#4442]
Path: /production/authentication/microsoft

Doc is incomplete - how can we enable authentication with AAD?
Adding the environment variable `ACTIVE_DIRECTORY_DIRECTORY_ID`  don't enable AAD login.

**Comment by mattppal** [comment]
@mts-dyt Are you saying changing the environment variable _doesn't_ enable Microsoft login? Do you have the `REQUIRE_USER_AUTHENTICATION` variable set to `1`

@dy46 is there an additional step here to enable ADD login? Or does the doc suffice
