### ISSUE TITLE
Issue on docs

### ISSUE THREAD

**Issue by persiyanov** [mage-ai/mage-ai#4507]
Path: /production/deploying-to-cloud/gcp/setup

On the **GCP Setup** page, Cloud SQL permission is unspecified (see screenshot below). GCP has 5 roles related to Cloud SQL:
1. Cloud SQL Admin
2. Cloud SQL Client
3. Cloud SQL Editor
4. Cloud SQL Instance User
5. Cloud SQL Viewer

Which one is required for Mage deployment?

<img width="764" alt="CleanShot 2024-02-01 at 16 01 32" src="https://github.com/mage-ai/mage-ai/assets/3997997/05a0c677-8c85-40ad-8ddc-0f380aaa6abb">

**Comment by mattppal** [comment]
I'm pretty sure it's Cloud SQL Admin— have you tried deployment?

**Comment by MerlinSchaefer** [comment]
To run the GCP terraform template you need Cloud SQL Admin. main.tf creates a resource with Cloud SQL Admin API.

**Comment by mattppal** [comment]
Thanks @MerlinSchaefer
