### ISSUE TITLE
[BUG] All Pipelines Stuck on Initial State

### ISSUE THREAD

**Issue by hevertonmedeiros** [mage-ai/mage-ai#4510]
### Mage version

9.60

### Describe the bug

When I create a pipeline, all triggers stuck on initial state. The only way it runs, is by clicking "Run block" or "Execute with all upstream block" manually
[Gravação de tela de 2024-02-01 16-46-37.webm](https://github.com/mage-ai/mage-ai/assets/37874229/da09a609-9906-4979-9a13-0beb1a392995)

Don't have any information error on logs

### To reproduce

Create a pipeline
Go to Trigger
Create any type trigger

**Comment by johnson-mage** [comment]
@hevertonmedeiros Is this trigger saved in code? If it is, can you please send the `triggers.yaml` file contents for your pipeline?

Also, did you happen to upgrade to a later version and then downgrade back to 0.9.60?

**Comment by hevertonmedeiros** [comment]
Hi @johnson-mage, sorry for late response.
I updated to version v0.9.62, before to post the trigger, but have no success to starting pipelines on mage.

Only way continues manual 
![mage_ultra_simple_test](https://github.com/mage-ai/mage-ai/assets/37874229/e5352249-2439-448f-980e-f383725eede5)

**Comment by johnson-mage** [comment]
@hevertonmedeiros This API trigger is different from the previous one you posted (named "solitary talisman"), right? Can you please take a screenshot of the API trigger's details? Looks something like this when you click on the trigger for example:
![image](https://github.com/mage-ai/mage-ai/assets/78053898/b3b4dcc9-a23e-4f1f-9e4f-c49d2191e3b2)

**Comment by hevertonmedeiros** [comment]
Hi @johnson-mage here is the screenshot
![Captura de tela de 2024-02-05 15-39-14](https://github.com/mage-ai/mage-ai/assets/37874229/f9e42e5e-0f3b-4f75-b4c0-3fde37274095)

**Comment by johnson-mage** [comment]
@hevertonmedeiros Are you in our Slack [channel](https://www.mage.ai/chat)? Can you please message me there so I can help troubleshoot?

**Comment by johnson-mage** [comment]
Issue has been resolved with user. The `project_type` in the project's `metadata.yaml` configuration file was set to `main` instead of `standalone`, so the scheduler was not starting.
