### ISSUE TITLE
[BUG] The workspace list is displaying an incorrect workspace URL if LB is created dynamically (K8s workspaces)

### ISSUE THREAD

**Issue by cisrudlow** [mage-ai/mage-ai#4526]
### Mage version

0.9.62

### Describe the bug

I have an EKS cluster with an AWS LB Controller that dynamically creates a load balancer for a given Ingress. The public Mage address (i.e., the Ingress address) is not known at the time of the Mage deployment, because the LB will be created later.

The correct workspace address should appear. Instead, it displays **http://None/{workspace_name}**.

In **mage_ai/cluster_manager/kubernetes/workload_manager.py -> get_url_from_ingress(...)**, you expect a host to be defined in the ingress rule, but this is not always possible. Everything depends on how the networking (DNS, etc.) will be configured.

Generally, this can be easily resolved by adding a few lines after **host = rule.host** in **get_url_from_ingress(...)**:

   ```
if host is None:
    # Check if `status`, `loadBalancer`, and `ingress` attributes exist and are not None
    if (hasattr(ingress, 'status') and ingress.status is not None and
        hasattr(ingress.status, 'loadBalancer') and ingress.status.loadBalancer is not None and
        hasattr(ingress.status.loadBalancer, 'ingress') and ingress.status.loadBalancer.ingress and
        len(ingress.status.loadBalancer.ingress) > 0):
        first_ingress = ingress.status.loadBalancer.ingress[0]
        if hasattr(first_ingress, 'hostname') and first_ingress.hostname is not None:
            host = first_ingress.hostname
        # Alternatively, check for `ip` if `hostname` is not available
        elif hasattr(first_ingress, 'ip') and first_ingress.ip is not None:
            host = first_ingress.ip
```
Please forgive the incorrect code, as I am just dumping what's in my head, but I want to convey the idea only.

**Comment by dy46** [comment]
hey @cisrudlow, taking look at this ticket now. In your setup, it seems like you would access the workspace through the load balancer created by the AWS LB Controller. In that case, the hostname or ip from the ingress itself would not actually allow you to access the workspace, right?

**Comment by cisrudlow** [comment]
Hi dy46. Yes. I don't have hostname in ingress spec. LB is created by AWS LB Controller and public url is avaiable in status.
Here is my ingress (with added workspace) with status field:

```apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  annotations:
    alb.ingress.kubernetes.io/group.name: mageai
    alb.ingress.kubernetes.io/scheme: internet-facing
    alb.ingress.kubernetes.io/tags: owner=xxx
    alb.ingress.kubernetes.io/target-type: instance
  finalizers:
  - group.ingress.k8s.aws/mageai
  generation: 2
  name: mage-ingress
  namespace: mage
  resourceVersion: "2890"
spec:
  ingressClassName: alb
  rules:
  - http:
      paths:
      - backend:
          service:
            name: demo3-service
            port:
              number: 6789
        path: /demo3
        pathType: Prefix
      - backend:
          service:
            name: mageai
            port:
              number: 6789
        path: /*
        pathType: ImplementationSpecific
status:
  loadBalancer:
    ingress:
    - hostname: {lb name}.elb.amazonaws.com```

**Comment by dy46** [comment]
ah that's for that example config. that makes much more sense now
