### ISSUE TITLE
Upsert Functionality for Data Exporters

### ISSUE THREAD

**Issue by brettshollenberger** [mage-ai/mage-ai#4527]
**Is your feature request related to a problem? Please describe.**

When dealing with big datasets, a useful pattern is to split up transformations using Dynamic Blocks, but one existing limitation is that Data Exporter blocks don't support upsert functionality — meaning we can't get incremental wins or checkpoints to allow a pipeline to pick back up only on blocks it hasn't succeeded on. The dataset either all succeeds or all fails, with upserts needing to be handled in a downstream SQL block (and also creating n intermediate tables from the batch blocks along the way). 

The n-blocks creation is itself enough of an issue to avoid this pattern, and instead use append logic on data exporters, but this creates the additional problem that the table itself needs to be deleted before running the batches to ensure we don't end up with duplicate rows.

Currently the options are:

1. SQL Block runs delete table if exists
2. Dynamic block creates n batches, splitting on some user-defined key
3. N dynamic transformations run, with append logic on the data exporter blocks, and only 1 new table created

Or:

1. Dynamic block creates n batches
2. N transformations run, returning the transformed data
3. N SQL blocks perform an upsert, but n intermediate tables are also created from the transformation blocks

**Describe the solution you'd like**
Data exporter blocks should allow `upsert` as one of the options for `if_exists`, with additional options for `conflict_target` and columns to update. A good example library implementing this feature for an ORM is: https://github.com/zdennis/activerecord-import

For example, in Postgres this logic would be mapped to:

```
ON CONFLICT(conflict_columns) 
DO UPDATE SET
  update_column_1 = new_values.update_column_1,
  update_column_2 = new_values.update_column_2;
```

**Describe alternatives you've considered**
Alternatives described above. They're not great. These would be great quality of life improvements to see to help Mage receive more widespread adoption. 

**Additional Context**
Personally, the databases I use the most are Snowflake and Postgres, but I think with data exporters we'd want to support this functionality across the board.

**Comment by brettshollenberger** [comment]
For what it's worth, Postgres already supports the keywords `unique_conflict_method="UPDATE"` and `unique_constraints`, but Snowflake doesn't:

https://github.com/mage-ai/mage-ai/blob/65f2673ecb7e087a1155c917387ba04055f48b4a/mage_ai/io/postgres.py#L360

**Comment by wangxiaoyou1993** [comment]
We'll support it for Snowflake, MySQL, BigQuery.

**Comment by Oubaluna** [comment]
it will not be possible for postgres ? :) 

In the mean time I use an upsert function that I use in python to do it if that help anyone : 

```
import os

import numpy as np
from sqlalchemy import create_engine
from sqlalchemy import MetaData, Table
from sqlalchemy.dialects import postgresql
from sqlalchemy.inspection import inspect


def upsert_in_postgres(
    engine,
    schema,
    table_name,
    records=[],
    update_columns=[]
):
    metadata = MetaData(schema=schema)
    metadata.bind = engine

    table = Table(table_name, metadata, schema=schema, autoload=True)

    # Convert NaN and Infinity values to None
    records_cleaned = []
    for record in records:
        cleaned_record = {}
        for key, value in record.items():
            if isinstance(value, float) and (np.isnan(value) or np.isinf(value)):
                cleaned_record[key] = None
            else:
                cleaned_record[key] = value
        records_cleaned.append(cleaned_record)

    # get list of fields making up primary key
    primary_keys = [key.name for key in inspect(table).primary_key]

    # assemble base statement
    stmt = postgresql.insert(table).values(records_cleaned)

    # Define dict of columns to update
    update_dict = {
        c.name: c
        for c in stmt.excluded
        if c.name in update_columns  # Only update specified columns
    }

    # Cover the case when no columns are specified for update
    if not update_dict:
        print('No columns specified for update.')
        return None

    # Create the update statement with 'on conflict do update' clause
    update_stmt = stmt.on_conflict_do_update(
        index_elements=primary_keys,
        set_=update_dict,
    )

    # Execute the upsert
    with engine.begin() as conn:
        conn.execute(update_stmt)
```

**Comment by wangxiaoyou1993** [comment]
> it will not be possible for postgres ? :)
> 
> In the mean time I use an upsert function that I use in python to do it if that help anyone :
> 
> ```
> import os
> 
> import numpy as np
> from sqlalchemy import create_engine
> from sqlalchemy import MetaData, Table
> from sqlalchemy.dialects import postgresql
> from sqlalchemy.inspection import inspect
> 
> 
> def upsert_in_postgres(
>     engine,
>     schema,
>     table_name,
>     records=[],
>     update_columns=[]
> ):
>     metadata = MetaData(schema=schema)
>     metadata.bind = engine
> 
>     table = Table(table_name, metadata, schema=schema, autoload=True)
> 
>     # Convert NaN and Infinity values to None
>     records_cleaned = []
>     for record in records:
>         cleaned_record = {}
>         for key, value in record.items():
>             if isinstance(value, float) and (np.isnan(value) or np.isinf(value)):
>                 cleaned_record[key] = None
>             else:
>                 cleaned_record[key] = value
>         records_cleaned.append(cleaned_record)
> 
>     # get list of fields making up primary key
>     primary_keys = [key.name for key in inspect(table).primary_key]
> 
>     # assemble base statement
>     stmt = postgresql.insert(table).values(records_cleaned)
> 
>     # Define dict of columns to update
>     update_dict = {
>         c.name: c
>         for c in stmt.excluded
>         if c.name in update_columns  # Only update specified columns
>     }
> 
>     # Cover the case when no columns are specified for update
>     if not update_dict:
>         print('No columns specified for update.')
>         return None
> 
>     # Create the update statement with 'on conflict do update' clause
>     update_stmt = stmt.on_conflict_do_update(
>         index_elements=primary_keys,
>         set_=update_dict,
>     )
> 
>     # Execute the upsert
>     with engine.begin() as conn:
>         conn.execute(update_stmt)
> ```

Postgres is already supported
