### ISSUE TITLE
Allow case sensitive naming in Postgresql data exporter

### ISSUE THREAD

**Issue by manucorrado-lodgify** [mage-ai/mage-ai#4530]
**Is your feature request related to a problem? Please describe.**
As of now the default behaviour of Postgres Loader execute() method lowercases both table and column names without any flag or argument to modify the behaviour. Hence, as is, the exporter is not able to insert data into any tables that have non-lowercase names or column names.
Given that Postgresql is case sensitive, this is quite bothersome.

**Describe the solution you'd like**
Ideal scenario would be to add an option in the Postgres loader creation to specify whether you want to enforce lowercase or not.

**Comment by manucorrado-lodgify** [comment]
Counterintuitively - the following [README.md](https://github.com/mage-ai/mage-ai/tree/master/mage_integrations/mage_integrations/destinations/postgresql) mentions said flag. 
Yet the actual implementation does not support it.

**Comment by wangxiaoyou1993** [comment]
The PR is merged: https://github.com/mage-ai/mage-ai/pull/4569
We'll build a new version that includes this change.

**Comment by wangxiaoyou1993** [comment]
This is published in version 0.9.64
