### ISSUE TITLE
[BUG] Git Directory panel in Version Control view content is cut

### ISSUE THREAD

**Issue by aaalexlit** [mage-ai/mage-ai#4538]
### Mage version

v0.9.62

### Describe the bug

Git Directory panel in Version Control view content is cut when you switch to the Version Control view for the first time (screenshot initial) 

Then after resizing the panel it seems to become more or less okay, but still flickering when mouseover and is not located under the "Git Directory" tab
(screenshot after resizing)

### To reproduce

1. Go to "Version control" view
2. Resize by draging the Right panel border

### Expected behavior

Git Directory panel takes up the whole space

### Screenshots

Initial 
<img width="842" alt="image" src="https://github.com/mage-ai/mage-ai/assets/116374290/d5a88ae7-e398-4c3b-9783-6fd95bba9e6e">

after resizing
<img width="1035" alt="image" src="https://github.com/mage-ai/mage-ai/assets/116374290/28fd7030-7b19-41b1-aa20-44cf17b862c2">

### Operating system

- OS macOS Ventura 13.6.3 (22G436)
- Google Chrome Version 121.0.6167.139 (Official Build) (arm64)

**Comment by johnson-mage** [comment]
@aaalexlit Thanks for reporting, we'll look into this.

**Comment by johnson-mage** [comment]
Fixed the Version Control page cutoff/blank section issue in this [PR](https://github.com/mage-ai/mage-ai/pull/4644). The bugfix will be in the next version (0.9.65). The two columns (for "All projects" and "Git directory") each take up half of the width of the left panel, so the second column wouldn't necessarily be directly under "Git directory".

**Comment by johnson-mage** [comment]
v0.9.65 is available now.
