### ISSUE TITLE
[BUG] Docker install exits with error

### ISSUE THREAD

**Issue by jase64** [mage-ai/mage-ai#4540]
### Mage version

latest

### Describe the bug

When trying to (quick) install mage in a Virtualbox VM, the docker run command ends with an error and the container is stopped.
```
$ sudo docker run -it -p 6789:6789 -v $(pwd):/home/src mageai/mageai /app/run_app.sh mage start APM
Execute command: mage start APM
/app/run_app.sh: line 53:     7 Illegal instruction     (core dumped) "$@
```

### To reproduce

```
$ sudo docker run -it -p 6789:6789 -v $(pwd):/home/src mageai/mageai /app/run_app.sh mage start APM
Execute command: mage start APM
/app/run_app.sh: line 53:     7 Illegal instruction     (core dumped) "$@
```

### Expected behavior

Expected behaviour: Container up an drunning

### Operating system

VM (Virtualbox)
8Gb RAM / 6 vcores / 20Gb disk/ OS debian 11 bullseye

```
sudo docker version
Client: Docker Engine - Community
 Version:           25.0.2
 API version:       1.44
 Go version:        go1.21.6
 Git commit:        29cf629
 Built:             Thu Feb  1 00:23:27 2024
 OS/Arch:           linux/amd64
 Context:           default

Server: Docker Engine - Community
 Engine:
  Version:          25.0.2
  API version:      1.44 (minimum version 1.24)
  Go version:       go1.21.6
  Git commit:       fce6e0c
  Built:            Thu Feb  1 00:23:27 2024
  OS/Arch:          linux/amd64
  Experimental:     false
 containerd:
  Version:          1.6.28
  GitCommit:        ae07eda36dd25f8a1b98dfbf587313b99c0190bb
 runc:
  Version:          1.1.12
  GitCommit:        v1.1.12-0-g51d5e94
 docker-init:
  Version:          0.19.0
  GitCommit:        de40ad0
```

**Comment by jase64** [comment]
Similar to https://github.com/mage-ai/compose-quickstart/issues/1

**Comment by miquelmartorell** [comment]
same here

**Comment by vdgns** [comment]
version 0.7.103 starts ok, but all versions starting from 0.8.0 and above print the same error:
**/app/run_app.sh: line 53:     7 Illegal instruction     (core dumped) "$@**
and don't start

**Comment by vdgns** [comment]
version 0.8.69 starts ok, but all versions above print the same error:
**/app/run_app.sh: line 53:     7 Illegal instruction     "$@"**
and don't start.

**Comment by isurudassanayake** [comment]
Same error. What is the solution to this error?

**Comment by uaydogdu** [comment]
same here

**Comment by kanocarra** [comment]
For anyone still having this issue, it looks to be a difference in platform. I was able to get it working by removing the platform tag in docker run e.g.:

```
docker build --tag mageprod:latest .
```
