### ISSUE TITLE
[BUG] Postgres export looking for "_type" column that doesn't exist anywhere

### ISSUE THREAD

**Issue by bfg-coding** [mage-ai/mage-ai#4542]
### Mage version

0.9.58

### Describe the bug

While using the data exporter Postgres I'm getting the below error looking for a _type that doesn't exist in the data going into the exporter or on the database it's trying to export into

![Screenshot from 2024-02-06 14-13-34](https://github.com/mage-ai/mage-ai/assets/11151592/f6b06f82-1a28-47d8-b724-1de75e449eb2)

Transformer going into the exporter

![Screenshot from 2024-02-06 14-14-16](https://github.com/mage-ai/mage-ai/assets/11151592/be7172b5-a160-4957-a8eb-a0821952cdd1)

Prisma definition of the table on the database

![Screenshot from 2024-02-06 14-14-42](https://github.com/mage-ai/mage-ai/assets/11151592/a19d5aae-44df-400a-8086-c21926ba0160)

### To reproduce

1. docker compose setup of a mariadb, postgres, and mage
2. Process data from another database (mine is Mariadb in the compose network)
3. Try to export transformed data into the postgres database 

### Expected behavior

Export data like other exporters have worked

### Operating system

OS: Linux
Browser: Firefox

**Comment by bfg-coding** [comment]
I've updated to the latest version and the issue persists.  I had to rerun my other pipelines I built before this one and they don't have any issues.   This one and ones where I'm trying to export to database in the same way fail the same way. They say `column "_first_column" of relation "table_name" does not exist`

**Comment by wangxiaoyou1993** [comment]
@bfg-coding could you add `allow_reserved_words=True` in the method params?

**Comment by wangxiaoyou1993** [comment]
@bfg-coding your issue be resolved by specifying `allow_reserved_words=True` in the method. Feel free to reopen the ticket if it's not resolved.
