### ISSUE TITLE
[BUG] Impossible to schedule a run for a certain time using @daily frequency

### ISSUE THREAD

**Issue by aaalexlit** [mage-ai/mage-ai#4546]
### Mage version

v0.9.62

### Describe the bug

If I set the frequency to daily and choose a start date **and time** the schedule of the next run is still at 00:00 (ie the "Next run date") instead of the specified time. I don't see any other option to set run time except for the `Start date and time`

### To reproduce

1. Create a new trigger
2. Choose schedule type
3. set Frequency to daily
4. choose current date as start date
5. Save changes
6. Observe "next run date" at 00:00

### Expected behavior

Expected either of the 2 options:
- the next run date is day apart from the Start date
or 
- there's a field to set the exact run time (for daily, weekly, monthly frequency)

### Screenshots

<img width="607" alt="image" src="https://github.com/mage-ai/mage-ai/assets/116374290/af79f67d-a144-4e9d-a801-4bd54d4035d8">
<img width="379" alt="image" src="https://github.com/mage-ai/mage-ai/assets/116374290/9e10bb89-4815-4503-bb5e-0446bad9bf3a">

### Operating system

OS macOS Ventura 13.6.3 (22G436)
Google Chrome Version 121.0.6167.139 (Official Build) (arm64)

**Comment by wangxiaoyou1993** [comment]
The start time is when the trigger becomes active.
If you want to schedule it to be a specific time of the day, you can use custom frequency and cron expression: https://docs.mage.ai/orchestration/triggers/schedule-pipelines

**Comment by aaalexlit** [comment]
Then probably it makes sense to convert this to a feature request.
I don't see much value in introducing the daily, weekly, etc options that can only be run at 00:00. From my experience, that wouldn't work in the majority of real-world cases. Yes, one can switch to cron expression (that I did), but introducing these other options that are rarely used means just cluttering the interface.
Again, that is my opinion from my own experience, someone else might have a different one.

I'm happy to create a feature request if you think it makes sense.
