### ISSUE TITLE
[BUG] Command Center - Arcane library and Portal Terminal weird behavior

### ISSUE THREAD

**Issue by ThomasGenetRepo** [mage-ai/mage-ai#4566]
### Mage version

0.9.63

### Describe the bug

Hey! I just upgraded to v0.9.63 and I'm getting weird behavior from the Arcane library & Portal Terminal. If I have one of them, let's say Arcane library open & minified and then open the portal terminal, then I can't access the arcane library anymore when clicking on it (it was working in v0.9.62). Then If I minify the portal terminal, it sort of 'spans' out across the bottom of the page & isn't clickable. At that point if I try to open the arcane library, it pops the window up, but it furiously pops in and out of focus if my mouse if hovering above the window. These issues pop up regardless if I open the terminal or library first.
Refreshing the page fixes somewhat fixes the issue. If I have either or open, then refreshing the page will make it stop furiously popping and out of focus. If refresh the page when both are minified, but one of them is 'splatted out' across the bottom the page, then it 'un-splats' it, but now neither of the 2 minified windows are clickable.

### To reproduce

1. Run using docker and the mageai/mageai:latest image (sepcifically v0.9.63)
2. Open the command center
3. Open Arcane library
4. Also open Portal terminal

### Expected behavior

The two windows, portal terminal and arcane library, should both be clickable when they are both minified. When one is minified and the other one is open, we should be able to interact with the open one and not have it pop in & out of focus as we hover above it with our mouse. 

### Screenshots

![image](https://github.com/mage-ai/mage-ai/assets/118834330/f0c8bbc1-e94f-4dfb-87c2-a2c06d54eec4)

### Additional context

These unexpected behaviors weren't present in version 0.9.62

**Comment by johnson-mage** [comment]
This issue has been addressed in this [PR](https://github.com/mage-ai/mage-ai/pull/4613) and will be in the next version (0.9.65).

**Comment by johnson-mage** [comment]
v0.9.65 is available now.
