### ISSUE TITLE
[BUG] Streaming pipelines with Kafka do not run

### ISSUE THREAD

**Issue by torreslucas13** [mage-ai/mage-ai#4567]
### Mage version

0.9.63

### Describe the bug

When trying to create a streaming pipeline with Kafka as a dataloader, the pipeline does not run

### To reproduce

1. Create a new streaming pipeline with Kafka as main dataloader
2. Do the necessary configs with your broker
3. Try to run the pipeline

### Expected behavior

See kafka messages

### Screenshots

![image](https://github.com/mage-ai/mage-ai/assets/8942972/5cd53786-0eb0-4fa2-8a4c-ce0a911cca5f)

### Operating system

- OS Win 11
- Mage installed via pip

**Comment by wangxiaoyou1993** [comment]
we would recommend running Mage in docker? running on windows with pip install is a bit harder to debug.

**Comment by wangxiaoyou1993** [comment]
This issue should've been fixed in this PR (version 0.9.67) https://github.com/mage-ai/mage-ai/pull/4784
