### ISSUE TITLE
[BUG] Invalid Security contact - error 550

### ISSUE THREAD

**Issue by coderbm1** [mage-ai/mage-ai#4571]
### Mage version

NA

### Describe the bug

Can not contact Security Team - this email does not exist - error... See below

### To reproduce

Go to https://www.mage.ai/security
Scroll down to see 'security@mage.ai' as contact
Send message there - see error  '550 5.1.1 The email account that you tried to reach does not exist (...)'

### Expected behavior

Can  contact Security Team - valid email

### Screenshots

"Address not found
The message was not delivered because the recipient's address (security@mage.ai) was not found or the recipient cannot receive the message."

### Operating system

NA

**Comment by wangxiaoyou1993** [comment]
Thanks for reporting the issue. Just make the email security@mage.ai email address available. You can report issues to email address in the future. Thanks!
