### ISSUE TITLE
[BUG] Suspicious activity - mage.ai server - SECURITY

### ISSUE THREAD

**Issue by coderbm1** [mage-ai/mage-ai#4572]
### Mage version

Current Demo 2024-02-11

### Describe the bug

First of all, I would not report this via this way, but your Security email address is incorrect... I suppose it can be very important for you (time to action here is also important)...

It looks for my like **Suspicious activity**...
Is it by design? Everything's OK? Looks like compromised server, right? C2 there could be 'command and control' I suppose... If I am wrong, why there are these files (what's the purpose)? - see screenshot below

Thank you in advance. Kind regards 

### To reproduce

Repro steps:
1. Go to main site https://www.mage.ai/ and click 'Try live tool' -> https://demo.mage.ai/ (check Demo)
2. Click on the left from Menu - Terminal, type there whoami (root), maybe it is as should be, BUT
3. Type ls - see some files - please notice weird-looks files like 'combo_list.txt'
if you type 'cat combo_list.txt' you can see some logins-passwords pairs (emails and passwords)...
After short time your browser will be crashed...

### Expected behavior

Secure

### Screenshots

Screenshot 
![scr](https://github.com/mage-ai/mage-ai/assets/60202305/08fc0f46-63ef-4c55-b11e-d61c253c4554)

### Operating system

NA

**Comment by coderbm1** [comment]
@tommydangerous @wangxiaoyou1993 @johnson-mage

**Comment by wangxiaoyou1993** [comment]
Thanks for reporting the issue.
I think those files are uploaded by users. I just deleted those files.
