### ISSUE TITLE
Data Loader support on data streaming pipelines

### ISSUE THREAD

**Issue by hevertonmedeiros** [mage-ai/mage-ai#4585]
Hi I'm trying to adjust my current code for data streaming, but I'm not succeeding, it currently doesn't support data loder.

My data loader code, accesses an API and returns the data, it's very simple, it doesn't use kafka or rabbitmq, for example, I just use python code.

I continuously fetch data from the API using "all minute pipeline",  it reperesents 1440 times a day  on one pipeline, disconsidering the  all others.

Was be nice have an alternative like "data loder", to build data streaming pipelines, consuming data from external API, from services like twitter or anything. 

Will be new level of alchemy, thanks for you time.

**Comment by hevertonmedeiros** [comment]
Thank you so much, can I test this feature when? 
This is so useful for my API pipelines or any RESTful recurring data get

**Comment by wangxiaoyou1993** [comment]
@hevertonmedeiros we'll release it in version 0.9.67 today or tomorrow
