### ISSUE TITLE
Connection with ClickHouse in streaming pipelines

### ISSUE THREAD

**Issue by tuliocaviquioli** [mage-ai/mage-ai#4591]
### Mage version

v0.9.63

### Describe the bug

I'm setting up a data streaming pipeline from Kafka to ClickHouse. I can log the messages arriving from Kafka in the transformation block, so far so good. However, the connection to ClickHouse is failing. I tried to create a block with a custom connection (.py), but apparently streaming pipelines don't allow Data Exporter blocks that aren't YAML.

My issues and suggestions:

Suggestion 1: I've managed to create a connection to ClickHouse in a Python file in other pipelines, so first and foremost, a suggestion would be to allow custom blocks in streaming pipelines that aren't just YAML configuration.

Suggestion 2: Enhance documentation with examples of streaming pipelines for ClickHouse. The internet lacks examples of this working.

Issue: There seems to be some problem with the Data Exporter template in streaming pipelines.

### To reproduce

1. Start a streaming pipeline.
2. Add a Kafka-specific Data Loader block.
3. Configure Kafka:
```
connector_type: kafka
bootstrap_server: {{mage_secret_var('KAFKA_HOST')}}
topic: {{mage_secret_var('KAFKA_TOPIC')}}
consumer_group: mage-consumer
include_metadata: false
api_version: 0.10.2
```

4. Create a Data Transformation block.
5. Configure it however you like, just make sure it returns something contained in the Kafka message.
6. -- So far so good, I could verify that these blocks are working for me --
7. Create a ClickHouse-specific Data Exporter block.
8. Configure ClickHouse:
```
connector_type: clickhouse
profile: default
config:
  table_name: test_mage
```
9. Create a Trigger to run the pipeline.

### Expected behavior

Tables beeing filled.

### Operating system

Linux Machine running Mage over docker

### Additional context

LOGS:

[kafka_streaming] [KafkaSource] Start initializing consumer.

[kafka_streaming] [KafkaSource] Finish initializing consumer.

[kafka_streaming] ClickHouse initialized

[kafka_streaming] └─ Connecting to ClickHouse...

[kafka_streaming] Traceback (most recent call last):

[kafka_streaming]   File "/usr/local/lib/python3.10/site-packages/urllib3/connectionpool.py", line 715, in urlopen

[kafka_streaming]     httplib_response = self._make_request(

[kafka_streaming]   File "/usr/local/lib/python3.10/site-packages/urllib3/connectionpool.py", line 467, in _make_request

[kafka_streaming]     six.raise_from(e, None)

[kafka_streaming]   File "<string>", line 3, in raise_from

[kafka_streaming]   File "/usr/local/lib/python3.10/site-packages/urllib3/connectionpool.py", line 462, in _make_request

[kafka_streaming]     httplib_response = conn.getresponse()

[kafka_streaming]   File "/usr/local/lib/python3.10/http/client.py", line 1375, in getresponse

[kafka_streaming]     response.begin()

[kafka_streaming]   File "/usr/local/lib/python3.10/http/client.py", line 318, in begin

[kafka_streaming]     version, status, reason = self._read_status()

[kafka_streaming]   File "/usr/local/lib/python3.10/http/client.py", line 279, in _read_status

[kafka_streaming]     line = str(self.fp.readline(_MAXLINE + 1), "iso-8859-1")

[kafka_streaming]   File "/usr/local/lib/python3.10/socket.py", line 705, in readinto

[kafka_streaming]     return self._sock.recv_into(b)

[kafka_streaming] ConnectionResetError: [Errno 104] Connection reset by peer

[kafka_streaming] 

[kafka_streaming] During handling of the above exception, another exception occurred:

[kafka_streaming] Traceback (most recent call last):

[kafka_streaming]   File "/usr/local/lib/python3.10/site-packages/clickhouse_connect/driver/httpclient.py", line 409, in _raw_request

[kafka_streaming]     response = self.http.request(method, url, **kwargs)

[kafka_streaming]   File "/usr/local/lib/python3.10/site-packages/urllib3/request.py", line 81, in request

[kafka_streaming]     return self.request_encode_body(

[kafka_streaming]   File "/usr/local/lib/python3.10/site-packages/urllib3/request.py", line 173, in request_encode_body

[kafka_streaming]     return self.urlopen(method, url, **extra_kw)

[kafka_streaming]   File "/usr/local/lib/python3.10/site-packages/urllib3/poolmanager.py", line 376, in urlopen

[kafka_streaming]     response = conn.urlopen(method, u.request_uri, **kw)

[kafka_streaming]   File "/usr/local/lib/python3.10/site-packages/urllib3/connectionpool.py", line 799, in urlopen

[kafka_streaming]     retries = retries.increment(

[kafka_streaming]   File "/usr/local/lib/python3.10/site-packages/urllib3/util/retry.py", line 550, in increment

[kafka_streaming]     raise six.reraise(type(error), error, _stacktrace)

[kafka_streaming]   File "/usr/local/lib/python3.10/site-packages/urllib3/packages/six.py", line 769, in reraise

[kafka_streaming]     raise value.with_traceback(tb)

[kafka_streaming]   File "/usr/local/lib/python3.10/site-packages/urllib3/connectionpool.py", line 715, in urlopen

[kafka_streaming]     httplib_response = self._make_request(

[kafka_streaming]   File "/usr/local/lib/python3.10/site-packages/urllib3/connectionpool.py", line 467, in _make_request

[kafka_streaming]     six.raise_from(e, None)

[kafka_streaming]   File "<string>", line 3, in raise_from

[kafka_streaming]   File "/usr/local/lib/python3.10/site-packages/urllib3/connectionpool.py", line 462, in _make_request

[kafka_streaming]     httplib_response = conn.getresponse()

[kafka_streaming]   File "/usr/local/lib/python3.10/http/client.py", line 1375, in getresponse

[kafka_streaming]     response.begin()

[kafka_streaming]   File "/usr/local/lib/python3.10/http/client.py", line 318, in begin

[kafka_streaming]     version, status, reason = self._read_status()

[kafka_streaming]   File "/usr/local/lib/python3.10/http/client.py", line 279, in _read_status

[kafka_streaming]     line = str(self.fp.readline(_MAXLINE + 1), "iso-8859-1")

[kafka_streaming]   File "/usr/local/lib/python3.10/socket.py", line 705, in readinto

[kafka_streaming]     return self._sock.recv_into(b)

[kafka_streaming] urllib3.exceptions.ProtocolError: ('Connection aborted.', ConnectionResetError(104, 'Connection reset by peer'))

[kafka_streaming] 

[kafka_streaming] The above exception was the direct cause of the following exception:

[kafka_streaming] Traceback (most recent call last):

[kafka_streaming]   File "/usr/local/lib/python3.10/site-packages/mage_ai/streaming/sinks/base.py", line 24, in __init__

[kafka_streaming]     self.init_client()

[kafka_streaming]   File "/usr/local/lib/python3.10/site-packages/mage_ai/streaming/sinks/generic_io.py", line 52, in init_client

[kafka_streaming]     self.io_client = self.__io_class().with_config(config_file_loader)

[kafka_streaming]   File "/usr/local/lib/python3.10/site-packages/mage_ai/io/clickhouse.py", line 48, in with_config

[kafka_streaming]     return cls(

[kafka_streaming]   File "/usr/local/lib/python3.10/site-packages/mage_ai/io/clickhouse.py", line 33, in __init__

[kafka_streaming]     self.client = clickhouse_connect.get_client(**kwargs)

[kafka_streaming]   File "/usr/local/lib/python3.10/site-packages/clickhouse_connect/driver/__init__.py", line 111, in create_client

[kafka_streaming]     return HttpClient(interface, host, port, username, password, database, settings=settings, **kwargs)

[kafka_streaming]   File "/usr/local/lib/python3.10/site-packages/clickhouse_connect/driver/httpclient.py", line 140, in __init__

[kafka_streaming]     super().__init__(database=database,

[kafka_streaming]   File "/usr/local/lib/python3.10/site-packages/clickhouse_connect/driver/client.py", line 60, in __init__

[kafka_streaming]     tuple(self.command('SELECT version(), timezone()', use_database=False))

[kafka_streaming]   File "/usr/local/lib/python3.10/site-packages/clickhouse_connect/driver/httpclient.py", line 331, in command

[kafka_streaming]     response = self._raw_request(payload, params, headers, method, fields=fields)

[kafka_streaming]   File "/usr/local/lib/python3.10/site-packages/clickhouse_connect/driver/httpclient.py", line 420, in _raw_request

[kafka_streaming]     raise OperationalError(f'Error {ex} executing HTTP request attempt {attempts} {self.url}') from ex

[kafka_streaming] clickhouse_connect.driver.exceptions.OperationalError: Error ('Connection aborted.', ConnectionResetError(104, 'Connection reset by peer')) executing HTTP request attempt 2 http://*****************************************:8443

[kafka_streaming] 

[kafka_streaming] During handling of the above exception, another exception occurred:

[kafka_streaming] Traceback (most recent call last):

[kafka_streaming]   File "/usr/local/lib/python3.10/site-packages/mage_ai/streaming/sinks/generic_io.py", line 80, in destroy

[kafka_streaming]     if hasattr(self.io_client, 'close') and callable(self.io_client.close):

[kafka_streaming] AttributeError: 'GenericIOSink' object has no attribute 'io_client'

Pipeline kafka_streaming execution failed with error:

Traceback (most recent call last):

  File "/usr/local/lib/python3.10/site-packages/urllib3/connectionpool.py", line 715, in urlopen

    httplib_response = self._make_request(

  File "/usr/local/lib/python3.10/site-packages/urllib3/connectionpool.py", line 467, in _make_request

    six.raise_from(e, None)

  File "<string>", line 3, in raise_from

  File "/usr/local/lib/python3.10/site-packages/urllib3/connectionpool.py", line 462, in _make_request

    httplib_response = conn.getresponse()

  File "/usr/local/lib/python3.10/http/client.py", line 1375, in getresponse

    response.begin()

  File "/usr/local/lib/python3.10/http/client.py", line 318, in begin

    version, status, reason = self._read_status()

  File "/usr/local/lib/python3.10/http/client.py", line 279, in _read_status

    line = str(self.fp.readline(_MAXLINE + 1), "iso-8859-1")

  File "/usr/local/lib/python3.10/socket.py", line 705, in readinto

    return self._sock.recv_into(b)

ConnectionResetError: [Errno 104] Connection reset by peer

During handling of the above exception, another exception occurred:

Traceback (most recent call last):

  File "/usr/local/lib/python3.10/site-packages/clickhouse_connect/driver/httpclient.py", line 409, in _raw_request

    response = self.http.request(method, url, **kwargs)

  File "/usr/local/lib/python3.10/site-packages/urllib3/request.py", line 81, in request

    return self.request_encode_body(

  File "/usr/local/lib/python3.10/site-packages/urllib3/request.py", line 173, in request_encode_body

    return self.urlopen(method, url, **extra_kw)

  File "/usr/local/lib/python3.10/site-packages/urllib3/poolmanager.py", line 376, in urlopen

    response = conn.urlopen(method, u.request_uri, **kw)

  File "/usr/local/lib/python3.10/site-packages/urllib3/connectionpool.py", line 799, in urlopen

    retries = retries.increment(

  File "/usr/local/lib/python3.10/site-packages/urllib3/util/retry.py", line 550, in increment

    raise six.reraise(type(error), error, _stacktrace)

  File "/usr/local/lib/python3.10/site-packages/urllib3/packages/six.py", line 769, in reraise

    raise value.with_traceback(tb)

  File "/usr/local/lib/python3.10/site-packages/urllib3/connectionpool.py", line 715, in urlopen

    httplib_response = self._make_request(

  File "/usr/local/lib/python3.10/site-packages/urllib3/connectionpool.py", line 467, in _make_request

    six.raise_from(e, None)

  File "<string>", line 3, in raise_from

  File "/usr/local/lib/python3.10/site-packages/urllib3/connectionpool.py", line 462, in _make_request

    httplib_response = conn.getresponse()

  File "/usr/local/lib/python3.10/http/client.py", line 1375, in getresponse

    response.begin()

  File "/usr/local/lib/python3.10/http/client.py", line 318, in begin

    version, status, reason = self._read_status()

  File "/usr/local/lib/python3.10/http/client.py", line 279, in _read_status

    line = str(self.fp.readline(_MAXLINE + 1), "iso-8859-1")

  File "/usr/local/lib/python3.10/socket.py", line 705, in readinto

    return self._sock.recv_into(b)

urllib3.exceptions.ProtocolError: ('Connection aborted.', ConnectionResetError(104, 'Connection reset by peer'))

The above exception was the direct cause of the following exception:

Traceback (most recent call last):

  File "/usr/local/lib/python3.10/site-packages/mage_ai/server/websocket_server.py", line 116, in run_pipeline

    pipeline.execute_sync(

  File "/usr/local/lib/python3.10/site-packages/mage_ai/data_preparation/models/pipeline.py", line 616, in execute_sync

    StreamingPipelineExecutor(self).execute(

  File "/usr/local/lib/python3.10/site-packages/mage_ai/data_preparation/executors/streaming_pipeline_executor.py", line 97, in execute

    raise e

  File "/usr/local/lib/python3.10/site-packages/mage_ai/data_preparation/executors/streaming_pipeline_executor.py", line 87, in execute

    self.__execute_in_python(

  File "/usr/local/lib/python3.10/site-packages/mage_ai/data_preparation/executors/streaming_pipeline_executor.py", line 124, in __execute_in_python

    sinks_by_uuid[sink_block.uuid] = SinkFactory.get_sink(

  File "/usr/local/lib/python3.10/site-packages/mage_ai/streaming/sinks/sink_factory.py", line 73, in get_sink

    return GenericIOSink(config, **kwargs)

  File "/usr/local/lib/python3.10/site-packages/mage_ai/streaming/sinks/base.py", line 24, in __init__

    self.init_client()

  File "/usr/local/lib/python3.10/site-packages/mage_ai/streaming/sinks/generic_io.py", line 52, in init_client

    self.io_client = self.__io_class().with_config(config_file_loader)

  File "/usr/local/lib/python3.10/site-packages/mage_ai/io/clickhouse.py", line 48, in with_config

    return cls(

  File "/usr/local/lib/python3.10/site-packages/mage_ai/io/clickhouse.py", line 33, in __init__

    self.client = clickhouse_connect.get_client(**kwargs)

  File "/usr/local/lib/python3.10/site-packages/clickhouse_connect/driver/__init__.py", line 111, in create_client

    return HttpClient(interface, host, port, username, password, database, settings=settings, **kwargs)

  File "/usr/local/lib/python3.10/site-packages/clickhouse_connect/driver/httpclient.py", line 140, in __init__

    super().__init__(database=database,

  File "/usr/local/lib/python3.10/site-packages/clickhouse_connect/driver/client.py", line 60, in __init__

    tuple(self.command('SELECT version(), timezone()', use_database=False))

  File "/usr/local/lib/python3.10/site-packages/clickhouse_connect/driver/httpclient.py", line 331, in command

    response = self._raw_request(payload, params, headers, method, fields=fields)

  File "/usr/local/lib/python3.10/site-packages/clickhouse_connect/driver/httpclient.py", line 420, in _raw_request

    raise OperationalError(f'Error {ex} executing HTTP request attempt {attempts} {self.url}') from ex

clickhouse_connect.driver.exceptions.OperationalError: Error ('Connection aborted.', ConnectionResetError(104, 'Connection reset by peer')) executing HTTP request attempt 2 http://*****************************************:8443

**Comment by tuliocaviquioli** [comment]
Should Python 3.9 solve?

**Comment by caviquioli** [comment]
I found the error, it comes from a Default configuration at `io_config.yaml`. You guys can close

**Comment by lauradang** [comment]
@caviquioli Could you comment more? I am getting this issue as well intermittently

**Comment by tuliocaviquioli** [comment]
The default configuration of my ClickHouse at the io_config.yaml was http, it should be https
