### ISSUE TITLE
Wrong request for creating backfill in API Docs

### ISSUE THREAD

**Issue by Sejmou** [mage-ai/mage-ai#4600]
Path: /api-reference/backfills/create-backfills

In mage v0.9.64, the API request for creating backfills fails if an object with a `name` is provided in the payload, although the [docs](https://docs.mage.ai/api-reference/backfills/create-backfills) state that this is required.

![image](https://github.com/mage-ai/mage-ai/assets/31240010/cdd4e3eb-0fb5-486a-8be6-c3240efeeae5)

Things work fine if I don't include anything in the body

![image](https://github.com/mage-ai/mage-ai/assets/31240010/a08b647a-9fa4-4da1-9df5-613da4d3377d)

**Comment by Sejmou** [comment]
just realized that I was missing the wrapping { "backfill: ... } around the object in the first example. However, it also doesn't work that way. 

I also noticed that the example curl command uses PUT (should be POST).

**Comment by wangxiaoyou1993** [comment]
For POST request, include the api_key in the body.
We'll fix the doc

**Comment by wangxiaoyou1993** [comment]
The doc is updated: https://docs.mage.ai/api-reference/backfills/create-backfills
