### ISSUE TITLE
[BUG] Backfill run failed with error: Failed to read parquet file

### ISSUE THREAD

**Issue by el-grudge** [mage-ai/mage-ai#4603]
### Mage version

0.9.62

### Describe the bug

I'm trying to run a pipeline that extracts a file from a url and exports it to GCS using backfills (the loader, exporter, and pipeline yaml are attached).

The pipeline runs successfully as a standalone, but when I specify a backfill duration the loader fails with error `Exception: Failed to read parquet file: /home/src/mage_data/week_4/pipelines/export_to_gcs/.variables/3/20190201T000000/load_file_from_url/output_0/data.parquet`, even though the file was created normally.
[pipeline_log.tar.gz](https://github.com/mage-ai/mage-ai/files/14336578/pipeline_log.tar.gz)
[export_to_gcs_pyarraw.py.txt](https://github.com/mage-ai/mage-ai/files/14336582/export_to_gcs_pyarraw.py.txt)
[load_file_from_url.py.txt](https://github.com/mage-ai/mage-ai/files/14336583/load_file_from_url.py.txt)
[pipeline_metadata.yml.txt](https://github.com/mage-ai/mage-ai/files/14336584/pipeline_metadata.yml.txt)

When I tried rerunning one of the failed backfills the exporter fails with error: `AttributeError: 'list' object has no attribute 'columns'`

### To reproduce

1. create a pipeline call it export_to_gcz
2. create a loader block using code in load_file_from_url.py
3. create an exporter block using code in export_to_gcs_pyarraw.py
4. create a backfill 
5. set the startdate to 2019-01-01
6. set the startdate to 2019-12-31
7. set the interval type to month
8. set the interval duration to 1
9. run

### Expected behavior

all the files should be loaded to gcs

### Screenshots

![Screenshot from 2024-02-19 15-05-44](https://github.com/mage-ai/mage-ai/assets/7900567/475dce90-44f6-4ec2-b7ec-b2fc7b25d9bd)

**Comment by el-grudge** [comment]
I think this might have something to do with having a multiple project setup. 

I tested the pipeline in a new mage setup and the backfill worked fine

**Comment by dy46** [comment]
hey @el-grudge , can you share what your project structure looks like?

**Comment by el-grudge** [comment]
@dy46 the settings file looked like this:

projects:
  week_2: {}
  week_3: {}
  capstone_1: {} 
  week_4: {} 

The backfill works fine when i create the pipeline in a new project though, so it might be a permissions or storage issue. I will close this
