### ISSUE TITLE
[BUG] Schedule trigger extra kwargs not populated properly

### ISSUE THREAD

**Issue by dgioga** [mage-ai/mage-ai#4608]
### Mage version

0.9.64

### Describe the bug

As per the documentation (https://docs.mage.ai/orchestration/triggers/schedule-pipelines#extra-runtime-variables-from-pipeline-run)
"If your pipeline run belongs to a trigger that is scheduled, then the following extra variables are available in your Python block’s keyword arguments (e.g. kwargs)"

The following extra variables are defined:
interval_start_datetime	The datetime when the pipeline run is scheduled for.	datetime.datetime(2023, 7, 23, 7, 0, 0, 0)
interval_end_datetime	The datetime when the next pipeline run is scheduled for.	datetime.datetime(2023, 7, 24, 7, 0, 0, 0)
interval_seconds	The number of seconds between the current pipeline run and the next pipeline run.	86400
interval_start_datetime_previous	The datetime when the previous pipeline run was scheduled for.	datetime.datetime(2023, 7, 22, 7, 0, 0, 0)

Problem:
Most of the defined extra variables are set to None when running on a schedule as such it is not possible to see when a pipeline was last ran.

### To reproduce

1. Create a new Pipeline
2. Create a custom schedule trigger to run every minute (* * * *) for the pipeline
3. Create a custom python block and include the following code:
```logger = kwargs["logger"]
    logger.info("Last interval_start_datetime_previous: {}".format(kwargs["interval_start_datetime_previous"]))
    logger.info("Last interval_start_datetime: {}".format(kwargs["interval_start_datetime"]))
    logger.info("Last interval_end_datetime: {}".format(kwargs["interval_end_datetime"]))
    logger.info("Last interval_seconds: {}".format(kwargs["interval_seconds"]))
    logger.info(', '.join(['{}={!r}'.format(k, v) for k, v in kwargs.items()]))
```
4. Enable the trigger and wait for 2 consecutive runs
5. Analyze Logs 

Output:
Some out put is redacted and enclosed in square brackets
This is the output from a test run because I could not create a screenshot of the log for the actual run (local restrictions) but nevertheless the logs as part of a scheduled run look the same.
```
INFO:[block_title]:Last interval_start_datetime_previous: None
INFO:[block_title]:Last interval_start_datetime: 2024-02-20 12:04:31.680103
INFO:[block_title]:Last interval_end_datetime: 2024-02-21 12:04:31.680103
INFO:[block_title]:Last interval_seconds: None
INFO:[block_title]:env='dev', execution_date=datetime.datetime(2024, 2, 20, 12, 4, 31, 680103), interval_end_datetime=datetime.datetime(2024, 2, 21, 12, 4, 31, 680103), interval_seconds=None, interval_start_datetime=datetime.datetime(2024, 2, 20, 12, 4, 31, 680103), interval_start_datetime_previous=None, event={}, logger=<Logger [block_title] (INFO)>, configuration={}, context={}, pipeline_uuid='[pipeline_title]', block_uuid='[block_title]'
```

### Expected behavior

The extra variables associated with running a scheduled task should be return appropriate datetime objects

### Operating system

Ubuntu 22.04

### Additional context

Trying to create a pipeline that processes items provided by an API.
The API provides a way to query for items based on time.
I want to process these items incrementally on a daily basis as such I need to know what is the last run time of the pipeline so I can query the api to only provide results starting with the time of the last run.
I could use a local file data exporter and import that at on next run as well as keep track of processed items as part of this file and cross-reference but i am opening this as i believe there's a bug concerning the extra variables.

**Comment by dy46** [comment]
Hey @dgioga, thanks for opening this issue. For cron expressions, it is possible for them to be on an irregular interval, so `interval_seconds` may not make sense to calculate. However, we should be able to calculate the other variables, so I will make that change
