### ISSUE TITLE
Integer reading and display issue 

### ISSUE THREAD

**Issue by hugabora** [mage-ai/mage-ai#4616]
### Mage version

0.9.64

### Describe the bug

I am reading Integer columns from mssql. However they are read as float.

I then try converting the column to nullable int:
`data[c] = data[c].astype('Int64')`

The block w the conversion cant display the data, fails w error
`TypeError: Invalid value '' for dtype Int64`

Good thing is that the next block picks up the converted data (and in this case writes is to csv correctly).

### To reproduce

1. Create pandas w float
2. In a transformer block convert to Int64 as above
3. hit run
4. observe errors
5. optionally run an exporter, to see that data was converted, for examplse save to csv and see that a value of "1" is serialized as float "1.0" vs int "1"

### Expected behavior

Int should be read as Int from the DB in the SQL data loader, And Int should be handled properly on block output display.

### Workaround

In my case, where I target csv output I can use string values instead:
`    data[c] = data[c].map(lambda x: '' if pd.isna(x) else '{:.0f}'.format(x))`

### Screenshots
I implemented a basic example for the Int64 rendering
![image](https://github.com/mage-ai/mage-ai/assets/1854452/d25c6310-98e2-42ff-9170-891a637c9fc0)
![image](https://github.com/mage-ai/mage-ai/assets/1854452/3dca124f-2dc4-47a2-a974-3cb7d55d21a3)
![image](https://github.com/mage-ai/mage-ai/assets/1854452/2ab21c30-fa41-43f1-b850-d9a6e801b5b7)

Could add better logic here?
![image](https://github.com/mage-ai/mage-ai/assets/1854452/d9bd06d3-0ae7-4d1e-8f21-2e16d181c37f)

_No response_

**Comment by haithem-souala** [comment]
Hey,
Same error when tying to load an integer that's null from BigQuery.
