### ISSUE TITLE
Expanded unit test examples in docs, especially for mocking the io libraries

### ISSUE THREAD

**Issue by jdvermeire** [mage-ai/mage-ai#4637]
**Is your feature request related to a problem? Please describe.**
Unit testing in DE is notoriously hard due to the number of cloud systems that need to be mocked (especially for exports). It's frustrating trying to figure out how to do unit testing within Mage's framework in relation to a number of external services (S3, BigQuery, Snowflake, etc...)

**Describe the solution you'd like**
Expanded examples of unit testing in the docs, especially for exporters and loaders (as those most often require mocking external services)

**Describe alternatives you've considered**
ChatGPT, StackOverflow, PyTest documentation

**Additional context**
https://mageai.slack.com/archives/C03HTTWFEKE/p1708625970983899

**Comment by tommydangerous** [comment]
Yes, we doing this!!!

**Comment by jdvermeire** [comment]
@wangxiaoyou1993 asked me to add the issue here.

**Comment by tommydangerous** [comment]
Yes, because VCs like to count issues... as a sign of product adoption lol

**Comment by jdvermeire** [comment]
Don't tempt me. Your backlog will explode
