### ISSUE TITLE
[Bug] Issue on Trino docs

### ISSUE THREAD

**Issue by LuizPanariello** [mage-ai/mage-ai#4638]
Path: /integrations/databases/trino

**Comment by devharipragaz007** [comment]
Is this bug still open? I can work on this. Please assign this bug to me.

**Comment by johnson-mage** [comment]
> Is this bug still open? I can work on this. Please assign this bug to me.

@devharipragaz007 Yes, it's still open. And that would be great! Thank you

**Comment by devharipragaz007** [comment]
Thanks @johnson-mage for letting me know.
@LuizPanariello if you could elaborate about this bug, that would be really helpful to close this out. What is wrong with this file?

**Comment by johnson-mage** [comment]
@devharipragaz007 If you go to https://docs.mage.ai/integrations/databases/trino, it shows a "parsing error":
<img width="546" alt="image" src="https://github.com/mage-ai/mage-ai/assets/78053898/a3d141d1-89b9-4ebc-9534-999b72910cfd">

**Comment by wangxiaoyou1993** [comment]
Close this issue since the fix PR is merged.
