### ISSUE TITLE
[BUG]  MySQL Data exporter got an unexpected keyword argument 

### ISSUE THREAD

**Issue by alfianazizi** [mage-ai/mage-ai#4648]
### Mage version

v0.9.64

### Describe the bug

Got error when using Data Exporter Python -> MySQL or Raw SQL for MySQL

`TypeError: MySQL.build_create_table_command() got an unexpected keyword argument 'case_sensitive'`

MySQL version: 8.0.36-0ubuntu0.22.04.1 - (Ubuntu)

### To reproduce

1. Create Data Exporter Blocks (Python->Mysql)
2. Run the Block 

### Expected behavior

Data Inserted

### Screenshots
<img width="1395" alt="image" src="https://github.com/mage-ai/mage-ai/assets/25798004/260e57e0-ddab-453a-ba34-b244e4ff2cc1">

<img width="1044" alt="image" src="https://github.com/mage-ai/mage-ai/assets/25798004/a6b616ef-feca-48bd-a413-db51b84b9fb8">

### Operating system

Harware - MacBook Pro M1 Pro
OS - Sonoma 14.2.1
Browser - Arc Browser 1.31.1 (46755)
MySQL Server version - 8.0.36-0ubuntu0.22.04.1 - (Ubuntu)

**Comment by wangxiaoyou1993** [comment]
We've merged the fix for this issue. It'll be released in version 0.9.65
