### ISSUE TITLE
Add AzureDevops GitHub integration

### ISSUE THREAD

**Issue by sujiplr** [mage-ai/mage-ai#4649]
People are commonly using AzureDevops for their end to end development life cycle. So can we add Azure DevOps GitHub integration to Version control . So that it will be easy for people who use that .

Azure is having service principle based integration as well . This can be used in production cases , for syncing the git code , without keeping a user based token . If we can have that as well , will be great .

**Comment by wangxiaoyou1993** [comment]
PR: https://github.com/mage-ai/mage-ai/pull/4721
It'll be released in version 0.9.66

**Comment by wangxiaoyou1993** [comment]
This feature is released in version 0.9.66 https://github.com/mage-ai/mage-ai/releases

**Comment by sujiplr** [comment]
Wow amazing, I will test this
