### ISSUE TITLE
Slack 

### ISSUE THREAD

**Issue by isoctcolo** [mage-ai/mage-ai#4651]
Hello I just wanted to enter the slack of mage.ai but it is not possible. 

For invitation the workspace admin should be connected but how can I find the workspace admin without entering slack.

**Comment by isoctcolo** [comment]
Thanks but if the access is limited then it should be taken off the website in my opinion.

**Comment by chrisafl** [comment]
Sorry you misunderstand me, I am just giving +1 to your issue and expanding on the error message I received. I believe this is not intended.

**Comment by isoctcolo** [comment]
it’s ok I understood - if many people have the same issue and the access is limited or difficult that it should not point there as a community - My personal opinion.

**Comment by johnson-mage** [comment]
@isoctcolo @chrisafl Sorry for the confusion, the Slack signup link has a limit on how many people can use it which was reached recently, but we just updated the link, so you should be able to [join](mage.ai/chat) the Mage slack now if you try again. Thanks!
