### ISSUE TITLE
[BUG] Vertical Line in Dashboards

### ISSUE THREAD

**Issue by chrisafl** [mage-ai/mage-ai#4652]
### Mage version

v0.9.64

### Describe the bug

In all dashboards, there is a right border to the left-hand navigation. Based on the generated div class name (in my case ```indexstyle__DraggableStyle-sc-1lxpneo-12 fZJCIk```), I believe this is meant to be the left-hand navigation drag/resize bar (although I am unable to use it as such).

When the left-hand navigation is minimized, the right border / drag bar does not adjust its width low enough to press up against the left-hand navigation.

![image](https://github.com/mage-ai/mage-ai/assets/7001706/75ca188c-7a31-4bd3-9afb-76113873b26d)

![image](https://github.com/mage-ai/mage-ai/assets/7001706/d90b512d-545d-4c7e-866c-10b2f0f3be07)

When the left-hand navigation is expanded, the issue is either resolved, or no longer visible.

![image](https://github.com/mage-ai/mage-ai/assets/7001706/71ef722c-2cce-461d-8b36-e16088b3012f)

### To reproduce

Go to Overview > Click on Dashboard

OR

Go to any pipeline > Click on Dashboard

### Expected behavior

The drag bar should resize appropriately to be flush against the left-hand navigation.

### Operating system

Windows 11, Edge browser

**Comment by johnson-mage** [comment]
@chrisafl Thanks for bringing this to our attention, will fix it asap.

**Comment by johnson-mage** [comment]
This issue has been fixed in this [PR](https://github.com/mage-ai/mage-ai/pull/4659) and will be in the next version of Mage (v0.9.65).

**Comment by johnson-mage** [comment]
v0.9.65 is available now.
