### ISSUE TITLE
Add support for `polars` dataframes

### ISSUE THREAD

**Issue by DeflateAwning** [mage-ai/mage-ai#4661]
**Is your feature request related to a problem? Please describe.**
I wish I could use Polars dataframes with this library. They're more ergonomic than pandas, and are far faster/more efficient.

**Describe the solution you'd like**
In the same way support for pandas is integrated throughout, I wish support for polars was too.

**Describe alternatives you've considered**
PySpark and Pandas are fine, but Polars is best.

**Comment by wangxiaoyou1993** [comment]
I think the polars dataframes are already supported. You can return polars dataframe in the block.

**Comment by DeflateAwning** [comment]
Polars isn't listed in the [mage quickstart docs](https://docs.mage.ai/getting-started/setup#install-mage-dependencies-optional) at "install-mage-dependencies-optional", which made me think it's not supported (or isn't fully supported).

**Comment by isoctcolo** [comment]
https://docs.mage.ai/integrations/polars

It seems that it is supported.

**Comment by wangxiaoyou1993** [comment]
> Polars isn't listed in the [mage quickstart docs](https://docs.mage.ai/getting-started/setup#install-mage-dependencies-optional) at "install-mage-dependencies-optional", which made me think it's not supported (or isn't fully supported).

Polars is a required dependency instead of optional dependency. So it's not in the list.

**Comment by DeflateAwning** [comment]
Thanks everyone! Closing as it appears there's nothing to do here!
