### ISSUE TITLE
High file storage on EFS 

### ISSUE THREAD

**Issue by dumim** [mage-ai/mage-ai#4676]
Hi,

We have Mage running in Production, set up on AWS ECS using Terraform as recommended. The file storage system is AWS EFS as suggested. Our Mage is used primarily to read from internal APIs, transform the data within the code blocks using pandas data frames and dump them into external destinations (S3, etc.) - no data is persisted.

Our storage size is upwards of 3GB with only some of our entire Production workload running on it. EFS is extremely expensive therefore this size equates to more than $100 in storage costs alone.

Is this caused by the Docker image, or some other Mage assets? Any recommendations on how we can reduce this size? We have added log rention and cleaned up old log files with practically no change. Is there a more lightweight version of the mage image or commands to optimise the storage/size? 

![image](https://github.com/mage-ai/mage-ai/assets/30994223/9f0e2773-0c57-4505-831f-54533de38af8)

Thanks

**Comment by wangxiaoyou1993** [comment]
do you also clean up the old variables?

**Comment by dumim** [comment]
Thank you, we were not aware of that - and no, we don't. We will do that and report back.

**Comment by dumim** [comment]
Thanks for the suggestion, it did reduce the size (our retention time is 5 days), but the storage is still kicking around 2.5GB

<img width="240" alt="image" src="https://github.com/mage-ai/mage-ai/assets/30994223/d3d4b173-7620-4ff4-bbe6-b04cd2fb82d3">

![image](https://github.com/mage-ai/mage-ai/assets/30994223/b06b30c3-4486-4574-8a45-8344b8f16eb0)


Any other suggestions or a reason to why this is happening for us to understand, would be appreciated.

**Comment by dumim** [comment]
It has gone down to 1.7 today. The block variables are the culprit, thanks for the support. Closing this now

**Comment by dumim** [comment]
It has gone down to 1.7 today. The block variables are the culprit, thanks for the support. Closing this now
