### ISSUE TITLE
Documentation to query metadata

### ISSUE THREAD

**Issue by nelson-quiceno** [mage-ai/mage-ai#4677]
Please create documentation to query the database (i.e., pipeline run, block run data).

from mage_ai.orchestration.db.models.schedules import PipelineSchedule, PipelineRun, BlockRun

**Comment by wangxiaoyou1993** [comment]
Docs
https://docs.mage.ai/orchestration/triggers/database-query
https://docs.mage.ai/orchestration/pipeline-runs/database-query
