### ISSUE TITLE
[BUG] Try to convert a pandas object (numbers and string object column) to int64

### ISSUE THREAD

**Issue by csauge** [mage-ai/mage-ai#4682]
### Mage version

v0.9.65

### Describe the bug

In a data loader, download a gshhet table, store it in a pandas dataframe and return it with these columns types below.
After the execution of the block i have an error:
```
ArrowInvalid: ("Could not convert '' with type str: tried to convert to int64", 'Conversion failed for column Nombre de participants (Chiffre uniquement) with type object')
```

Types:
```
Horodateur                                                                        object
Ton nom                                                                           object
Ton prénom                                                                        object
Adresse e-mail                                                                    object
Adresse mail de ton·ta co-anim (optionnel)                                        object
Nombre de sessions que tu as animées sur cet événement                             int64
Date de l'animation                                                               object
Type d'animation                                                                  object
Nombre de participants (Chiffre uniquement)                                       object
Nombre d'animateurs (à remplir par le coordinateur)                               object
Quelle version de l'atelier as-tu animée ?                                        object
Contexte de l'animation                                                           object
Précisions sur le contexte (nom de l'école, asso, entreprise, collectivité...)    object
Code Postal du lieu de la session                                                 object
Pays                                                                              object
dtype: object
```

### To reproduce

1. Create a loader block with returning a pandas dataframe containing a column of object type with only numbers and empty strings
2. Execute the blcok to get the ArrowInvalid Exception

### Expected behavior

No exception and the column is managed as an object, not an int64

### Screenshots

<img width="1087" alt="Screenshot 2024-02-29 at 19 16 49" src="https://github.com/mage-ai/mage-ai/assets/9370091/121893d1-972e-40e6-9539-33c0424ef8d6">
<img width="1091" alt="Screenshot 2024-02-29 at 19 16 10" src="https://github.com/mage-ai/mage-ai/assets/9370091/24bbb913-8d24-472b-89ad-b1922f17d498">

### Operating system

- MacOS: Ventura 13.4.1
- Chrome: Version 122.0.6261.69 (Official Build) (arm64)

**Comment by wangxiaoyou1993** [comment]
This looks like a duplicate ticket with this one: https://github.com/mage-ai/mage-ai/issues/4616

**Comment by csauge** [comment]
> This looks like a duplicate ticket with this one: #4616

Actually this seems not the same issue (and not the same exception)
In fact here, the pandas column which cause the issue is not a int64 but just an object because it contains numbers and empty strings ("") but i do not know why it is trying to force the case of empty strings ("") to int64 even if the pandas column is an object
