### ISSUE TITLE
Conditional blocks based on block_uuid

### ISSUE THREAD

**Issue by messerzen** [mage-ai/mage-ai#4690]
I'm working with conditional blocks to trigger some blocks in case the upstream block returns a certain kind of values. For Example:

`main` block - > returns `['customer', 'items', 'region']`

The list returned by the main block is based on a input variable and can vary according to the data type present on batch. In this case, based on this values, I need to trigger `load_customer`, `load_items`, `load_region` downstream blocks. 

Based on documentation , I need to create a callback block for this, but I need to create one callback block for each condition, like this 
```
# callback 1
@condition
def evaluate_condition(data,*args, **kwargs) -> bool:
    if "customer" in data:
        return True
    else:
        return False
```

```
# callback 2
@condition
def evaluate_condition(data,*args, **kwargs) -> bool:
    if "items" in data:
        return True
    else:
        return False
```
And attach it in their respective blocks.
![image](https://github.com/mage-ai/mage-ai/assets/39966249/d6408f81-97fc-43e8-92ac-bd0a1c910c8b)

In this case, would be very helpful to create just one callback block that returns the respective uuid block to execute, for instance:

```
@condition
def evaluate_condition(data,*args, **kwargs) -> bool:
    if "customer" in data:
        return "load_customer"
   if "item" in data:
       return "load_item"
   if "item" in data:
       return "load_region"
...

in this example, `data=["customer", "clients"]` ..so I could write just one callback block, instead one block for each dimension.

**Comment by messerzen** [comment]
This code do the trick.

```
@condition
def evaluate_condition(data,*args, **kwargs) -> bool:
    if kwargs['parent_block_uuid'].replace('load_','') in ','.join(data):
        return True
    else:
        return False
```

Thanks anyway.

**Comment by csharplus** [comment]
@messerzen thanks for sharing the nice solution for this specific usage scenario for conditional blocks.
