### ISSUE TITLE
Please upgrade the dependency for typing-extensions

### ISSUE THREAD

**Issue by broomva** [mage-ai/mage-ai#4737]
It's crazy the amount of issues I'm getting when trying to install mage with poetry. Several dependencies, most notably, openai, require typing-extensions > 4.7, but the requirement in mage is so tightly defined that it does not allow for a proper installation.

```
Because no versions of openai match >1.13.3,<2.0.0
 and openai (1.13.3) depends on typing-extensions (>=4.7,<5), openai (>=1.13.3,<2.0.0) requires typing-extensions (>=4.7,<5).
And because mage-ai (0.9.65) depends on typing-extensions (4.5.0)
 and no versions of mage-ai match >0.9.65,<0.10.0, openai (>=1.13.3,<2.0.0) is incompatible with mage-ai (>=0.9.65,<0.10.0).
```

A workaround of course is using openai lower than 1.0.0, but several newer packages do use the most recent version, i.e., langchain-openai:

```
Because no versions of langchain-openai match >0.0.8,<0.0.9
 and langchain-openai (0.0.8) depends on openai (>=1.10.0,<2.0.0), langchain-openai (>=0.0.8,<0.0.9) requires openai (>=1.10.0,<2.0.0).
```

It should be good to have the dependency on typing-extension defined with a ^ or similar to enable flexible dependencies.

**Comment by wangxiaoyou1993** [comment]
we'll upgrade the versions

**Comment by wangxiaoyou1993** [comment]
The version is upgraded in this PR: https://github.com/mage-ai/mage-ai/pull/4860
