### ISSUE TITLE
[BUG] Google SSO not working

### ISSUE THREAD

**Issue by tuanchris** [mage-ai/mage-ai#4762]
### Mage version

latest

### Describe the bug

Google SSO does not work. After authentication, return to login page without logging in

**Comment by dy46** [comment]
hey @tuanchris this should be fixed in the next version. you can also try using the `mageai/mageai:alpha` docker image which should have a fix for this

**Comment by wangxiaoyou1993** [comment]
This issue should've been fixed in latest version.
