### ISSUE TITLE
[BUG] Cannot change default port

### ISSUE THREAD

**Issue by azasconstantinos** [mage-ai/mage-ai#4767]
### Mage version

0.9.66

### Describe the bug

Setting port other than 6789 fails, nextjs is looking at 6789 still

### To reproduce

1. mkdir newfolder && cd newfolder
2. docker run -it -p 8123:6789 -v $(pwd):/home/src mageai/mageai /app/run_app.sh mage start demo 
3. open http://localhost:8123 
4. blank window, console errors trying to hit http://localhost:6789/api endpoint

**Comment by wangxiaoyou1993** [comment]
@azasconstantinos check this doc: https://docs.mage.ai/development/troubleshooting#mage-doesnt-load-properly-when-running-locally

**Comment by azasconstantinos** [comment]
It's working. Thank you @wangxiaoyou1993
