### ISSUE TITLE
[BUG] Broken Facebook ads data integration pipeline with trino destination

### ISSUE THREAD

**Issue by sumanshusamarora** [mage-ai/mage-ai#4777]
### Mage version

0.9.66

### Describe the bug

The issue is actually with trino delta lake exporter in the data integration pipeline. The casting of ARRAY isn't happening properly. Almost all the stream except ads, campaigns, assets are broken.
Error -  (to be updated)

[](url)

### To reproduce

Create data integration pipeline between Facebook and trino delta lake connector and monitor pipeline insights_country

**Comment by wangxiaoyou1993** [comment]
working on the fix for it
