### ISSUE TITLE
pipelines are not running as per schedule in cloudrun

### ISSUE THREAD

**Issue by NaveenKoduri494** [mage-ai/mage-ai#4780]
Hello,

I am running mage in google cloud run and scheduled the pipelines. Storing the pipeline runs and pipeline schedule in postgresql but pipelines are not running as per schedule.

Kindly, help me if any config is required to run pipelines as per schedule on daily basis in cloud run.

![image](https://github.com/mage-ai/mage-ai/assets/92677534/7db69ae4-0234-4deb-8dcb-6a46eebb299b)

**Comment by wangxiaoyou1993** [comment]
it's being discussed in this slack thread: https://mageai.slack.com/archives/C03HTTWFEKE/p1710741023575289
