### ISSUE TITLE
Update deltalake dependency

### ISSUE THREAD

**Issue by jackmead515** [mage-ai/mage-ai#4813]
**Is your feature request related to a problem? Please describe.**
Python `deltalake` version is outdated at `0.7.0`

**Describe the solution you'd like**
Updated version of `deltalake`. It's up to `0.16.2` as of today.

**Additional context**
Many new functionalities and bug fixes have come out in later features. Like better merge support and addition helper functions. This will absolutely make working with deltalake datasets easier when working with pure python (instead of relying on an external spark cluster with java depedencies)

**Comment by wangxiaoyou1993** [comment]
We'll upgrade the version.

**Comment by Ayumi08** [comment]
This has been resolved on May 3rd with https://github.com/mage-ai/mage-ai/pull/5020

**Comment by csharplus** [comment]
The latest version of `deltalake` has been updated to the following in https://github.com/mage-ai/mage-ai/blob/master/requirements.txt

```
deltalake==0.17.4
```
