### ISSUE TITLE
dbt single model or snapshot block is not selectable [BUG] 

### ISSUE THREAD

**Issue by shayansm2** [mage-ai/mage-ai#4817]
### Mage version

 v0.9.67

### Describe the bug

I'm following [this doc](https://docs.mage.ai/guides/dbt/developing-dbt-in-mage) in order to get to know how to work with dbt in mage-ai. However in the 6th step I cannot create a "single model or snapshot block (from file) dbt block" as I click on the `my_second_dbt_model.sql` file but nothing happens.

### To reproduce

you can follow all the steps in this doc: [https://docs.mage.ai/guides/dbt/developing-dbt-in-mage](https://docs.mage.ai/guides/dbt/developing-dbt-in-mage)

### Operating system

- OS: Max
- browser: I checked on bot chrome and Microsoft edge

**Comment by johnson-mage** [comment]
@shayansm2 Thanks for reporting this, we are currently working on a fix for it, as well as some performance improvements with the DBT blocks that should be ready sometime next week. In the meantime, can you try enabling our DBT Block V2 by going to the project settings page (`/settings/workspace/preferences`) and enabling BOTH `Code block v2` and `Dbt v2` settings? Then you should be able to add dbt blocks from files.

**Comment by johnson-mage** [comment]
@shayansm2 This should be fixed in the next version (0.9.68).

**Comment by johnson-mage** [comment]
v0.9.68 has been released
