### ISSUE TITLE
[BUG] Retry configuration not working

### ISSUE THREAD

**Issue by jordi-ydteam** [mage-ai/mage-ai#4818]
### Mage version

0.9.66

### Describe the bug

I am testing a pipeline, which I had configured to retry 2 times if it fails. But I see that on failure it does not retry.

I have created a pipeline, with a very simple block:

```python
@custom
def transform_custom(*args, **kwargs):
    raise Exception("error")
    return {}
```

with the following retry_config in the pipeline metadata ( I have tried in the blocks metadata as well):

```
retry_config:
  delay: 1
  max_delay: 0
  retries: 2
```

When it fails, I don’t see that it is retrying to execute the task again.

I was waiting for this pipeline to run again as I had specified the retry configugration

![image](https://github.com/mage-ai/mage-ai/assets/135833324/5bf1e494-0f5b-4f3a-94b1-9f790aa886cf)

### To reproduce

1. Create a pipeline
2. Create a very simple block that raises an error
3. Execute the pipeline

### Expected behavior

I would expect that when it fails, it would have the same behavior as when I manually click on retry, that I can see another run of that pipeline in the UI, to identify that it has failed, but to know that it has been executed again.

### Operating system

- Docker ( locally and k8s)

**Comment by wangxiaoyou1993** [comment]
It's because you set the `max_delay` to 0.
