### ISSUE TITLE
[BUG]  Errors in setting up mongodb streaming pipeline due to typo in mongodb source file 

### ISSUE THREAD

**Issue by vatsal-kavida** [mage-ai/mage-ai#4831]
### Mage version

0.9.67

### Describe the bug

In this particular line ->[streaming_source_mongodb]( https://github.com/mage-ai/mage-ai/blob/master/mage_ai/streaming/sources/mongodb.py#L51) there is typo which is causing the following error when trying to setup streaming pipeline in mongodb  -> `"[MongoSource] Error reading from MongoDB: 'MongoDBConfig' object has no attribute 'full_documentd'"`

### To reproduce

Just try to setup a streaming pipeline in latest version of mage with mongodb as source

**Comment by wangxiaoyou1993** [comment]
Thanks for reporting the issue. We'll fix the typo

**Comment by vatsal-kavida** [comment]
> Thanks for reporting the issue. We'll fix the typo

By when can I expect a new image to be on docker hub so that I can use it

**Comment by wangxiaoyou1993** [comment]
we'll publish a new version tomorrow
