### ISSUE TITLE
Add retry configurations for streaming pipeline 

### ISSUE THREAD

**Issue by sujiplr** [mage-ai/mage-ai#4840]
Currently for streaming pipeline retry configurations is not working properly. We need to have the proper retry configurations as same as the standard pipeline. This will help to control the streaming pipeline failures.

**Comment by sujiplr** [comment]
Can you prioritize this @wangxiaoyou1993 @tommydangerous

**Comment by wangxiaoyou1993** [comment]
Yes, will prioritize
