### ISSUE TITLE
[BUG] Triggers duplicating after renaming

### ISSUE THREAD

**Issue by mrykin** [mage-ai/mage-ai#4862]
### Mage version

0.9.68

### Describe the bug

When I renaming trigger - its dulicate

example:
https://demo.mage.ai/pipelines/test_ntf_2/triggers

I create two triggers and rename it twice and four time
![image](https://github.com/mage-ai/mage-ai/assets/13833432/dd2c5a2e-09cf-479e-9ed8-674a704e6ba7)

### To reproduce

1. Open triggers
2. Create new
3. Save
4. Open trigger
5. Rename
6. Save
7. You have two triggers instead one.

### Video
https://github.com/mage-ai/mage-ai/assets/13833432/9e0b1777-2fa3-4140-aff2-4ed3492ab84d

### Additional context

setting Save triggers in code automatically - is ON

**Comment by johnson-mage** [comment]
This should be fixed in the next version (0.9.70).

**Comment by johnson-mage** [comment]
v0.9.70 has been released
