### ISSUE TITLE
Unable to Authenticate to GitLab Using Mage Documentation

### ISSUE THREAD

**Issue by gtentillier** [mage-ai/mage-ai#4869]
I'm encountering an issue while attempting to authenticate to GitLab following the guidelines outlined in the Mage documentation (https://docs.mage.ai/production/data-sync/github). Despite setting the Callback URI of my application to http://xx.xx.xxx.xxx:6789/ (where xx.xx.xxx.xxx is the IP adress of my server where the Mage container is running), I consistently receive the error message `The redirect URI included is not valid.` from GitLab during the authentication process.

I've searched both the Mage and GitLab documentation for insights into this error, but haven't found any relevant information. Can anyone provide guidance or tips on how to resolve this issue effectively?

**Comment by dy46** [comment]
hey @gtentillier can you try setting the callback URI as "http://xx.xx.xxx.xxx:6789/oauth"?

**Comment by gtentillier** [comment]
Hey, thanks, the authentication worked that way :)

**Comment by dy46** [comment]
Great to hear! I updated the documentation to clear that up too.
