### ISSUE TITLE
Multi-project platform - The Project Selection Bar disappears

### ISSUE THREAD

**Issue by kkhatke** [mage-ai/mage-ai#4880]
### Mage version

latest(0.9.68)

### Describe the bug

After setting up the latest version of Mage-AI using docker-compose for a Multi-Project Platform, the project selection bar vanishes after a while. This issue prevents the selection or switching between projects.

![mage before bug](https://github.com/mage-ai/mage-ai/assets/113087478/6a4ac491-b945-409a-8fb4-a0207982a96d)

After Bug -
![mage after bug](https://github.com/mage-ai/mage-ai/assets/113087478/129abe4b-3f4b-47a6-b8cc-21e844273920)

**Comment by johnson-mage** [comment]
Resolved in Slack. Issue due to invalid project `metadata.yaml` configuration file unable to be loaded properly.
