### ISSUE TITLE
[BUG] cannot cancel closing unsaved modified file

### ISSUE THREAD

**Issue by gtentillier** [mage-ai/mage-ai#4882]
### Mage version

v0.9.68

### Describe the bug

After having modified a file, and then trying to close it without saving the changes, a pop up windows asks if I'm sure to close it without saving changes. If I answer Ok, the expected beahaviour occurs : the file is closed without changes saved. But if I click on the Cancel button, the same behaviour occurs, but we would expect the file not to be closed, so that we don't lose our changes.

### To reproduce

- Open a file in the 'Files' window
- modify the file (like adding a word or whatever)
- click on the cross to close the file
- click the Cancel button (or the equivalent, my system is not in english)

### Expected behavior

I expect the file not to close, and not to be modified by clicking the Cancel button

### Operating system

- OS : Windows 11
- Browser : Chrome version 123.0.6312.86

**Comment by johnson-mage** [comment]
@gtentillier This issue has been resolved in PR https://github.com/mage-ai/mage-ai/pull/4975 and will be in the next version (0.9.70).
