### ISSUE TITLE
Define custom port when starting backend

### ISSUE THREAD

**Issue by ijereijere** [mage-ai/mage-ai#4925]
**Describe the solution you'd like**
This request is for the implementation of a feature that will allow a user to change the default port from 6789 to a value of their choosing, either when running "mage start" or via docker env. This can be achieved via an environment variable, ${PORT} for instance. 

The feature will enable the integration of mage into different tools, such as https://openondemand.org/, and address cases in which port randomization is necessary for web services running on servers.

**Comment by wangxiaoyou1993** [comment]
@ijereijere this feature is supported

<img width="645" alt="image" src="https://github.com/mage-ai/mage-ai/assets/80284865/8f46db99-9a45-43b3-811c-6a7e6d0b490b">

If you run Mage in docker, you can also just simply update the port mapping in docker command.
