### ISSUE TITLE
[DOCUMENTATION] - Add documentation for "Features" in Settings menu

### ISSUE THREAD

**Issue by amlloyd** [mage-ai/mage-ai#4932]
Requesting documentation for "Features" items in the Settings menu.

![image](https://github.com/mage-ai/mage-ai/assets/17985189/2f0abbfb-e184-4843-8d0e-bac9849dad8d)

**Comment by johnson-mage** [comment]
@amlloyd Got it, we'll create a doc with details.

**Comment by johnson-mage** [comment]
@amlloyd Added a doc here: https://docs.mage.ai/development/project/features
