### ISSUE TITLE
[BUG] Version Control branches

### ISSUE THREAD

**Issue by gtentillier** [mage-ai/mage-ai#4936]
### Mage version

v0.9.68

### Describe the bug

When trying to use the version control feature using GitLab as Git provider, the mage app often didn't seem to recognize the branches containing the caracter '/' like 'gtentillier/1'. The branch seems to be named 'gtentillier' according to mage. If an other branch is named 'gtentillier/2' in the same repo, mage seems to see those two branches separately (in the pulling feature, when selecting branch there are two 'gtentillier' branches, but I can't know which one corresponds to 'gtentillier/1' and 'gtentillier/2')

**Comment by dy46** [comment]
can you share a screenshot of your issue? I know roughly what your issue is, but I'm not sure about specifically where you're running into it

**Comment by gtentillier** [comment]
![Capture d'écran 2024-04-20 170139](https://github.com/mage-ai/mage-ai/assets/85692346/66e66755-bea7-4554-a7f3-f9b371680090)

**Comment by gtentillier** [comment]
It's here, clicking the "Synchronize code" doesn't update the files according to the current version of the branch specified above

**Comment by gtentillier** [comment]
here's what I got after setting up the version control, and doing a first Pull on All branches : 
![Capture d'écran 2024-04-22 142925](https://github.com/mage-ai/mage-ai/assets/85692346/604db7c9-134f-4694-b181-13a816ea4a48)
