### ISSUE TITLE
[BUG] gbk Encoding error

### ISSUE THREAD

**Issue by yanlingsishao** [mage-ai/mage-ai#4982]
### Mage version

3.9

### Describe the bug

Error reported when starting project:
UnicodeDecodeError: 'gbk' codec can't decode byte 0xa1 in position 1175: illegal multibyte sequence

### To reproduce

Windows host, image start demo, no issues found. When adding some pipelines and restarting the project, GBK encoding issues may occur

### Screenshots

![image](https://github.com/mage-ai/mage-ai/assets/28887713/30ebd8ac-7db7-48f6-ab7f-04f5f4d76816)

### Operating system

- OS：windows 10

### Additional context

After investigation, it was found that in line 297 of mageuai/cache/block-action_object/__ init__. py, after adding the encoding, the startup did not report any errors。
![image](https://github.com/mage-ai/mage-ai/assets/28887713/150d65b8-55ba-4319-9034-60c459040dea)

**Comment by wangxiaoyou1993** [comment]
Got it. We'll fix it.
