### ISSUE TITLE
Add Google Cloud Storage (GCS) as a data integration source

### ISSUE THREAD

**Issue by davekim917** [mage-ai/mage-ai#5000]
GCS is a commonly used object storage service, and especially for users working within the Google Cloud Platform it's frequently relied on for data exports/integrations with 3rd party platforms. If GCS data integration is enabled in Mage, it would open up a lot of use cases for various data pipelines and would be a huge benefit for GCP users.

**Comment by TalaatHasanin** [comment]
hey @wangxiaoyou1993 can you assign me to this issue?
