### ISSUE TITLE
[BUG] GIT_ACCESS_TOKEN Env variable no longer working

### ISSUE THREAD

**Issue by Arthidon** [mage-ai/mage-ai#5023]
### Mage version

9.70

### Describe the bug

Since 9.70 ENV Variable GIT_ACCESS_TOKEN no longer works. 
Old behavior:

- Create Project
- Register Project
- Open Version Control App
- Add Remote
- Pull all Branches from Remote

New Behavior:

- Create Project
- Register Project
- Open Version Control App
- Add Remote
- Fails authentication on Pull , All Branches from Remote

I can see that other Git Env Variables are working. Username is populated and so is HTTPS. I have made no changes to any ENV variables, only updated to version 9.70 from 9.68.

### To reproduce

- Create Project
- Register Project
- Open Version Control App
- Add Remote
- Fails authentication on Pull , All Branches from Remote

### Expected behavior

- Create Project
- Register Project
- Open Version Control App
- Add Remote
- Pull all Branches from Remote - should be succesful

### Screenshots

![image](https://github.com/mage-ai/mage-ai/assets/52332022/749ac663-263d-427f-b2d8-75d62ee4d7fb)

**Comment by dy46** [comment]
This should be resolved in the next mage release
