### ISSUE TITLE
[BUG] Clicking the copy icon for a secret does not actually copy secret name to clipboard (Windows 10)

### ISSUE THREAD

**Issue by amlloyd** [mage-ai/mage-ai#5065]
### Mage version

0.9.70

### Describe the bug

Clicking the copy icon for a secret does not actually copy secret name to clipboard. Nothing happens when clicked.
Version: 0.9.70
Server OS: Docker on Ubuntu
Client OS: Windows 10
Browser: Chrome 124.0.6367.119

### Screenshots

![image](https://github.com/mage-ai/mage-ai/assets/17985189/9cf006ca-8316-4316-83a5-1688abe9108d)

**Comment by johnson-mage** [comment]
Closing this issue since it was related to the browser settings blocking the clipboard. Clipboard would need to be allowed on the domain hosting Mage in order for the "Copy" button to be used.
