### ISSUE TITLE
[FEATURE REQUEST] More room for Secrets name so it isn't cut off. Auto-fit?

### ISSUE THREAD

**Issue by amlloyd** [mage-ai/mage-ai#5066]
**Is your feature request related to a problem? Please describe.**
Secrets' names are cut off even though plenty of room. Theses names are far more important to see than the "********".

**Describe the solution you'd like**
Requesting that the dynamic column width favors the secret name rather than having a ton of whitespace in the value area.

![image](https://github.com/mage-ai/mage-ai/assets/17985189/d05b89d4-99ba-4410-ba80-a07662c2c726)

**Comment by johnson-mage** [comment]
@amlloyd Got it, we'll make this improvement.

**Comment by johnson-mage** [comment]
Addressed in https://github.com/mage-ai/mage-ai/pull/5072. Will be available in next version of Mage.

**Comment by johnson-mage** [comment]
New version 0.9.71 was just released
