### ISSUE TITLE
[BUG] DBT block creation not working anymore

### ISSUE THREAD

**Issue by octav-s** [mage-ai/mage-ai#5084]
### Mage version

0.9.70

### Describe the bug

Unable to create a new (empty) DBT block.

The option to create new model is greyed out, it says to manually create an SQL file.

Manually creating an SQL file and then opening the model doesn't show the profile name input correctly.
The target input field doesn't show the mage profiles.

Activating DBT v2 in setting doesn't do anything meaningful (still unable to select profile - profile list does not show the mage profiles).

Unable to get DBT block to run, since the profile can't be properly selected.

At least the old DBT blocks still run..................

### To reproduce

create a damn empty DBT block and start typing the sql code if you can

then try to run the dbt block, if you can...

### Expected behavior

click on new dbt model

- get a popup to set block name and create a new sql file or select existing
- insert the block
- allow user to select mage profile

**Comment by johnson-mage** [comment]
@octav-s Saw that you closed this issue but feel free to DM me in our [Slack](mage.ai/chat) channel if you still run into this dbt issue.
