### ISSUE TITLE
fill_in_missing_values.py variable name

### ISSUE THREAD

**Issue by Sohaib90** [mage-ai/mage-ai#5140]
I was following the steps of [Quickstart](https://docs.mage.ai/getting-started/setup#docker-run) and the Docker compose template, when I noticed the transformer `fill_in_missing_values.py` has a function call [fill_missing_values_with_median()](https://github.com/mage-ai/mage-ai/blob/53a9def11f86064e0163679414a0c5bf122c95b3/mage_ai/data_preparation/templates/repo/transformers/fill_in_missing_values.py#L13). 

```python
for col in df.columns:
  values = sorted(df[col].dropna().tolist())
  median_age = values[math.floor(len(values) / 2)]
  df[[col]] = df[[col]].fillna(median_age)
```

Shouldn't the variable name `median_age` be `median` since it is not just the `Age` that is being transformed but all the columns that are returned using 

```python
def select_number_columns(df: DataFrame) -> DataFrame: 
    return df[['Age', 'Fare', 'Parch', 'Pclass', 'SibSp', 'Survived']]
```

**Comment by Sohaib90** [comment]
I can open a PR if this sounds like it needs fixing

**Comment by csharplus** [comment]
The suggested fix has been merged.
