### ISSUE TITLE
Unable to register global data product

### ISSUE THREAD

**Issue by ochieng-odera** [mage-ai/mage-ai#5155]
I am running mage in a local install using `pip install mage-ai`, I have successfuly created a pipeline and I am able to access the global data products. I have create one as captured below:

<img width="1570" alt="image" src="https://github.com/mage-ai/mage-ai/assets/133975678/9dfce32a-e781-4db6-8de3-3278250e0f63">

but when I check the global products , it keeps on displaying `There are currently no global data products registered`. Meaning that the global product is not being saved

**Comment by tramcandoit** [comment]
I've got the same issue (installing with Docker).

**Comment by wangxiaoyou1993** [comment]
working on the fix for it.

**Comment by wangxiaoyou1993** [comment]
This is fixed in version 0.9.72
