### ISSUE TITLE
[BUG] Update Workspaces not working - Multiple issues

### ISSUE THREAD

**Issue by Arthidon** [mage-ai/mage-ai#5158]
### Mage version

9.71

### Describe the bug

1. Tried updating the workspace image as show below (1). This made the workspace unusable. Stuck in pending
2. I attempted to turn off container config. It would either not hold the setting of being turned off or give an error if I left the content blank
3. tried stopping and resuming the instance an this didn't work either

**The error in EKS**
 
Warning  Failed   59m (x4 over 61m)    kubelet  Failed to pull image "mageai/mageai:9.71": rpc error: code = NotFound desc = failed to pull and unpack image "docker.io/mageai/mageai:9.71": failed to resolve reference "docker.io/mageai/mageai:9.71": docker.io/mageai/mageai:9.71: not found

### To reproduce

1. create workspace (did this in 9.70)
2. updated Workspaces Main Project to 9.71
3. selected workspace still on 9.70
5. select update
6. toggled on "Container config"
7. enter: image: mageai/mageai:0.9.70
8. selected "Update"

### Screenshots

1: update workspace
![image](https://github.com/mage-ai/mage-ai/assets/52332022/b7c55b6a-30ea-4029-ad84-b039b947e82a)
2: first attempt to disable "Configure container"
![image](https://github.com/mage-ai/mage-ai/assets/52332022/253d170b-d696-4d98-a903-17ff8d8612e1)
3: Second attempt disable "Configure container"
![image](https://github.com/mage-ai/mage-ai/assets/52332022/006cd4ec-2f1d-4b18-8a7e-7f2fd5051441)

**Comment by wangxiaoyou1993** [comment]
`mageai/mageai:9.71` this is the wrong image. It should be `mageai/mageai:0.9.71`

**Comment by Arthidon** [comment]
image: mageai/mageai:0.9.71 worked
