### ISSUE TITLE
[BUG] Crashes on launch on aarch64 due to jemalloc issues

### ISSUE THREAD

**Issue by fstolba** [mage-ai/mage-ai#5170]
### Mage version

latest (0.9.7.1)

### Describe the bug

Trying to launch current `latest` container on an aarch64 platform (an Orace Cloud Ampere Instance in this case).
Application crashes after these log lines (probably repeated):
```
magic-1     | <jemalloc>: Unsupported system page size
magic-1     | <jemalloc>: Unsupported system page size
magic-1     | memory allocation of 8 bytes failed
```

This is introduced by the dependency `polars` and has been fixed there as per https://github.com/pola-rs/polars/issues/15549 .

On a side note, pparently there are further issues with the version in use as stated in https://github.com/mage-ai/mage-ai/issues/5169 

### To reproduce

* Launch documented `docker-compose` environment on an Oracle Linux Ampere instance.

### Operating system

```
Linux xxx 5.4.17-2136.329.3.1.el8uek.aarch64 #2 SMP Tue Mar 5 01:19:51 PST 2024 aarch64 aarch64 aarch64 GNU/Linux
```

```
Red Hat Enterprise Linux release 8.10 (Ootpa)
```

### Additional context

Fixed by upgrading to `polars==0.20.31`.

**Comment by wangxiaoyou1993** [comment]
Thanks for the ticket. Will upgrade polars version.
