### ISSUE TITLE
[BUG] mage-ai 0.9.71 missing a dependency

### ISSUE THREAD

**Issue by gaspardc-met** [mage-ai/mage-ai#5186]
### Mage version

0.9.71

### Describe the bug

Upon install of `mage-ai`, errors on `mage start project` because `botocore` is missing

### To reproduce

- pip install mage-ai
- mage start project_name

### Screenshots

![image](https://github.com/mage-ai/mage-ai/assets/78359781/7eb80c96-59dd-4410-b52d-d4051477c5ce)

### Operating system

- Ubuntu (WIndows 11 WSL)
- Python 3.11

**Comment by wangxiaoyou1993** [comment]
that was a mistake and fixed in this PR: https://github.com/mage-ai/mage-ai/pull/5151
