### ISSUE TITLE
[BUG] Frontend development server at port 3000 returns 404 response

### ISSUE THREAD

**Issue by MarHash** [mage-ai/mage-ai#5233]
### Mage version

0.9.72

### Describe the bug

Following the guide [here](https://github.com/mage-ai/mage-ai/blob/master/README_dev.md) to prepare the development environment for mage frontend development, accessing frontend at port 3000 returns 404 for API requests for multiple endpoints. Accessing port 6789 is ok and no issues are encountered.

Tested on Ubuntu 24, and Debian 12 and various mage versions and still facing the same issue,

### To reproduce

1. install docker and docker-compose
2. clone repository `git clone https://github.com/mage-ai/mage-ai.git`
3. cd to the directory and 
4. run `./scripts/init.sh myrepo`
5. run `./scripts/dev.sh myrepo`

### Expected behavior

running Mage at port 3000 for development with no issues.

### Screenshots

<img width="678" alt="image" src="https://github.com/mage-ai/mage-ai/assets/69709477/4b6fd04d-b452-4638-9c4e-e7c4f656ee7e">

Logs:
<img width="848" alt="image" src="https://github.com/mage-ai/mage-ai/assets/69709477/bdd36f3b-6ae7-4f0f-89e4-28e8a3e59d7d">

### Operating system

- OS: Ubuntu 24, Debian 12
- Browser: Chrome
- Mage: 0.9.72

**Comment by johnson-mage** [comment]
@MarHash Looks like the "Request URL" endpoint should be made to port 6789 instead of 3000. Can you try going to the line in this [file](https://github.com/mage-ai/mage-ai/blob/master/mage_ai/frontend/api/utils/url.ts#L105) and adding the `{ forceDefaultPort: true }` argument to the `getHost` method? So the line looks like this instead:
```
  let path: string = `${getHost({ forceDefaultPort: true })}${opts?.excludeApi ? '' : '/api'}/${resource}`;
```

**Comment by MarHash** [comment]
@johnson-mage Thank you so much! It is fixed now.
