### ISSUE TITLE
Python 3.11

### ISSUE THREAD

**Issue by someburner** [mage-ai/mage-ai#5248]
![image](https://github.com/mage-ai/mage-ai/assets/9430255/6917b838-c7f4-4ec4-8149-4bfc073d76b0)

- Most developers, OS contributors are not going to be running systems that have python 3.10 or older.
- Python 3.11 was released nearly 2 years ago
- shoehorning everyone into using antiquated versions of python in docker does not help anyone, just adds to confusion and bugs
- Every major data-science / math / framework library supports 3.12, and has supported 3.11 for a long time- numpy, pandas, dbt, pyarrow, ipython. I guess ipython might be broken for 3.12.

If you are trying to onboard to mage ai, and have code written in python, using newer libraries with bug fixes, improvements etc, and you have shared dependencies with mageai, what are you supposed to do?

**Comment by Ayumi08** [comment]
Using a virtual environment should solve this issue? Recommended in instructions to install mage

**Comment by someburner** [comment]
I am just lamenting that if I want to hack on mage-ai source, that I have to use old libraries and an older python. Or use a newer python, but be left wondering if every problem that occurs is due to using an unsupported and untested version. Having an active project with such stale dependencies is just not a good look when considering adopting a framework. I'm just wondering if there is a reason this isn't higher on the priority list, like it is for most open source projects.
