### ISSUE TITLE
Enable nodeSelector property for k8s_executor

### ISSUE THREAD

**Issue by MosbyTheGreat** [mage-ai/mage-ai#5253]
### Description
The current supported method for specifying nodes for Kubernetes executors involves using nodeAffinity and tolerations. While these are powerful features, they can be overly complex for certain use cases. Another simpler method for selecting nodes for pods is the [nodeSelector](https://kubernetes.io/docs/concepts/scheduling-eviction/assign-pod-node/#nodeselector) property.

We are currently using the nodeSelector property on our main Mage instance to efficiently manage node selection. The nodeSelector value is inherited and forwarded to the executors. Introducing the ability to set this field in the k8s_executor_config would streamline our configuration process and enhance the flexibility of node management.

### Proposed Solution
* Update k8s_executor_config:
Add support for the nodeSelector field.
Ensure backward compatibility by making this an optional field.
* Configuration Example:
```
k8s_executor_config:
  nodeSelector:
    disktype: ssd
```

### Benefits
* Simplicity: Provides a straightforward way to specify node selection, reducing complexity compared to nodeAffinity.
* Consistency: Aligns the executor node selection process with the main instance configuration.
* Flexibility: Offers an additional method for users to control pod scheduling, enhancing overall configuration options.

**Comment by wangxiaoyou1993** [comment]
we're working on it

**Comment by isatfg** [comment]
We also require this since we want to run the mage jobs on specific nodes. We would require both nodeSelector and toleration. We need toleration because our nodes have taints and without toleration the pods wont schedule on the node.

**Comment by wangxiaoyou1993** [comment]
> We also require this since we want to run the mage jobs on specific nodes. We would require both nodeSelector and toleration. We need toleration because our nodes have taints and without toleration the pods wont schedule on the node.

i think toleration is already supported. we're adding nodeSelector.
