### ISSUE TITLE
Inefficient scheduled pipeline_run check

### ISSUE THREAD

**Issue by kreopt** [mage-ai/mage-ai#5269]
There is a very inefficient way to check if pipeline was already scheduled. Why not just query database with pipeline_uuid and execution time? After while this in-memory full-scan can lead to big performance issues

https://github.com/mage-ai/mage-ai/blob/35dfa556b5ef9e10491c85c1aadd6d8463187aaa/mage_ai/orchestration/db/models/schedules_project_platform.py#L202

**Comment by wangxiaoyou1993** [comment]
Thanks for reporting. This is fixed in this PR: https://github.com/mage-ai/mage-ai/pull/5331
