### ISSUE TITLE
Issue on docs

### ISSUE THREAD

**Issue by jayasree-gundasu** [mage-ai/mage-ai#5333]
Path: /streaming/destinations/amazon-s3

[
  "You must specify a region."
]

**Comment by Ayumi08** [comment]
I've tested it out and it seems like region is a redundant parameter. It looks like if you don't specify any one of AWS server names or null you can still access to S3 buckets in other regions. However, if you do include the parameter for the region it must be a valid region name for AWS or null so it wont error out.

**Comment by csharplus** [comment]
@Ayumi08 added some explanation in the document on the `region` parameter.
