### ISSUE TITLE
[BUG] After changing the location of .mage_data/ old triggers are not visible.

### ISSUE THREAD

**Issue by mvpkarthik1** [mage-ai/mage-ai#5346]
### Mage version

0.9.7

### Describe the bug

I have deployed mage in a machine where all my pipelines are stored.
Now I want to move that to a different directory.
I have copied .mage_data/ and /project/pipelines folder.
Now after copying I am able to see pipelines but not my triggers and secrets.
My pipelines are also inactive state.

### To reproduce

deploy mage in /home/ubuntu/xyz/abc.
 stored the .mage_data in /home/ubuntu/xyz/abc/.mage_data/..
 Copy the .mage_data/ into /home/ubuntu/pqs/urt/.mage_data/...
 Deploy the same and mount the volume accordingly.
 Now The pipelines are visible not the triggers.

### Expected behavior

I have deployed mage in a machine where all my pipelines are stored.
![image](https://github.com/user-attachments/assets/c50114d9-91d6-41bd-a2f9-decb71408616)

![image](https://github.com/user-attachments/assets/1b26ab5c-5688-4984-938d-1f64eaea3a0a)

Now I want to move that to a different directory.
I have copied .mage_data/ and /project/pipelines folder.
Now after copying I am able to see pipelines but not my triggers and secrets.
![image](https://github.com/user-attachments/assets/da131bcc-8441-441a-b9b6-a3b35f8030e2)

![image](https://github.com/user-attachments/assets/146bbcf7-32d9-4eaa-b323-d075961da31b)

My pipelines are also inactive state.

**Comment by wangxiaoyou1993** [comment]
if you don't set the MAGE_DATABASE_CONNECTION_URL env variable https://docs.mage.ai/production/databases/default#databases , it'll use the default sqlite database, which is in the mage_dat folder. So when you move that folder, the database is changed. The triggers are all saved in database.

You have the option to save triggers in code: https://docs.mage.ai/orchestration/triggers/configure-triggers-in-code
So the triggers can be kept when you change the database.
