### ISSUE TITLE
Issue on docs

### ISSUE THREAD

**Issue by josh-sawell** [mage-ai/mage-ai#5351]
Path: /production/databases/default

This makes it sound like MSSQL is supported, but Kapa.ai in Slack as well as a reply on this bug: https://github.com/mage-ai/mage-ai/issues/4681 suggest that it is not.

Please update to mention that it's not officially supported so people don't invest lots of time trying to make it work?

**Comment by wangxiaoyou1993** [comment]
Thanks for the reminder. Updated the doc: https://docs.mage.ai/production/databases/default#mssql-not-officially-supported
