### ISSUE TITLE
Add trigger name to kwargs

### ISSUE THREAD

**Issue by AndriyKhomenkoArammeem** [mage-ai/mage-ai#5370]
To understand what trigger is running, add a variable with the trigger name to kwards.

**Comment by Abdullah-Alamodi** [comment]
hello, need to know if this issue still open or closed?

**Comment by csharplus** [comment]
@Abdullah-Alamodi this issue was resolved. The relevant document for getting `trigger name` from `Extra runtime variables from pipeline run` is located at:

https://docs.mage.ai/orchestration/triggers/schedule-pipelines#extra-runtime-variables-from-pipeline-run

**Comment by Abdullah-Alamodi** [comment]
@csharplus noted with thanks 👍
