### ISSUE TITLE
[BUG] replica blocks not functioning with conditional blocks as expected

### ISSUE THREAD

**Issue by felixshier** [mage-ai/mage-ai#5401]
### Mage version

9.73

### Describe the bug

Hei I have noticed a strange behaviour in one of my pipelines.
I have the following
block_1 -> block_2 -> block_3 - block_4
block 2 has a conditional attached to not run based on the output of block_1
block_3 is a replica of a separate block
block_4 is also a replica of a separate block
when the conditional returns False, block_2 and block_3 have status=condition_failed as expected; however, block_4 gets stuck on status=initial
and strangely
if I replace block_4 with a non-replica block, the conditional works as expected and it also get status=condition_failed rather than getting stuck on status=initial

To me it seems to be an issue with a replica block being downstream of a replica block as if I move block_4 so that it is also downstream of block_2, things run as intended.

**Comment by atjhoendz** [comment]
any update on this?  also happened to me in older version v0.9.70

cc: @wangxiaoyou1993
