### ISSUE TITLE
Specify scheduler name on k8s executor

### ISSUE THREAD

**Issue by messerzen** [mage-ai/mage-ai#5411]
Is your feature request related to a problem? Please describe.
Currently, the scheduler pod name is not configurable in the k8sconfig file for Mage. This limitation forces users to rely on the default Kubernetes scheduler, which can be restrictive in scenarios where alternative schedulers are required, such as those optimized for specific workloads, custom scheduling algorithms, or multi-tenant environments. The lack of flexibility can be frustrating for users who need more control over scheduling policies to optimize resource usage or meet specific performance requirements.

Describe the solution you’d like
I would like the ability to specify the scheduler pod name directly in the k8sconfig file for Mage. This addition would allow users to easily select and switch between different schedulers without needing to modify other parts of the configuration. The change would involve adding a field where users can define the desired scheduler's name, enabling seamless integration of custom or third-party schedulers with Mage workflows.

Describe alternatives you’ve considered
Alternatives considered include manually configuring the scheduler settings at the pod level, which can be cumbersome and error-prone, especially when managing large or dynamic environments. Another alternative is to fork and modify the Mage codebase to support this feature, but this approach is not scalable, introduces maintenance overhead, and creates potential compatibility issues with future updates.

Additional context
Allowing users to specify the scheduler pod name enhances flexibility, performance, and resource optimization. It also aligns with Kubernetes' philosophy of providing configurable components, giving users the ability to fine-tune their infrastructure based on their unique needs. This feature would be particularly beneficial in environments that use advanced schedulers like Volcano for machine learning workloads, Coscheduling for multi-step workflows, or custom schedulers designed for specific business logic.

**Comment by wangxiaoyou1993** [comment]
This is published in 0.9.74
