### ISSUE TITLE
Use Redshift Merge command while replicating data to redshift for incremental load

### ISSUE THREAD

**Issue by solomoncpus** [mage-ai/mage-ai#5445]
**Is your feature request related to a problem? Please describe.**
Currently when we replicate data from mysql to redshift for incremental load it creates a temp table, inserts the records and drops and renames the temp table. This process is time consuming and blocking other sessions.
**Describe the solution you'd like**
Redshift now has merge command to upsert records for incremental loads. Please update the integration code to use merge.

**Additional context**
[Add any other context or screenshots about the feature request here.](https://docs.aws.amazon.com/redshift/latest/dg/r_MERGE.html)

**Comment by csharplus** [comment]
The relevant code to be updated is located at: https://github.com/mage-ai/mage-ai/blob/master/mage_integrations/mage_integrations/destinations/redshift/__init__.py

**Comment by csharplus** [comment]
@solomoncpus please try the suggested features enabled in https://github.com/mage-ai/mage-ai/pull/5522, and see if it works for you.
