### ISSUE TITLE
Support postgresql-client package in Base Image

### ISSUE THREAD

**Issue by jx2lee** [mage-ai/mage-ai#5468]
**Is your feature request related to a problem? Please describe.**
Mage supported two meta database, Postgres and MSSQL(Not Official).
When deploy postgres in eks, need to add live/readinessProbe for database connection.

But, in current, No client package in Dockerfile.
How we add postgres-client system package in [Dockerfile](https://github.com/mage-ai/mage-ai/blob/master/Dockerfile)?

**Describe the solution you'd like**
[L8~L23](https://github.com/mage-ai/mage-ai/blob/7699bd458d1b4b298fff45f29c924787f340e0a7/Dockerfile#L8)
```suggestions
## System Packages
RUN \
  curl https://packages.microsoft.com/keys/microsoft.asc | apt-key add - && \
  curl https://packages.microsoft.com/config/debian/11/prod.list > /etc/apt/sources.list.d/mssql-release.list && \
  apt-get -y update && \
  ACCEPT_EULA=Y apt-get -y install --no-install-recommends \
  # NFS dependencies
  nfs-common \
  # odbc dependencies
  msodbcsql18\
  unixodbc-dev \
  graphviz \
  # here ##########################################################
  # postgres dependencies
  postgres-client \
  # end here ##########################################################
  # R
  r-base && \
  apt-get clean && \
  rm -rf /var/lib/apt/lists/*
```

**Describe alternatives you've considered**
None

**Additional context**
None

**Comment by jx2lee** [comment]
if possible to contribute, i want to take.

**Comment by wangxiaoyou1993** [comment]
you can build your custom docker image using Mage image as the base image.

**Comment by wangxiaoyou1993** [comment]
```
FROM mageai/mageai:latest

# Install your custom packages

```

**Comment by jx2lee** [comment]
@wangxiaoyou1993 yeah, i know use custom docker image. but, i think mage default image should support postgres client

- mage support postgres for meta database.
- with helm, it's essential to add liveness/readiness on mageai pod(include standalone)

Any reason not to add postgres client package in default image? when using custom image, i manage our custom image..not effifcient.

**Comment by jx2lee** [comment]
in similar case, Lightdash support client package in [base image](https://github.com/lightdash/lightdash/blob/4c75cb047386cf47756d770fb983393d59753dd9/dockerfile#L87). (it used postgres as meta database)

**Comment by wangxiaoyou1993** [comment]
> @wangxiaoyou1993 yeah, i know use custom docker image. but, i think mage default image should support postgres client
> 
> * mage support postgres for meta database.
> * with helm, it's essential to add liveness/readiness on mageai pod(include standalone)
> 
> Any reason not to add postgres client package in default image? when using custom image, i manage our custom image..not effifcient.

OK. these are fair reasons. You can make change in the Dockerfile and submit a PR. We'll review it.
