### ISSUE TITLE
Connect PostgreSql database 

### ISSUE THREAD

**Issue by Stavros-Lyras** [mage-ai/mage-ai#5488]
### Mage version

0.9.74

### Describe the bug

Hello 
I run mage ai local and i want to run SQL block. I follow this [guide](https://docs.mage.ai/integrations/databases/PostgreSQL), and I set `POSTGRES_CONNECTION_METHOD: direct` and I get this error:
![Screenshot 2024-10-10 at 1 51 59 PM](https://github.com/user-attachments/assets/09613f2f-702b-4da7-9476-d6b1f2d99c86)

Thank you

### Screenshots

![Screenshot 2024-10-10 at 1 51 59 PM](https://github.com/user-attachments/assets/59309bfa-bf17-4186-b7fb-384d7bb78c57)
![Screenshot 2024-10-10 at 3 06 41 PM](https://github.com/user-attachments/assets/d749ec3d-3fa4-4de1-86a9-918215a90aad)
![Screenshot 2024-10-10 at 3 06 48 PM](https://github.com/user-attachments/assets/bba85163-4dd4-4cea-b8f0-7a8c1d5e290e)

**Comment by wangxiaoyou1993** [comment]
do you run Mage in docker? where do you host your Postgres?

**Comment by Stavros-Lyras** [comment]
> do you run Mage in docker? where do you host your Postgres? do you specify the wrong host for Postgres?

I run Postgres local on port 5432. When I run mage with docker raise this error.

**Comment by wangxiaoyou1993** [comment]
> > do you run Mage in docker? where do you host your Postgres? do you specify the wrong host for Postgres?
> 
> I run Postgres local on port 5432. When I run mage with docker, this error is raised.

You should use `host.docker.internal` as your postgres host if you run Postgres local and run Mage in docker.  https://docs.mage.ai/development/troubleshooting#cant-connect-to-local-database-from-within-mage-via-docker
