### ISSUE TITLE
How to terminate or exit Mage locally? (Not Docker)

### ISSUE THREAD

**Issue by MinaBasem** [mage-ai/mage-ai#5509]
I have been looking for hours for any way to disable/exit/terminate/close the local mage process in my linux terminal but every time I do that it just restards. I am unable to run my Docker Container because the local process is running the "mage start etl-demo" automatically and the port remains occupied by it. 

There is not a single reference in the Docs on how to terminate the process or exit mage in general.

**Comment by wangxiaoyou1993** [comment]
you can find the process id  and run `kill -9 [process_id]`

**Comment by MinaBasem** [comment]
> you can find the process id and run `kill -9 [process_id]`

I tried that plenty of times, it just restarts

**Comment by wangxiaoyou1993** [comment]
> > you can find the process id and run `kill -9 [process_id]`
> 
> I tried that plenty of times, it just restarts

do you have any background job to restart Mage automatically? i don't know how you set it up

**Comment by MinaBasem** [comment]
> > > you can find the process id and run `kill -9 [process_id]`
> > 
> > 
> > I tried that plenty of times, it just restarts
> 
> do you have any background job to restart Mage automatically? i don't know how you set it up

None, but i found a possible workaround. when i list all processes that contain the word "mage" I find 4 of them, terminating them all together in a 1 liner fixed it

**Comment by wangxiaoyou1993** [comment]
you just need to terminate the root one

**Comment by MinaBasem** [comment]
Root constantly changes process_id, so catching it in a kill command was unfeasible, I noticed the rest of them had fixed processes ids and terminated them in a 1 liner, it didn't restart after doing that

**Comment by wangxiaoyou1993** [comment]
> Root constantly changes process_id, so catching it in a kill command was unfeasible, I noticed the rest of them had fixed processes ids and terminated them in a 1 liner, it didn't restart after doing that

I'm curious about how you run Mage. sounds very wierd.

**Comment by MinaBasem** [comment]
> > Root constantly changes process_id, so catching it in a kill command was unfeasible, I noticed the rest of them had fixed processes ids and terminated them in a 1 liner, it didn't restart after doing that
> 
> I'm curious about how you run Mage. sounds very weird.

Usually through Docker but I might have pip installed it a while ago for some reason. So when i tried running the container and launching the UI, the example file was the only thing there is. So i suspect it to be a Linux process and when I did it turned out to be true. The hassle was that I wanted to do something like `mage quit` or `mage terminate` using the mage commands but found out there wasn't much there
