### ISSUE TITLE
Cannot delete Templates

### ISSUE THREAD

**Issue by gasci** [mage-ai/mage-ai#5557]
### Mage version

0..9.72

### Describe the bug

Cannot delete Template

### To reproduce

Go to Templates and try to rename or delete.

When you try to rename, it will populate another one keeping the old one.
And there is no delete button.

### Expected behavior

We should be able to delete Block templates.

### Screenshots

![Screenshot 2024-11-12 at 18 08 44](https://github.com/user-attachments/assets/c29b63f8-9c1c-4957-9d29-53431d4b4a52)

### Operating system

Kubernetes:

Helm chart 0.1.4
https://artifacthub.io/packages/helm/mageai/mageai

**Comment by wangxiaoyou1993** [comment]
@gasci you can delete the templates directly file browser

**Comment by wangxiaoyou1993** [comment]
<img width="248" alt="image" src="https://github.com/user-attachments/assets/4d8e1738-a264-411b-8ca9-cfbbad09d717">
just delete the template directly file browser
