### ISSUE TITLE
Allow reuse of existing sources and destinations in integration pipeliens

### ISSUE THREAD

**Issue by octav-s** [mage-ai/mage-ai#5560]
At the moment you have to create new sources for each integration pipeline, even if it is the same source/destination. Using same name when setting up the source/destination shows already existing error and you need to select a different name for source/destination.

Please add way to select existing source/destination alongside the existing create source/destination option

**Comment by wangxiaoyou1993** [comment]
you can drag and drop the existing source/destination from file browser to the pipeline to reuse it

**Comment by wangxiaoyou1993** [comment]
@octav-s let me know if you have problem using it

**Comment by wangxiaoyou1993** [comment]
Feel free to reopen if you still have this issue

**Comment by octav-s** [comment]
Dragging and dropping existing loaders/exporters works. Did not think of trying that. Thanks!
