### ISSUE TITLE
Instance-wide API key rotation

### ISSUE THREAD

**Issue by the-archbishop** [mage-ai/mage-ai#5618]
**Is your feature request related to a problem? Please describe.**
Our organization values strong security practices, but the application currently lacks a method to rotate the instance-wide API key. This creates a potential risk if the key is ever compromised, as there is no way to retire the compromised key or introduce a new one. This limitation also makes it challenging to adhere to security policies that mandate periodic credential rotation.

**Describe the solution you'd like**
We would like the ability to rotate the instance-wide API key through the application's interface or API. The solution could include:
- The ability to generate a new API key while keeping the existing key temporarily active to ensure a seamless transition.
- Automated expiration or deactivation of old keys after a configurable period.
- Notifications or logs indicating when a key was rotated and by whom for auditing purposes.

**Describe alternatives you've considered**
We do try to limit the key's exposure via other external controls, but this does not address the root problem of the inability to rotate the key itself.

**Additional context**
Adding this feature would align the application with modern security best practices and industry standards for credential management.

**Comment by wangxiaoyou1993** [comment]
@the-archbishop you can delete the existing api trigger and recreate it and the token will be a new one.
