### ISSUE TITLE
[BUG] Mage scheduler is getting stuck

### ISSUE THREAD

**Issue by tech-dev-ip** [mage-ai/mage-ai#5621]
### Mage version

0.9.73

### Describe the bug

We have deployed Mage on a Kubernetes (K8s) cluster with separate scheduler instance having redis setup managing the cluster and set up pipelines for at least 10 clients. Occasionally, all Mage pipelines get stuck and stop progressing due to a scheduler issue. This is critical for us because if even a single pipeline trigger fails to run in a day, it becomes a significant problem.

We have tried capturing py-spy profiles, which often point to the usage statistics API calls. Previously, when this issue occurred, it was suggested to change the help_improve_mage flag from true to false, which we did. However, despite the help_improve_mage flag already being set to false, we are still encountering the same issue. One of the profiles is attached herewith:

Scheduler profile:
![mage_k8s_15_dec_scheduler_profile](https://github.com/user-attachments/assets/08276afb-6bf2-4632-9cb4-6fbf9205f70b)

Web server profile:
![mage_k8s_15_dec_ws_profile](https://github.com/user-attachments/assets/da537583-a7cb-4bdf-88ba-14b1985d8ed9)

### To reproduce

It's an intermittent issue.

### Expected behavior

Mage scheduler should never be stuck until the resources limit has reached.

### Screenshots

![Screenshot 2024-12-16 at 11 37 30 AM](https://github.com/user-attachments/assets/47f6f8e9-f5f6-4055-992d-b770a9f3811c)
![Screenshot 2024-12-16 at 11 39 06 AM](https://github.com/user-attachments/assets/2575a093-93eb-4a15-a720-7e68e135936e)
![Screenshot 2024-12-16 at 11 41 14 AM](https://github.com/user-attachments/assets/dc2af481-bb3c-4b21-939c-e0f615c38a49)

**Comment by IWmadhuri** [comment]
Hello Team,

we are again facing same issue after this fix we have upgraded the mage version to 0.9.75 and today again we saw our pipelines got stuck.

Please find attached profile file from scheduler.

![26dec_scheduler_profiles](https://github.com/user-attachments/assets/1256839a-d9d4-4842-b6e7-507ec385207e)

**Comment by HMaker** [comment]
I think I have the same issue with Mage 0.9.73.

Sometimes Mage stops to schedule new pipeline runs from triggers. When checking logs Mage is running, no error is reported, it just sudently stops scheduling new runs. The logs is filled with the pattern below
```
magic-1  | 2025-03-24T14:40:56.178719102Z [Process 25292] Worker pool size: 9
magic-1  | 2025-03-24T14:40:56.178722602Z [Process 25292] Worker pool size: 9
magic-1  | 2025-03-24T14:40:56.178726302Z [Process 25292] Worker pool size: 9
magic-1  | 2025-03-24T14:40:56.178729902Z [Process 25292] Worker pool size: 9
magic-1  | 2025-03-24T14:40:56.178733303Z [Process 25292] Worker pool size: 9
magic-1  | 2025-03-24T14:40:56.178737003Z [Process 25292] Worker pool size: 9
magic-1  | 2025-03-24T14:40:56.178740403Z [Process 25292] Worker pool size: 9
magic-1  | 2025-03-24T14:40:56.178744503Z [Process 25292] Worker pool size: 9
magic-1  | 2025-03-24T14:40:56.178747903Z [Process 25292] Worker pool size: 9
magic-1  | 2025-03-24T14:40:56.178751703Z [Process 25292] Worker pool size: 9
magic-1  | 2025-03-24T14:40:56.178756203Z [Process 25292] Worker pool size: 9
magic-1  | 2025-03-24T14:40:56.178760103Z [Process 25292] Worker pool size: 9
magic-1  | 2025-03-24T14:40:56.178763603Z [Process 25292] Worker pool size: 9
magic-1  | 2025-03-24T14:40:56.178766903Z [Process 25292] Worker pool size: 9
magic-1  | 2025-03-24T14:40:56.178770603Z [Process 25292] Worker pool size: 9
magic-1  | 2025-03-24T14:40:56.178774003Z [Process 25292] Worker pool size: 9
magic-1  | 2025-03-24T14:40:56.178782303Z [Process 25292] Worker pool size: 9
```
it repeats indefinitely until Mage itself is restarted.

I have multiple triggers which should run every 2 hours, they just stop running for days.
Below is the log right after Mage is restarted, look it starts scheduling new runs immediately:
```
magic-1  | 2025-03-25T21:38:38.207855754Z [Process 25292] Worker pool size: 9
magic-1  | 2025-03-25T21:38:38.207859254Z [Process 25292] Worker pool size: 9
magic-1  | 2025-03-25T21:38:38.207862354Z [Process 25292] Worker pool size: 9
magic-1  | 2025-03-25T21:38:38.207865554Z [Process 25292] Worker pool size: 9
magic-1  | 2025-03-25T21:41:51.921263298Z WARNING:traitlets:Message signing is disabled.  This is insecure and not recommended!
magic-1  | 2025-03-25T21:41:51.921768103Z WARNING:traitlets:Message signing is disabled.  This is insecure and not recommended!
magic-1  | 2025-03-25T21:41:56.492955132Z Initializing global job manager:  <mage_ai.orchestration.job_manager.JobManager object at 0x76135c7e5000>
magic-1  | 2025-03-25T21:41:56.598177573Z INFO:alembic.runtime.migration:Context impl PostgresqlImpl.
magic-1  | 2025-03-25T21:41:56.598210774Z INFO:alembic.runtime.migration:Will assume transactional DDL.
magic-1  | 2025-03-25T21:41:57.576833857Z INFO:tickets_download/32/20250325T200000:{"cpu": 11.15771484375, "cpu_total": 4, "cpu_usage": 2.7894287109375, "memory": 1814.0, "memory_total": 32093.0, "memory_usage": 0.05652322936465896, "pipeline_run_id": 63579, "pipeline_schedule_id": 32, "pipeline_uuid": "tickets_download", "hostname": "c487c1f436c6", "level": "INFO", "message": "Pipeline tickets_download for run 63579 in schedule 32 is alive.", "timestamp": 1742938917.57567, "uuid": "490f0ecda5994d2086b853a92a81a057"}
magic-1  | 2025-03-25T21:41:57.589436381Z INFO:tickets_download/32/20250325T200000:{"pipeline_run_id": 63579, "pipeline_schedule_id": 32, "pipeline_uuid": "tickets_download", "hostname": "c487c1f436c6", "level": "INFO", "message": "Start a process for PipelineRun 63579", "timestamp": 1742938917.589028, "uuid": "2786693d2bd740469add64c37c35bb5a"}
magic-1  | 2025-03-25T21:41:57.598593372Z [ProcessQueue] Enqueue job pipeline_run_63579
magic-1  | 2025-03-25T21:41:57.620290487Z [Process 63] Worker pool size: 0
```

@IWmadhuri did you find a solution?

**Comment by wangxiaoyou1993** [comment]
> same issue for me. version: 0.9.76

would you mind sharing your backend logs and CPU profiling results with me? you can DM me on slack

**Comment by andexte** [comment]
same issue for me. version: 0.9.74

Edited on 2026.05.26:
The issue has resolved in the 0.9.79 release. There was a memory leak issue in earlier versions which resulted outage in system memory which resulted restarting containers and stuck pipelines.

**Comment by DevBey** [comment]
same here in all latest version

**Comment by Manantsoa12** [comment]
Same here in OSS version

**Environment**
- Mage AI OSS v0.9.79
- Google Cloud Run (Gen2)
- Revision scaling:
   - Minimum instances: 1
   - Maximum instances: 100
- Billing mode: Instance-based
- CPU is available for the entire instance lifetime.
- Metadata database: PostgreSQL
- Pipelines are triggered using Mage cron schedules.


Resolved ✔️ 
Solution : redeploy cloud Run
